apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
    namespace: extra-tools
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:k8whqaeejrqkdFHdUw==,iv:bktkD7Luf99jLQQsGmy+jaaQLiCIY1hKmhuUR+/J+sI=,tag:SUXTyqvmAOHOX8F6QOUhQQ==,type:str]
    password: ENC[AES256_GCM,data:9LXS9sAz1XjcaNJFFd+biWiNS6odhof9cc+/msQs/aWSOw==,iv:sCrK/w1St8NHWGUtFcGl0i2zvI0Q/86x3XYLUkxtAms=,tag:3JMjqPB0gZr7CZxq6doRkA==,type:str]
    api_encryption_key: ENC[AES256_GCM,data:zSl/w8QvVeBOn/Pf+MkSZYrAjqjy3UFiwVJo8s0PHqkE6xVEZZKv+mQw13Dk5OShq+zHHZzh+YigyHhpOVhwFw==,iv:hQe7kLWFjwfu1v4epHFAgeIgT+gvrWN0VRhPtv9OHPI=,tag:TdCeL12hQu7rcr/2vW7Rzg==,type:str]
    better_auth_secret: ENC[AES256_GCM,data:MqBz34M6fTaYjfVUhu2ydqJAETg/HTH5a0MGH4PJlwsdiPUkFyprn8ftGa65JJb4FBATVa38NOZ18kkyePDZEg==,iv:8xd6yP9iISNHQcHOR7DjIk4DtNkwCb0Lie9O0Oi7rtk=,tag:Xk4BoYXrpNyXFJEiMbOW7w==,type:str]
    SPARKY_FITNESS_FRONTEND_URL: ENC[AES256_GCM,data:WayNa9F1IsBM8ATfjZh2qfrCnwILzLYSPAb/2gLIFebtfTMi8veXBZcezA==,iv:3COwbe9l/1WYJTO9FCjLAjydPsllSgaPftfDwW4fbQg=,tag:+zWOIl/G3TI6btLGCQ3m4Q==,type:str]
    SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS: ENC[AES256_GCM,data:SDUr16lSBot8cjZG4zInY/Dyg2HxUONxcnwugGjqvufZUUdXE43oforM/g==,iv:glUdZIWFAZuHlJZSsxvidtTLjUkF0nOWE7tyLwyDwos=,tag:3WvxY18uNw+b9cLpTvmXkw==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:HP6aoqJ5qFMeqwz+SbrfGxCI82RTtSw4VTvdWDGvqGgPQ7KRDG0Iqegq/w==,iv:Q+6ofGqsdbWmK7tOa+ezgAdsx/fdtIKSRtnIJ2eS6sA=,tag:vh2qTzWZigrpB+TbqPjeqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGM2ZG9COUlhU3N6aGI0
            YmRxSVBXNXpNRXQyOUlhSGxkd244ejJjK0E0CkppS2VoNkYzSlQwL0k5NnRUWnJL
            M3pwUDZuaVJ5aXdvYlczZDFzcW0vTDgKLS0tIGV0Y2d1WFY2MnlYNTIvU3ROKzhB
            RFpvdWJuekVOQ2kyQUwzajF0clUzMzAKhqyD/RahfqKfI+iq3MsVLhWAGWqDaHbk
            CTpQ//ONxY1DYUmGx09XtKDZYLg40O2xCHqkgkGrB6OCJb9/vrBgiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T09:33:22Z"
    mac: ENC[AES256_GCM,data:fbGhrPcF6ooblBUMCwr/zNE4ZOzgtfiGT0miFORR7kj9PXipKrwKzBmQ8byW+4kRLEj9zkicbczHNFvsWR0pYs9ukiEBIT8It17vRcrIygaVtzz4AFUAXeWy7n4x+HEfy/mVB9r3swJ2t4KR9RJPYZi3u9AmDaJxwAHLQSRTU50=,iv:slNfttDSG1s4n6f6u7CsmYnlePTtw660LCi91LQifQM=,tag:KRRaKlXfFU78BpgmP3FmaA==,type:str]
    version: 3.13.3
