apiVersion: v1
data:
    pass: ENC[AES256_GCM,data:/N6OZJRDBhRNjjuqPVIYL0dL/eY=,iv:7lTKwmrY1Ir5MV2MqMooQFPK4tE5ibXk7fI3Ciec9jY=,tag:GRtnppSdexdGsZGCG2BvSw==,type:str]
    url: ENC[AES256_GCM,data:30VMoDsB3G1Vpfa6yN68VZbnDgc42mxfgEo5gd7iIhs+2NIoRT2u//HT69OWXKTtKoFvYe8=,iv:84ftNh51M6PZmmwLAxXtkWAB6KnTzmqWxeI9dn5Kwxc=,tag:m3XZPbV+qnb2B4ZqymCumA==,type:str]
    user: ENC[AES256_GCM,data:ah7cr1L03B2wOQ==,iv:FGO8Dd2MR3ZeWgh/ZqO/rAA5fPSXe+8nH9M3pXQeJYk=,tag:L2uvhcJKLfAKqbm91thVbw==,type:str]
kind: Secret
metadata:
    name: uptime-kuma-creds
    namespace: extra-tools
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:30:08Z"
    mac: ENC[AES256_GCM,data:bBWU6La+GRHpzZFRVCLDFwqE9aM3zX4jYzI3WfM6bRhhixRxRavr97zcHkvZnqts2uJLC2AJWkNQPSvMzStqPv4VD5kpaU6mSJpQVRHLsWOZzF6EnJ3Sazbvsvg+xZvp4dkWiLeidJFc1Q9anm8GKCNuwi8Np9sgyhusqZMASSE=,iv:Um/4P2l7jXrXgZSHAFZumm9MqbYhmVkP3qpr0e/vwLs=,tag:GefI+fmC1J4e/zdyZSIvTg==,type:str]
    version: 3.13.3
