apiVersion: v1
stringData:
    pass: ENC[AES256_GCM,data:F2AT6kNOU/WlgKOlXknJmBgsHw0=,iv:ajl79yCTie9GwlAIWxKjE1T/P8KMA7xJnITZlOP5JxY=,tag:Bz46GiwObDlh2HZBP5l18A==,type:str]
    url: ENC[AES256_GCM,data:uFqwP4hYIH9uZCc7kviadYPiLBS+RfAocebtkJtulifP2pjbN4LTRhYAVB50vUfNWyENpSc=,iv:MVMxiMOHihYMsdpSGLXrfiKWmh+31g5W+Ifh+DHYUZI=,tag:Ndf866Iun0sEhviWzRlfjg==,type:str]
    user: ENC[AES256_GCM,data:Xc/88F7c/+yBCw==,iv:9AW6lwT10svsrXW7pjKZBNWrvNQr0atBk24UTdRdhv8=,tag:rzm5bNjnS9pFNQiFfxAq0Q==,type:str]
kind: Secret
metadata:
    name: uptime-kuma-creds
    namespace: extra-tools
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:35:26Z"
    mac: ENC[AES256_GCM,data:D+TLt0iI7U1BbyBnF07JB/2Enn8vtf+xQbEC0snyEuNsz6y+gVCT+kR+1gYiDSG/gf0X9brxWlD0yAwx+HezflaxD6sNYn0wXqrZgg8dh5HxRxGGR4JzyksnMnoeb3nF5MpthR0cVg/B8lBsNvXc8GxHeFv2qMbcIoYJ9erIc0U=,iv:kvqIQT5TpuweCcLlk+5xfcxXtUUVpahWN5Ku/aqhDdc=,tag:GeQO9iaW0xTArtsLuJ6+BA==,type:str]
    version: 3.13.3
