apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-operator
  namespace: extra-tools
spec:
  clusterIP: None
  selector:
    app: uptime-kuma-operator
  ports:
    - name: dummy
      port: 80