---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: profilarr
  name: profilarr
  namespace: multimedia-factory
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/matchTag: "true"
    uptime-kuma.io/enabled: "true"
    uptime-kuma.io/type: "http"
    uptime-kuma.io/url: "http://profilarr.multimedia-factory.svc:6868"
    uptime-kuma.io/name: "profilarr"
    uptime-kuma.io/interval: "60"
    uptime-kuma.io/retries: "3"
    uptime-kuma.io/notifications: "Monitoring Bot"
    uptime-kuma.io/group: "Arr Stack"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profilarr
  template:
    metadata:
      labels:
        app: profilarr
    spec:
      containers:
        - name: profilarr
          image: ghcr.io/dictionarry-hub/profilarr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9696
          envFrom:
            - secretRef:
                name: profilarr
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: UMASK
              value: '002'
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - mountPath: /config
              name: profilarr-config
      volumes:
        - name: profilarr-config
          persistentVolumeClaim:
            claimName: profilarr-config
