---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaresolverr
  name: flaresolverr
  namespace: multimedia-factory
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/matchTag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr
          imagePullPolicy: Always
          ports:
            - containerPort: 8191
          env:
            - name: LOG_LEVEL
              value: info
