apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: database
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:DQvwpWTiE2OxOh8K2Xp3+bJVrzO0,iv:I4qon9m3hfZ7NFXkIue8j7tU0eZ3Cw6XgfjkcrKYO8c=,tag:1dX2wOclUtm4eAEMWZcCfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbUdTeFBXRURzOFF1N0ZL
            Q1Rud3V3THFJUTY4OTdqUEJucU10dmxPcVFrCkZyRjB5L2pEc3VXMFgxR3ZuWnlE
            czBndHFWdTZ0enhmaDYrVG9ZUWYxdVEKLS0tIDdJOE1KSWVSNk9ueVlsRlZKNTY2
            V21UV1VLKzlBWTdmc3g1aU5LbGo3RmcKsMaTqYi5LSDOSeQef4ZdnHhNiw80yxrV
            S2Qnav0kjsz3GDuhFD6EoRKBiJUx1Ke1APe409u6iIRsdQNvpfQl3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T10:56:48Z"
    mac: ENC[AES256_GCM,data:S4hLTcoDRuVBj0kuxNATCGMqXnXj7T+015iq5WoRZPhMRzSByxipJFas2VQ9S4N9+rS4ZVd7s3MTzsUT+CKiPE2LH/dQtpNZjIL9ExznP+bBzQW1RMuzuEP1rGR8Mj3Wi3txw60lbEBhnaFCBwkkdqeMGK94bdjmyOHghwm2rDA=,iv:uAyZSBg5ptXb31gtJ2miipJ0E4Xeqt6k9SMPSvJtbcM=,tag:m5DXM2/df5LV7qOINFhvGQ==,type:str]
    version: 3.13.3
