apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: database
spec:
  interval: 15m

  dependsOn:
    - name: mariadb-operator-crds

  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 1h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    podAnnotations:
      uptime-kuma.io/enabled: "true"
      uptime-kuma.io/type: "port"
      uptime-kuma.io/url: "mariadb-operator.database.svc:8080"
      uptime-kuma.io/name: "mariadb-operator"
      uptime-kuma.io/interval: "60"
      uptime-kuma.io/retries: "3"
      uptime-kuma.io/notifications: "Monitoring Bot"
      uptime-kuma.io/group: "Storage & Databases"
    currentNamespaceOnly: false

    metrics:
      enabled: true