apiVersion: v1
kind: Secret
metadata:
    name: mariadb-root
    namespace: database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:hCW25aLXDwG8/EmLCI5hZpRlJEAUSzGR3zXHs4iJhqE=,iv:7cYtcBy6zF8ov1WCuXPoqf6//gnW1Q1/Nd8waBTNmzY=,tag:rtrvLgNlJ+iO0dBeUKwhUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVTVMd21pY1RSOWQySkwr
            Vkk5d21IYnVyVVRIWG03eW44OVhIZE1rb21nCldEbk80UEl4allNS0Ivc1pYRUhx
            d211WGM2YkVqTm5NUHJDRlVpa2R2UU0KLS0tIEhTRHBlT0doMUNsak5OQ2lxa2Va
            OWVCYmN1eG90QjE3RUQ2L2xyaFc4M1EKq8rOtTdIcrsJo5ucnDSHRoJgRuzm0S/W
            9kQdDxxVY6AQSTHUaxPA3Z9gq2xk32ASiYs48riOIZBvwZ1+/5Kcvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T14:04:58Z"
    mac: ENC[AES256_GCM,data:cXN31DaF8IJ8LSCaVZHWnWS5SW2mC3Mmv5quNhP7WIV6BsepBOoLOl8QHsS/Yw9T5TLE4UVFZDSd0YYRQ8uAMxcT+PwN9XtqzEes9tls9rqLf+u5x9I2DNQEVjpX9QAVBIFD4+5QfWkGbxoy5NuoDYKWEJE5EO8gYS68Sq/unxY=,iv:yVIspIKAaZNuVziVQeLOtQXlYNSPb8rWeol2PdhhFUE=,tag:WQ4zzZL0zRygo2/pnxoYjA==,type:str]
    version: 3.13.3
