apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boxarr-config
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: boxarr-config
