apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: youtarr
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: lingarr
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: romm
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: grimmory
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
