apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: youtarr
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  username: youtarr
  database: youtarr
  privileges:
    - ALL

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: lingarr
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  username: lingarr
  database: lingarr
  privileges:
    - ALL

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: romm
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  username: romm
  database: romm
  privileges:
    - ALL

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grimmory
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
  username: grimmory
  database: grimmory
  privileges:
    - ALL
