apiVersion: v1
kind: Secret
metadata:
    name: mariadb-app-passwords
    namespace: database
type: Opaque
stringData:
    youtarr: ENC[AES256_GCM,data:levzzSlhDGlXcJ9lyI4=,iv:e/WE7+sGm0/yUInFq9XAhGzuwGx6eFMLWgX6yewT4UI=,tag:fq7cIq2GrxJhErvfeJxh3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZkdnUnpPTXdyamZrYkFm
            NDhGOFFRVEtpdy94MkNuTHpWRGZDckhjUFVnClpITFI1ZGRBNkRQRjJ6eXVrQXUy
            U1RsZnFyYXk0KzFtcUJvTEhMNW1XZHMKLS0tIGRERkRQaVBlQkkxV3ZxeFNlR0hi
            NGN2Y0R0ZTJ5NjZVMmJkWmtyT1N4RWsK0LBx4QWxa/UxThI/3703Un6aYh8gRyk6
            +9OxbtOHPuYGAxxDgNwMTVmu81S0hB0lX8nMu2LR0srlzuDaOi5fcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T14:14:30Z"
    mac: ENC[AES256_GCM,data:jmA5QpejmBocRjq3JmMSNJNAwhZUky6yT6rECMwN6fB99VilIg5aH2y6Zbs2xoYeDvqpB3babbgiwsO84pIZquBVvSvsYBf3/H/1byBEhHT6kPiQQVLikOrpGYqF22nPfdc/5PDRkLgN6MIFPyvis/vvwDUkJpdDZwhAakJu+Uo=,iv:eFu53MP9R51h50/aHv2h0ZVO8zjeDnZRco1jvsOBqzs=,tag:L3cgwWJ/Uo2BUVdtDp+p+w==,type:str]
    version: 3.13.3
