apiVersion: v1
kind: Secret
metadata:
    name: mariadb-app-passwords
    namespace: database
type: Opaque
stringData:
    youtarr: ENC[AES256_GCM,data:levzzSlhDGlXcJ9lyI4=,iv:e/WE7+sGm0/yUInFq9XAhGzuwGx6eFMLWgX6yewT4UI=,tag:fq7cIq2GrxJhErvfeJxh3g==,type:str]
    lingarr: ENC[AES256_GCM,data:QYiSmcHSJToSkuFvFjpX,iv:EXMKd2YVFSy/FfHwlSloxLA+00uy+rFzvmjtskYqXTM=,tag:jbFOsbS3T5sMq03alKuZjw==,type:str]
    grimmory: ENC[AES256_GCM,data:OHUPm7sGzUdxmzMZTCnIs4Q=,iv:Oi3Q6wBOd7UUO7r8m29AVhkmHIE1VejumyTIkWN3+4A=,tag:DoQSBkA0ag7FyEB15szXrQ==,type:str]
    romm: ENC[AES256_GCM,data:Mn04qfsYB/OMrJogWIV1bdIJ,iv:GpVk39irafQGOydUvxRyQGdiybr6kpkMbWhGpxDxBh4=,tag:v9/ioIlGhbPL5oa+JKZhbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZkdnUnpPTXdyamZrYkFm
            NDhGOFFRVEtpdy94MkNuTHpWRGZDckhjUFVnClpITFI1ZGRBNkRQRjJ6eXVrQXUy
            U1RsZnFyYXk0KzFtcUJvTEhMNW1XZHMKLS0tIGRERkRQaVBlQkkxV3ZxeFNlR0hi
            NGN2Y0R0ZTJ5NjZVMmJkWmtyT1N4RWsK0LBx4QWxa/UxThI/3703Un6aYh8gRyk6
            +9OxbtOHPuYGAxxDgNwMTVmu81S0hB0lX8nMu2LR0srlzuDaOi5fcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T14:35:43Z"
    mac: ENC[AES256_GCM,data:3SvlHLSluYd2mP8PVG3zuGEJFK+eeKNF5iMCc5eBElZE8vVcampCbCERFBgFeIUSV18Pi4uWBcJkcjqre6H/Km1CzgPzZc/tsOUNwfFQ32msb/5DmYpQzLEKCMobk+/VxVSBpV3DZgPIYSD+0B80D9FTqYPTJkeStDkYqE5HGgs=,iv:bS573VEWjQNE6OhjngKoBO8dLn6jG8PLhZ0c0HK4B3U=,tag:Ido5jAQPjNEz+ek0CxF9tw==,type:str]
    version: 3.13.3
