apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
spec:
    acme:
        email: sottile.alessandro10@gmail.com
        privateKeySecretRef:
            name: letsencrypt-apigateway-staging
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        key: api-token
                        name: cert-manager
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbHNVdml6d3NtMHY2bDRZ
            WDlEcnZpU1hFL0xPZVlncmJHaDBKZTgxeGkwCjVrcUhqU1dWRGFjZnB2Tld2WmMr
            QXJjNWRYMVpwUVR0Yy9aOThXV3ZBOE0KLS0tIG9yamRRazl4T2NpNHc0NDhDa3Rj
            UjZzbVRDNTF5RWtVcisxVUs3SnNJbW8KxLwb8/37/hgwlCOICCktt36DVhlPB3OA
            9jOCUQYwc2bXg3HOEQKIxfcC36t0iPcs+kQx6+FhGw64XexewyLb3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T09:53:52Z"
    mac: ENC[AES256_GCM,data:uVX5lKc0BotsqhLWEX3yHn9FZLAQpXR9xYznI7eqCFzRIE//gl/6xxkxuztrIc53lWLm38+NpRULzc27DL7mA9i6fNiRgsKca0Sv0Kn5dX5AGFsf0plOXXfMDBug9e6k2mfNJQtDw+P5uvXTReQVcNhmBGt/ie5GYGCPF4xc5oM=,iv:SMpBhUQhQQEsFlvFJMqwBvwAJiUylg5s+cbByHGqcQo=,tag:7EbGNiAiLtlGqudN2bZNvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
