apiVersion: v1
kind: Secret
metadata:
    name: unifi-youtube-pbr-credentials-x
    namespace: system-addon
type: Opaque
stringData:
    UNIFI_HOST: ENC[AES256_GCM,data:0z+IHH16zwb5sZw=,iv:vhtd6QUrM1n+uuTaG3UWkiuuzXEgTr04npojQ9IR6JY=,tag:+J3/5dc984IRStIGldeDTg==,type:str]
    UNIFI_USERNAME: ENC[AES256_GCM,data:dtd7fDbqATL8NWyLJIE=,iv:gM2ekf4mHr091UI1keRaiNl5CoGQDWXH52aWZF/I2HQ=,tag:KHhyXOcP2Q//DQZw2y+iPA==,type:str]
    UNIFI_PASSWORD_ENCRYPTED: ENC[AES256_GCM,data:6o6SefxH2PRi2WIrsnlExYIefeEXfvOucO3WuUYZIUqhSvo/8LuMbZShl8s6dsAgTsPUz2grpIMrJskoq4xuHeCjeeqgeklReZyFRcEtUeD6rlGvsFQ+DpLC6/zm1OE2kG2EGMpLR/Nb6LFQdfVID7QI097Cg+j66WBdnNbvz3oAq5XYtaA1AGTmqQovChCJDelIY9i1O/A1e4Av1p+JQE81IGEnmhjtNEbOEJejDUkRZgbDQ2VgXMMJUNuNvvBYaUiKFVwHA0hCnCJFhWgNxEYnrU85l4e2EtmrYBk/ow==,iv:z/lDYv+1wtXkwboeIZwvB1c3ZSYpHCSAzcQOygL3O4A=,tag:Klv8myL7tdBiZIQuyMBX9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXQyZjhIdHBYdkZveENt
            Sm1DUWZROEdIZXloRkRQS2pFaVZaTU5uVW1vCkVRek11dThDeWUxd2RjYlRVcm5E
            TXErV2FiVnlKUXNlQ0NIUld4SDhSazgKLS0tIFBuZC9JR1JHZldmMjdPMEFDVFBn
            Mis0R2ZCamdFZzBsaXJpSkpLdEN4UDAKtW2VF4z2EuVVLDuXfxQmpv3wmyDk0CcU
            wVefXh2ohaXfaACMNWDpyTJ0B337XiKOoO7Udgwtj6EYUpDqgWknog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T10:00:09Z"
    mac: ENC[AES256_GCM,data:g6/Bh2c9L9KbAKkAvGnewYMt1ukeVql8wj/FeGZDN9girjku1irAdU0ZFhq2dBBZYEIFZTbIvzlQsOcNY1u4KQfWpZau/DVrdls3ga8e5SPkYjYgiDdc4DNtRLb1Fq/uVTUaIjpMtWzPm48uhyyQccDizbIz3BIM+hRYbhzmjaA=,iv:4ygXtbKkl687qFFmX7WtzPJG36sEEVZgwiGL7ohSRB0=,tag:7URKSifPRy7IlSpmQV8gMg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: unifi-youtube-pbr-decryption-key-x
    namespace: system-addon
type: Opaque
stringData:
    UNIFI_DECRYPTION_PASSPHRASE: ENC[AES256_GCM,data:8FMibBZ8SPVQ6BWxx9La3Z0r1hHHHfk6FJ7H3mLY3tE=,iv:GgEI7cd0m3Pd69HiajfFBSP7P1wUmtQ0/Fz4sPpr1v4=,tag:y2jERjkC2pHpjjmb44at7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXQyZjhIdHBYdkZveENt
            Sm1DUWZROEdIZXloRkRQS2pFaVZaTU5uVW1vCkVRek11dThDeWUxd2RjYlRVcm5E
            TXErV2FiVnlKUXNlQ0NIUld4SDhSazgKLS0tIFBuZC9JR1JHZldmMjdPMEFDVFBn
            Mis0R2ZCamdFZzBsaXJpSkpLdEN4UDAKtW2VF4z2EuVVLDuXfxQmpv3wmyDk0CcU
            wVefXh2ohaXfaACMNWDpyTJ0B337XiKOoO7Udgwtj6EYUpDqgWknog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T10:00:09Z"
    mac: ENC[AES256_GCM,data:g6/Bh2c9L9KbAKkAvGnewYMt1ukeVql8wj/FeGZDN9girjku1irAdU0ZFhq2dBBZYEIFZTbIvzlQsOcNY1u4KQfWpZau/DVrdls3ga8e5SPkYjYgiDdc4DNtRLb1Fq/uVTUaIjpMtWzPm48uhyyQccDizbIz3BIM+hRYbhzmjaA=,iv:4ygXtbKkl687qFFmX7WtzPJG36sEEVZgwiGL7ohSRB0=,tag:7URKSifPRy7IlSpmQV8gMg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: unifi-youtube-pbr-credentials-y
    namespace: system-addon
type: Opaque
stringData:
    UNIFI_HOST: ENC[AES256_GCM,data:bA1DTRg+Fd8qm9vh,iv:7ZRQ47ycbZkaHlNjRG2PsvdvwFaaVcw6Rz6WAysB5jQ=,tag:BNwx+fZLdA2GletcPPKI3w==,type:str]
    UNIFI_USERNAME: ENC[AES256_GCM,data:XfzQg6wYzOzpzV1Nt+s=,iv:XXdfE/VLgd5TeEZ9ouajoUfMOqLXrb4iaSfy6Q+1upo=,tag:Jx16wUSn2t/igRrfEUirig==,type:str]
    UNIFI_PASSWORD_ENCRYPTED: ENC[AES256_GCM,data:UYnIe2GB6S6JwyTDYlCdXNUCQf3QIKq7h7z8PHprRokwr1LDlEEb8QNkyr0ZT+j9p6xJnIN2NVz6eRXsGpoz8Kb0VkpzDGBbtddmOQN4lK/Sok0l+n3dSqvo+PVgWUUPQ5nBXsBPiqN3xBtSIynxMM9Nws7zd06NLBbmfMEaY3+PXwO+iWAcMgBdPm+K5ODQlln1eXlX68n9va9U2cGMgIR/ToMDQpx2xlHy4Dvj7HPm8NHBfsivr4BmGK2AR4fEqnHyhTy+4euZIXlcQmA5ihqWaVqsqUTYqjzNYmXBSQ==,iv:gfPoQUVh7z+upZAF9jl5BY5rqseum7ykPsOd0VIlT3E=,tag:NfSJXFb+JrN0TpYhM6kqBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXQyZjhIdHBYdkZveENt
            Sm1DUWZROEdIZXloRkRQS2pFaVZaTU5uVW1vCkVRek11dThDeWUxd2RjYlRVcm5E
            TXErV2FiVnlKUXNlQ0NIUld4SDhSazgKLS0tIFBuZC9JR1JHZldmMjdPMEFDVFBn
            Mis0R2ZCamdFZzBsaXJpSkpLdEN4UDAKtW2VF4z2EuVVLDuXfxQmpv3wmyDk0CcU
            wVefXh2ohaXfaACMNWDpyTJ0B337XiKOoO7Udgwtj6EYUpDqgWknog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T10:00:09Z"
    mac: ENC[AES256_GCM,data:g6/Bh2c9L9KbAKkAvGnewYMt1ukeVql8wj/FeGZDN9girjku1irAdU0ZFhq2dBBZYEIFZTbIvzlQsOcNY1u4KQfWpZau/DVrdls3ga8e5SPkYjYgiDdc4DNtRLb1Fq/uVTUaIjpMtWzPm48uhyyQccDizbIz3BIM+hRYbhzmjaA=,iv:4ygXtbKkl687qFFmX7WtzPJG36sEEVZgwiGL7ohSRB0=,tag:7URKSifPRy7IlSpmQV8gMg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: unifi-youtube-pbr-decryption-key-y
    namespace: system-addon
type: Opaque
stringData:
    UNIFI_DECRYPTION_PASSPHRASE: ENC[AES256_GCM,data:3IQOfYi+TX+plkPADvvai5If7Tc4mcNLL2wOr28zKnQ=,iv:7eZ67AwApEjwhWuswn38bI+4YhGNGqgq4/H6sxPYo1k=,tag:d9MAxz0O0FFXadzEQVjEFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXQyZjhIdHBYdkZveENt
            Sm1DUWZROEdIZXloRkRQS2pFaVZaTU5uVW1vCkVRek11dThDeWUxd2RjYlRVcm5E
            TXErV2FiVnlKUXNlQ0NIUld4SDhSazgKLS0tIFBuZC9JR1JHZldmMjdPMEFDVFBn
            Mis0R2ZCamdFZzBsaXJpSkpLdEN4UDAKtW2VF4z2EuVVLDuXfxQmpv3wmyDk0CcU
            wVefXh2ohaXfaACMNWDpyTJ0B337XiKOoO7Udgwtj6EYUpDqgWknog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T10:00:09Z"
    mac: ENC[AES256_GCM,data:g6/Bh2c9L9KbAKkAvGnewYMt1ukeVql8wj/FeGZDN9girjku1irAdU0ZFhq2dBBZYEIFZTbIvzlQsOcNY1u4KQfWpZau/DVrdls3ga8e5SPkYjYgiDdc4DNtRLb1Fq/uVTUaIjpMtWzPm48uhyyQccDizbIz3BIM+hRYbhzmjaA=,iv:4ygXtbKkl687qFFmX7WtzPJG36sEEVZgwiGL7ohSRB0=,tag:7URKSifPRy7IlSpmQV8gMg==,type:str]
    version: 3.13.2
