---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-postgres
  namespace: system-addon
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: crowdsec-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-data
  namespace: system-addon
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: crowdsec-data
