apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-secrets
    namespace: system-addon
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:nawuUZcrSSg=,iv:PWyFp0MnXIoeQXQ4v4JqXz41FexArIglORsbEwV+YIc=,tag:pGo39MqmlNzbIXHE3DXnuQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:zbqvuXTD9y4=,iv:E0trzhz6Yo7bUqcsDhINoNj0ep04PX0EtHQejDo043s=,tag:PMOFRpLKZFS9vvofEg658Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a4LTBm6YfnzkMmSzgELUZLx4ilY+f0w=,iv:ozKNZ0oDYl/tWGd9F3vyG5LAxG/ZznK+8kzeTtdMipU=,tag:0YB0PjXGXZUrlixO12h6Mg==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T08:28:50Z"
    mac: ENC[AES256_GCM,data:rhoKAJFA39TrvYuLODO0ceMIZjRqjTAGD3iiugtBa2ncrGdPEX1+YvUmmSG+8vFT8hgpXkvPyaC39wN110Dp6neduobEgHJfUmZWRhR+hxdOotaAXbkbG59N4Gdd3wd2bVxGfwfpkyvnAvNFhwD4WdlqK4g4ONSrG7j6RySpEP0=,iv:aalL3u571dylp02CpbcT5Avw0Mn9Hiezd3ccu7+hGaY=,tag:F7C69STRr38UHBfGGxlqWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-postgres-secret
    namespace: system-addon
    labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: crowdsec-postgres
        app.kubernetes.io/component: database
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:zbqvuXTD9y4=,iv:E0trzhz6Yo7bUqcsDhINoNj0ep04PX0EtHQejDo043s=,tag:PMOFRpLKZFS9vvofEg658Q==,type:str]
    #ENC[AES256_GCM,data:Q2EF4X588jXgyB2PS1kClJ6pAxW5OsG50qSYLAMeaoXT0HtsDqihq0XUwXRoKWYI/j7vdRWX,iv:YBlmdx87NPikidPwORWHXjXa/hPq5EqvPkDuDOM22ZA=,tag:ZOnVZ+c7L7ruiOSvFqu6BQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a4LTBm6YfnzkMmSzgELUZLx4ilY+f0w=,iv:ozKNZ0oDYl/tWGd9F3vyG5LAxG/ZznK+8kzeTtdMipU=,tag:0YB0PjXGXZUrlixO12h6Mg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:nawuUZcrSSg=,iv:PWyFp0MnXIoeQXQ4v4JqXz41FexArIglORsbEwV+YIc=,tag:pGo39MqmlNzbIXHE3DXnuQ==,type:str]
    #ENC[AES256_GCM,data:ZaCNlVKQgm9SupQwbppfpcfQLeG7Uvu0Z9C1nktm8qvkxaKauoqfrruX0MAr4SaHfjn9RyRkjZwVtuMuIM6IFBCAYw==,iv:N+atmFkGbHUVNlYPBgMYAYzqTOoVj3tmT3W/EnvH8Kw=,tag:7YR5tWIcxzfAso3bz1v29Q==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:Wf4xnJeKg6VD5C0xSDNF83tC8BQ5NpHbbYmAWZbvu6/qZpy1MlkpPnSbTXSL3e1jDElkNegCrbDt4GT1lVxYBoYjlo6hSz9zi4IPAGs=,iv:KIdw0fy8LfjsE/khKDB6hCiVlFEKqlZILxkoR3NAdzs=,tag:gTaAYmI6kNwbWbAKpPBGvg==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T08:28:50Z"
    mac: ENC[AES256_GCM,data:rhoKAJFA39TrvYuLODO0ceMIZjRqjTAGD3iiugtBa2ncrGdPEX1+YvUmmSG+8vFT8hgpXkvPyaC39wN110Dp6neduobEgHJfUmZWRhR+hxdOotaAXbkbG59N4Gdd3wd2bVxGfwfpkyvnAvNFhwD4WdlqK4g4ONSrG7j6RySpEP0=,iv:aalL3u571dylp02CpbcT5Avw0Mn9Hiezd3ccu7+hGaY=,tag:F7C69STRr38UHBfGGxlqWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T08:28:50Z"
    mac: ENC[AES256_GCM,data:rhoKAJFA39TrvYuLODO0ceMIZjRqjTAGD3iiugtBa2ncrGdPEX1+YvUmmSG+8vFT8hgpXkvPyaC39wN110Dp6neduobEgHJfUmZWRhR+hxdOotaAXbkbG59N4Gdd3wd2bVxGfwfpkyvnAvNFhwD4WdlqK4g4ONSrG7j6RySpEP0=,iv:aalL3u571dylp02CpbcT5Avw0Mn9Hiezd3ccu7+hGaY=,tag:F7C69STRr38UHBfGGxlqWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
# ATTENZIONE: in produzione usa sealed-secrets o external-secrets per non
# committare credenziali in chiaro nel repo git.
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-keys
    namespace: system-addon
    labels:
        app.kubernetes.io/name: crowdsec
        app.kubernetes.io/managed-by: flux
type: Opaque
stringData:
    #ENC[AES256_GCM,data:DBqLs+6vzXTFI2jncKZ6fjU+KLUQY/AsOQyV4HCYyuflB0ir/hjSTquhNAarp98R7uK2ErkLrdIL+fzqiOicwTTTBA5jVAwuTyM=,iv:p3GT5xJWEIzIkirMGqckiOKpOgfbXHU2AIe/+honizg=,tag:bnuRLbxCEaRsZHl+Em4xmQ==,type:comment]
    ENROLL_KEY: ENC[AES256_GCM,data:Hwbds7LYjcVvnhfJO+LrjCVk+ZsNPkVApA==,iv:G7aQrG2BUD939GTbQUajlbpC9CvtyE7AJUITjutYltc=,tag:dKO6knLwOG5p4P29iDSKWg==,type:str]
    #ENC[AES256_GCM,data:f4DwLRliUfpdi9jOuotjjK4nNWdFMJoDjKa+wDNBUD9CZhrgnhIYYEJkkfBKZTTFXLGD/k8ZcfsoG7+MMojz6ImXJl11xzmp6In+8VBAGCk+VWAq,iv:zWEwex+uIMHD62bWEQIO74yPwwiPeSDKE89CPvIetzI=,tag:YGpM10pCeeyUl9af9izHag==,type:comment]
    BOUNCER_KEY_traefik: ENC[AES256_GCM,data:JCL34a6zYqczgeeHRbyPdEqOePy8k5qijFyzhX4r856kFtH+ZfOHy/pGb2oiducfjDwqrUDi6oot3ueo6yOX7Q==,iv:nMRU1N/oMQ6JXjzZZ/65PAvBZJRnzl62eWicFWehuDE=,tag:9QhWQlHfRlVlHMe4agSHpw==,type:str]
    #ENC[AES256_GCM,data:0gick1mbalDKUZmDbUUlsW20BZnjV1icsIim+vFkI0XFIHp8rQAzS4AYD5jFwpigio59UKRU2RS36d5hhgmfDxRg4eDD+GEzLiVLVt//8BmW,iv:W3Fu/dxQFAx9aM6dXLZ4F/AK1L/gWQe1MdnsjseqKFI=,tag:B8/5oVUgGFGfPbrLaHV7zA==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:a/JbSZhJ/4U55a7klxz8fuwzG6e6zLk=,iv:DnEBGV566T67GrlUlNAr2laJ6Amev5EQ7x17ZL2xnDY=,tag:4EFL7zGNtEW4Rh120zI/IQ==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T08:28:50Z"
    mac: ENC[AES256_GCM,data:rhoKAJFA39TrvYuLODO0ceMIZjRqjTAGD3iiugtBa2ncrGdPEX1+YvUmmSG+8vFT8hgpXkvPyaC39wN110Dp6neduobEgHJfUmZWRhR+hxdOotaAXbkbG59N4Gdd3wd2bVxGfwfpkyvnAvNFhwD4WdlqK4g4ONSrG7j6RySpEP0=,iv:aalL3u571dylp02CpbcT5Avw0Mn9Hiezd3ccu7+hGaY=,tag:F7C69STRr38UHBfGGxlqWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
