apiVersion: v1
kind: PersistentVolume
metadata:
  name: playerr-config
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/playerr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: playerr-media
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /mnt/md0/MediaFactory/game_library
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: playerr-downloads
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /mnt/md0/MediaFactory/torrents/playerr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem