---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dispatcharr-postgres
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/dispatcharr/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: dispatcharr-redis
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/dispatcharr/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: dispatcharr-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/dispatcharr/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
