---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-postgres
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: dispatcharr-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-redis
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: dispatcharr-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-data
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: dispatcharr-data
