apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-secrets
    namespace: multimedia-factory
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:jvZtpz4Ud11/DoM=,iv:XiUwoUAD/t6zR8fAHg+XfbBvcKD7ehZwuRUYkieOU5s=,tag:4fQnU1LC0vK5sfbHvLg5dA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:i35sv/YFjxVzi9E=,iv:Rlyz/3R2eKMqA6yMYyE//r0I6HqQ4PzmDtuNvCCgpCg=,tag:RNGEmPfEXoYTquPCxbYErw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cfI0EcTDpY/02dEkHOI+pA==,iv:4MgAimEZRi3G+9eALhd9L2Wdv4ftckn/5JAgeASvabs=,tag:dpckBOoScTzn7F13qIF3+Q==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:hvR5xEopT2pagx1Zduq4/xHl37k5HVsM0EJfo80TCO0jaxXbr2E=,iv:tCINct4IkUFOEtL6IoNbkf5QzH7Yib1eblJg3OOilBY=,tag:eyae2pvgi7KR3YENYB4tEA==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:gghG9A==,iv:MIk3VcLz8ZodCSEMlDbtDBw+t1VMvx7G/ZXuxqK9NL8=,tag:xxHVYAdW73kghE0d10AgSw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:276jUfPz6RLLFU+izZD9yMhrY+9LkkSnxAX6LtHy/W7gfwohyACB4cDP/yQ7awbSb+fZ/kOSWEbiFZFk+yuw8f+QpbTdG9NZuwPrZMs=,iv:4zwvR/KCRJL5Z5odcMt0/djmQnJFH8VdFC6zMKuAe2I=,tag:df1QNST7GuO03KjU0qmoCA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:tTkfIQ==,iv:6vH9Cm5+Fsjh+IvW7HNX9IBFkqau1CztkPSKEfCaVF8=,tag:i7q2XL9ukPcKT9qe0ujD9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T11:17:50Z"
    mac: ENC[AES256_GCM,data:aOjzLJ2rV/Xnb1y/cymVgyfiu5F3ymlY62+mrjf6NGboBKV2uNY/26ztJf6t/otez/LapSLd16IDquFVeToPoQGnY/cxn6V7Jbznvqh7ptYlv0Eog2pzkavRWoit3XzQ/o5wZoZOywd0LB3POQV3exnqNuwDX4+vTJ89CSnsSyk=,iv:Wqxmx1c3kMZY/uHKVDp2AYgrPAIlUT/8zdwRnIosFhc=,tag:yyGkCP1Rp82vIKJITygRhA==,type:str]
    version: 3.13.3
