apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-secrets
    namespace: multimedia-factory
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:jvZtpz4Ud11/DoM=,iv:XiUwoUAD/t6zR8fAHg+XfbBvcKD7ehZwuRUYkieOU5s=,tag:4fQnU1LC0vK5sfbHvLg5dA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:rLAEHiRczjw=,iv:Qe9UCGDutHoUwvSgjEpeabd+BDkirattIWgL24JtqPI=,tag:XpHnas6uKt0s0f1m5Jq7UQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cfI0EcTDpY/02dEkHOI+pA==,iv:4MgAimEZRi3G+9eALhd9L2Wdv4ftckn/5JAgeASvabs=,tag:dpckBOoScTzn7F13qIF3+Q==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T09:14:02Z"
    mac: ENC[AES256_GCM,data:Qri4QeeGE31L3iDlheyfXHjwFg+shPip/A4JvThyWIwZsQv65TlpqbDaJ7N12CjmGzbTjLreqhfUdzPgIBlFuVYtjHHOvXXi38GYXpEpLLMPA02vOmuijKfvZUlNpYq6+FS2GIBA9kG9op0GgMEAKH53ZWjd8Sc5OOrINIdc62I=,iv:U5sXEXrhNqRCADE3eW8ZJCplZ3HQySbpuY6UGjEw4Vg=,tag:pOyRxt05N2bKYWIXXDbkng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
