apiVersion: v1
kind: Secret
metadata:
    name: trackerdex-secret
    namespace: extra-tools
type: Opaque
stringData:
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:urqOxO0swO2ougwOH2pVcY+1i2k=,iv:QwjWdIysGMxPULy1i6nKBu80XGZL2Dq0IcHhEIXgspY=,tag:QsnJ8QQ0XEry3XbJp7m7uw==,type:str]
    PIHOLE_UPSTREAM: ENC[AES256_GCM,data:BEIf63b2p117qfS/q/WaoXrtjZfRt2k+Tck9pue5Nxt+IHLC,iv:iAg6JmZmG+/1WGekosphF60oGcXXN7UV5S/A3Ty2IBU=,tag:KFVW+2cofLIM4V+WsvPR6Q==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGM2ZG9COUlhU3N6aGI0
            YmRxSVBXNXpNRXQyOUlhSGxkd244ejJjK0E0CkppS2VoNkYzSlQwL0k5NnRUWnJL
            M3pwUDZuaVJ5aXdvYlczZDFzcW0vTDgKLS0tIGV0Y2d1WFY2MnlYNTIvU3ROKzhB
            RFpvdWJuekVOQ2kyQUwzajF0clUzMzAKhqyD/RahfqKfI+iq3MsVLhWAGWqDaHbk
            CTpQ//ONxY1DYUmGx09XtKDZYLg40O2xCHqkgkGrB6OCJb9/vrBgiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T13:57:59Z"
    mac: ENC[AES256_GCM,data:qLQbRDXqv2IGKDgdEVcDhstHbpzZ6tfnjMH7DHTNNjrFuwTCy38HGKBZTZEKE3mPejhL6uYWWSLTBxGpNaHFqNQKme9YlBc/R7f7iUG8mfwC2A/r0EwzpY7S8RYGA6uPOGfWF6WfiFEMbcALD9CGlVKGwj//ni7ouRtp3dnrXtw=,iv:8hwK3p5MaLRFKrWBbSnsqYkkd0sleOuE+LJNrWJyGko=,tag:ZyvESaBVauSxaOtdOb/hFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
