apiVersion: v1
kind: Secret
metadata:
    name: trackerdex-secret
    namespace: extra-tools
type: Opaque
stringData:
    trackerdex.env: ENC[AES256_GCM,data:J9d90EPon0fs0uR3CPh0RroN4AvMGqHwRH9ftjib8Gc9ElcFisEDp1xFWS8RsjtceWkwN4pr7x4hGpygSPurMjbxVsAEsI8=,iv:BEOzI4rDjX8gvt7IG8WxJSsT4/DxCY4YJDrdicECy80=,tag:yTwcFqMopAano+KH3L3c8g==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGM2ZG9COUlhU3N6aGI0
            YmRxSVBXNXpNRXQyOUlhSGxkd244ejJjK0E0CkppS2VoNkYzSlQwL0k5NnRUWnJL
            M3pwUDZuaVJ5aXdvYlczZDFzcW0vTDgKLS0tIGV0Y2d1WFY2MnlYNTIvU3ROKzhB
            RFpvdWJuekVOQ2kyQUwzajF0clUzMzAKhqyD/RahfqKfI+iq3MsVLhWAGWqDaHbk
            CTpQ//ONxY1DYUmGx09XtKDZYLg40O2xCHqkgkGrB6OCJb9/vrBgiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T14:12:54Z"
    mac: ENC[AES256_GCM,data:D/JcsXcm7WKS4dHNqu1C0Ga/lGulFF/elVNk9r7AkHf8YcX3nPllkxrhgKmJkVsbF3+x6XCf3I2y91pzh+xtpqjeANKOMnR9Y3pdKcCnCnJOiz/+TRtvOfd66XCVwLdBMNxcUFm0HnGJNbCRzOK2g3f/sNQtzgtdlPsoF054A7s=,iv:sRY9kD7E+FSfLMgzfuoEorF6rsuOYyfYIB8GmBZXO6k=,tag:JTVLe1rS/OF7H8zvhCmdzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
