apiVersion: v1
kind: Secret
metadata:
    name: trackerdex-secret
    namespace: extra-tools
type: Opaque
stringData:
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:urqOxO0swO2ougwOH2pVcY+1i2k=,iv:QwjWdIysGMxPULy1i6nKBu80XGZL2Dq0IcHhEIXgspY=,tag:QsnJ8QQ0XEry3XbJp7m7uw==,type:str]
    PIHOLE_UPSTREAM: ENC[AES256_GCM,data:C5XVc76Ug77gZo6PltZBH78=,iv:B9apzUL2elmFIuHtOS3Bu5gvBAHTLm/oE/3wwc5AAX8=,tag:UEt7X7U4GWmTHdV7KOZEVw==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGM2ZG9COUlhU3N6aGI0
            YmRxSVBXNXpNRXQyOUlhSGxkd244ejJjK0E0CkppS2VoNkYzSlQwL0k5NnRUWnJL
            M3pwUDZuaVJ5aXdvYlczZDFzcW0vTDgKLS0tIGV0Y2d1WFY2MnlYNTIvU3ROKzhB
            RFpvdWJuekVOQ2kyQUwzajF0clUzMzAKhqyD/RahfqKfI+iq3MsVLhWAGWqDaHbk
            CTpQ//ONxY1DYUmGx09XtKDZYLg40O2xCHqkgkGrB6OCJb9/vrBgiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T14:03:22Z"
    mac: ENC[AES256_GCM,data:6h+05U90XbQonOpZK60qnX3xRYWmztxiwbAXKP08eXoRNyfsYnMSEOWRjBYEerZc41RMZ9jTHCjsqf+vETDvSdiIS3nhZLutaFYMfiy/JDTiGoEH1rp7HI/5T1H+roo4PUhaQKu34OXdTQATLHvvDX2bPIqcmEB0WVqzXYhwa+c=,iv:tu3pgvP18cVz048Hpl1Ee10C3YMF8dgVKpWYLHZsxHM=,tag:qtIvK5OENZmbmVREiTFcYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
