apiVersion: v1
kind: Service
metadata:
  name: trackerdex
  namespace: extra-tools
spec:
  selector:
    app: trackerdex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: extra-tools
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
