apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 1
  inheritedMetadata:
    annotations:
      uptime-kuma.io/enabled: "true"
      uptime-kuma.io/type: "port"
      uptime-kuma.io/url: "postgres-r.database.svc"
      uptime-kuma.io/port: "5432"
      uptime-kuma.io/name: "postgres-database"
      uptime-kuma.io/interval: "60"
      uptime-kuma.io/retries: "3"
      uptime-kuma.io/notifications: "Monitoring Bot"
      uptime-kuma.io/group: "Storage & Databases"

  storage:
    storageClass: local-path
    size: 50Gi

  managed:
    roles:
      - name: sparkyfitness
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: sparkyfitness-db-credentials
      - name: dispatcharr
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: dispatcharr-db-credentials
      - name: speedtesttracker
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: speedtesttracker-db-credentials
      - name: yamtrack
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: yamtrack-db-credentials
      - name: tranga
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: tranga-db-credentials
      - name: crowdsec
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: crowdsec-db-credentials
