apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sparkyfitness
  namespace: database
spec:
  name: sparkyfitness
  owner: sparkyfitness
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: dispatcharr
  namespace: database
spec:
  name: dispatcharr
  owner: dispatcharr
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: speedtesttracker
  namespace: database
spec:
  name: speedtesttracker
  owner: speedtesttracker
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: floppy
  namespace: database
spec:
  name: floppy
  owner: floppy
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: tranga
  namespace: database
spec:
  name: tranga
  owner: tranga
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: crowdsec
  namespace: database
spec:
  name: crowdsec
  owner: crowdsec
  cluster:
    name: postgres
