apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8crrIA1I9X2g2Xa0mA==,iv:xoguJKGwsPL/8Drm3/c42NAsrY1DcZ9NuOoHN1jIfbQ=,tag:UtOGc4K6zichaEGgl2HUXQ==,type:str]
    password: ENC[AES256_GCM,data:QIzoh/UVgUWHOvR5iods05kCh/C6AHV2u4m5vMe5UFOVwA==,iv:xePJWagqHK66B76bLkSFPEtweEhSD6WU3a90tV/MpPw=,tag:3QEYU8cI74BtKPBN20AtqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUVtRy9FUndZYW5OZEJ2
            bkEyblRHNlljUjR0djFUZWF1bzl0bGpDWVFrClNIQ1N4RU9DTUx6YUtrWEduMnBQ
            NC9wYUx4OFRkUWpxd2NKMmNycGRYVVEKLS0tIEwzWjdPZ2RjaUFJeFBhMCs1V3hl
            Q1luOWJJMVJYNmplZUQrdjBJS2orQVEKuGTb09vgBgNNXp4NjD9OJ6bC+Wg3C4cL
            j5L4uO6wZTwrZOE0PvDG0SJQhOE2C20kYU624OzNsHQBiXKSsBmN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T14:31:20Z"
    mac: ENC[AES256_GCM,data:uI5/UAaRKAlmeM1U0FAxkHL0WRV4PA+V2M/ZwMnHdyHGpB7LUzTT+BnMyi9ILBe0y7tCuXZJx3H0iRPBi2RnjKkkL7NfZxz8ML6rv/KqJMLV84GHq69SFxi02IJvahVBDrAlqohY6OVVk8bmjZneCA6Wi22h8TW+D7Dn1GAvIiY=,iv:yNFFegRILgZjzGz1d5Nk/PX/qot5oLrQLMOj6VqXvM4=,tag:dOEnLqCMc/8f67lUox0t6g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IrnVA7ySvueRP7U=,iv:FoEtrjfrAmNcGEUktrZlAiDwefiQAiKAttH2w0avpp8=,tag:jZFdKP3bGQfDJhrUICUgjA==,type:str]
    password: ENC[AES256_GCM,data:t/BFRI2C9TGEIZbueOnGwQ==,iv:wUVT8kwwQyzRnsvXRkFlcmYAupcdIyA1dAQW3+9+FUo=,tag:29Oz3k4c6aJm6LlZp9uLYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUVtRy9FUndZYW5OZEJ2
            bkEyblRHNlljUjR0djFUZWF1bzl0bGpDWVFrClNIQ1N4RU9DTUx6YUtrWEduMnBQ
            NC9wYUx4OFRkUWpxd2NKMmNycGRYVVEKLS0tIEwzWjdPZ2RjaUFJeFBhMCs1V3hl
            Q1luOWJJMVJYNmplZUQrdjBJS2orQVEKuGTb09vgBgNNXp4NjD9OJ6bC+Wg3C4cL
            j5L4uO6wZTwrZOE0PvDG0SJQhOE2C20kYU624OzNsHQBiXKSsBmN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T14:31:20Z"
    mac: ENC[AES256_GCM,data:uI5/UAaRKAlmeM1U0FAxkHL0WRV4PA+V2M/ZwMnHdyHGpB7LUzTT+BnMyi9ILBe0y7tCuXZJx3H0iRPBi2RnjKkkL7NfZxz8ML6rv/KqJMLV84GHq69SFxi02IJvahVBDrAlqohY6OVVk8bmjZneCA6Wi22h8TW+D7Dn1GAvIiY=,iv:yNFFegRILgZjzGz1d5Nk/PX/qot5oLrQLMOj6VqXvM4=,tag:dOEnLqCMc/8f67lUox0t6g==,type:str]
    version: 3.13.3
