apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8crrIA1I9X2g2Xa0mA==,iv:xoguJKGwsPL/8Drm3/c42NAsrY1DcZ9NuOoHN1jIfbQ=,tag:UtOGc4K6zichaEGgl2HUXQ==,type:str]
    password: ENC[AES256_GCM,data:QIzoh/UVgUWHOvR5iods05kCh/C6AHV2u4m5vMe5UFOVwA==,iv:xePJWagqHK66B76bLkSFPEtweEhSD6WU3a90tV/MpPw=,tag:3QEYU8cI74BtKPBN20AtqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUVtRy9FUndZYW5OZEJ2
            bkEyblRHNlljUjR0djFUZWF1bzl0bGpDWVFrClNIQ1N4RU9DTUx6YUtrWEduMnBQ
            NC9wYUx4OFRkUWpxd2NKMmNycGRYVVEKLS0tIEwzWjdPZ2RjaUFJeFBhMCs1V3hl
            Q1luOWJJMVJYNmplZUQrdjBJS2orQVEKuGTb09vgBgNNXp4NjD9OJ6bC+Wg3C4cL
            j5L4uO6wZTwrZOE0PvDG0SJQhOE2C20kYU624OzNsHQBiXKSsBmN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T15:28:31Z"
    mac: ENC[AES256_GCM,data:eMcnRBghHhkT4NaeG/nR1O179WUd922bNLEs2hDOWBYPejsU4bO8JWt8+9Fh7Y3AYfRqLhHqkfR+VRv2XtgrpOh9CHaw59yRfO4WO7wzj02dwTWZd7Oz5fDcwFgRWTl/mpmcCwwYOwULnqUg9Do/J853+cBWEGJiuXYA2qlzYFg=,iv:KRXd3nujJwDiHlIEqwAGpAMnFQj44D9Ug1Wg9LPdFTw=,tag:NnIo5RX3dJDCbGDAV57TMg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IrnVA7ySvueRP7U=,iv:FoEtrjfrAmNcGEUktrZlAiDwefiQAiKAttH2w0avpp8=,tag:jZFdKP3bGQfDJhrUICUgjA==,type:str]
    password: ENC[AES256_GCM,data:t/BFRI2C9TGEIZbueOnGwQ==,iv:wUVT8kwwQyzRnsvXRkFlcmYAupcdIyA1dAQW3+9+FUo=,tag:29Oz3k4c6aJm6LlZp9uLYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUVtRy9FUndZYW5OZEJ2
            bkEyblRHNlljUjR0djFUZWF1bzl0bGpDWVFrClNIQ1N4RU9DTUx6YUtrWEduMnBQ
            NC9wYUx4OFRkUWpxd2NKMmNycGRYVVEKLS0tIEwzWjdPZ2RjaUFJeFBhMCs1V3hl
            Q1luOWJJMVJYNmplZUQrdjBJS2orQVEKuGTb09vgBgNNXp4NjD9OJ6bC+Wg3C4cL
            j5L4uO6wZTwrZOE0PvDG0SJQhOE2C20kYU624OzNsHQBiXKSsBmN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T15:28:31Z"
    mac: ENC[AES256_GCM,data:eMcnRBghHhkT4NaeG/nR1O179WUd922bNLEs2hDOWBYPejsU4bO8JWt8+9Fh7Y3AYfRqLhHqkfR+VRv2XtgrpOh9CHaw59yRfO4WO7wzj02dwTWZd7Oz5fDcwFgRWTl/mpmcCwwYOwULnqUg9Do/J853+cBWEGJiuXYA2qlzYFg=,iv:KRXd3nujJwDiHlIEqwAGpAMnFQj44D9Ug1Wg9LPdFTw=,tag:NnIo5RX3dJDCbGDAV57TMg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: speedtesttracker-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xFqXcC8Fr29EzpHXu5SpCA==,iv:sOI55REcvzx8bRWh9UnGwymlyATABFCqPx/rtuBSBrI=,tag:pjyqLSRjAj6Z/J7W+5sSyQ==,type:str]
    password: ENC[AES256_GCM,data:SJVWxDWMqIuC5BpCpg==,iv:UKkgMXvrp4gIDcGWpVwhN2xnEIyk7X9DxF2aefUxrPM=,tag:zCsuv2KuGqO5XQ0PxBB/Zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUVtRy9FUndZYW5OZEJ2
            bkEyblRHNlljUjR0djFUZWF1bzl0bGpDWVFrClNIQ1N4RU9DTUx6YUtrWEduMnBQ
            NC9wYUx4OFRkUWpxd2NKMmNycGRYVVEKLS0tIEwzWjdPZ2RjaUFJeFBhMCs1V3hl
            Q1luOWJJMVJYNmplZUQrdjBJS2orQVEKuGTb09vgBgNNXp4NjD9OJ6bC+Wg3C4cL
            j5L4uO6wZTwrZOE0PvDG0SJQhOE2C20kYU624OzNsHQBiXKSsBmN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T15:28:31Z"
    mac: ENC[AES256_GCM,data:eMcnRBghHhkT4NaeG/nR1O179WUd922bNLEs2hDOWBYPejsU4bO8JWt8+9Fh7Y3AYfRqLhHqkfR+VRv2XtgrpOh9CHaw59yRfO4WO7wzj02dwTWZd7Oz5fDcwFgRWTl/mpmcCwwYOwULnqUg9Do/J853+cBWEGJiuXYA2qlzYFg=,iv:KRXd3nujJwDiHlIEqwAGpAMnFQj44D9Ug1Wg9LPdFTw=,tag:NnIo5RX3dJDCbGDAV57TMg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: yamtrack-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Ie6huwOnVc8=,iv:llJMzyACveJcF/wLnoGW0wjm3juRGjFlBzpyRBClo8g=,tag:I4xXDzYRtorlWw0Lf+dRYg==,type:str]
    password: ENC[AES256_GCM,data:xGhiu87oZdT31idLBoTapTVE+qY=,iv:/rm3ZqjkGuudhmt7z/OqsCKoVIj9ItRQdEnT6w1iR6U=,tag:4YpHuSpc5n26rT/zgIW/WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUVtRy9FUndZYW5OZEJ2
            bkEyblRHNlljUjR0djFUZWF1bzl0bGpDWVFrClNIQ1N4RU9DTUx6YUtrWEduMnBQ
            NC9wYUx4OFRkUWpxd2NKMmNycGRYVVEKLS0tIEwzWjdPZ2RjaUFJeFBhMCs1V3hl
            Q1luOWJJMVJYNmplZUQrdjBJS2orQVEKuGTb09vgBgNNXp4NjD9OJ6bC+Wg3C4cL
            j5L4uO6wZTwrZOE0PvDG0SJQhOE2C20kYU624OzNsHQBiXKSsBmN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T15:28:31Z"
    mac: ENC[AES256_GCM,data:eMcnRBghHhkT4NaeG/nR1O179WUd922bNLEs2hDOWBYPejsU4bO8JWt8+9Fh7Y3AYfRqLhHqkfR+VRv2XtgrpOh9CHaw59yRfO4WO7wzj02dwTWZd7Oz5fDcwFgRWTl/mpmcCwwYOwULnqUg9Do/J853+cBWEGJiuXYA2qlzYFg=,iv:KRXd3nujJwDiHlIEqwAGpAMnFQj44D9Ug1Wg9LPdFTw=,tag:NnIo5RX3dJDCbGDAV57TMg==,type:str]
    version: 3.13.3
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdUVtRy9FUndZYW5OZEJ2
            bkEyblRHNlljUjR0djFUZWF1bzl0bGpDWVFrClNIQ1N4RU9DTUx6YUtrWEduMnBQ
            NC9wYUx4OFRkUWpxd2NKMmNycGRYVVEKLS0tIEwzWjdPZ2RjaUFJeFBhMCs1V3hl
            Q1luOWJJMVJYNmplZUQrdjBJS2orQVEKuGTb09vgBgNNXp4NjD9OJ6bC+Wg3C4cL
            j5L4uO6wZTwrZOE0PvDG0SJQhOE2C20kYU624OzNsHQBiXKSsBmN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T15:28:31Z"
    mac: ENC[AES256_GCM,data:eMcnRBghHhkT4NaeG/nR1O179WUd922bNLEs2hDOWBYPejsU4bO8JWt8+9Fh7Y3AYfRqLhHqkfR+VRv2XtgrpOh9CHaw59yRfO4WO7wzj02dwTWZd7Oz5fDcwFgRWTl/mpmcCwwYOwULnqUg9Do/J853+cBWEGJiuXYA2qlzYFg=,iv:KRXd3nujJwDiHlIEqwAGpAMnFQj44D9Ug1Wg9LPdFTw=,tag:NnIo5RX3dJDCbGDAV57TMg==,type:str]
    version: 3.13.3
