apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:wd17wPLZSU1olT/s7A==,iv:IdsGhY0UXXvWaevXmFHwfQsOzsZT72ngbCt4S+tejq0=,tag:iiwaIF6EQsc8bl8zmeMPAA==,type:str]
    password: ENC[AES256_GCM,data:2qV7SjoopemGd7wlBOOIXtHYyZ2aPVFeWrU3Ds3mLasrBA==,iv:MDXHmP5rZ55p/7Ict4oZ2BAd4s0pt3hZEKQRpgpOWcA=,tag:PROFTsF0ROSCpP3IM1us0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFRxdHh4c0NwbU96WFE5
            Wjg3SkdnU1BqelR1MldhejJKeVJKYVEzalZnCkVQbzdQMkRGWFdwVHRxeTVoRWVG
            ek9EMDFhTVpTOHVlaVU4eXlLakRDUEkKLS0tIHY0elNaMWtvSUpuTUZTM1FMdFMz
            MWgyektQMDFkSWJkV2hXUWg1bmYvYWMK4MfVArOYaFFDp1weduKlK5GFFReDcaqz
            4XCWeVwTUcLgIQPGieQDnCDdHwjrDOAKQE/Mm6cxCeDWItFL1uR5mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:11:17Z"
    mac: ENC[AES256_GCM,data:oWZtmeUV46ZfNWKayXUNJW0bDmhAHERnPt2P9M7VB077jvDdQAvVEdY7oTbH1H3Spr1FVI7TNygzqprqqHSgl1tC2qrbKrINDE6vSs0XVoO5P0si/f+K0dRstmS2Ao4vLMtyTkjTgMRyOM0dwx8gKtSEP+cNRX9vZqITDi6JQBo=,iv:2JuLC0M4/RZTUTRu7su4Eh1uupDK9mUDLYTeOfduvAQ=,tag:QZW9LZESWDkjJxZuZGjaCQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Di0r9TthcLemUmc=,iv:MlrF2UfgioP8ku7FLw78vz9fcYZ3c9v/u1QFwQpi+68=,tag:xIvX2+EmD5Us3wmgWlYAFQ==,type:str]
    password: ENC[AES256_GCM,data:qrbT9gx5blnR2SW0SKam7w==,iv:hZd57DFVrwnq8ciSxFins+zCfPWQCdzGi9E6fQsdt3Y=,tag:7Z7b5NtNCz4i7qeaQZof7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFRxdHh4c0NwbU96WFE5
            Wjg3SkdnU1BqelR1MldhejJKeVJKYVEzalZnCkVQbzdQMkRGWFdwVHRxeTVoRWVG
            ek9EMDFhTVpTOHVlaVU4eXlLakRDUEkKLS0tIHY0elNaMWtvSUpuTUZTM1FMdFMz
            MWgyektQMDFkSWJkV2hXUWg1bmYvYWMK4MfVArOYaFFDp1weduKlK5GFFReDcaqz
            4XCWeVwTUcLgIQPGieQDnCDdHwjrDOAKQE/Mm6cxCeDWItFL1uR5mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:11:17Z"
    mac: ENC[AES256_GCM,data:oWZtmeUV46ZfNWKayXUNJW0bDmhAHERnPt2P9M7VB077jvDdQAvVEdY7oTbH1H3Spr1FVI7TNygzqprqqHSgl1tC2qrbKrINDE6vSs0XVoO5P0si/f+K0dRstmS2Ao4vLMtyTkjTgMRyOM0dwx8gKtSEP+cNRX9vZqITDi6JQBo=,iv:2JuLC0M4/RZTUTRu7su4Eh1uupDK9mUDLYTeOfduvAQ=,tag:QZW9LZESWDkjJxZuZGjaCQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: speedtesttracker-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Br6ayOU7+LgiGhRw8ycYJQ==,iv:NUBe5HFKETkesdaN6gdy79NzWbLsug5tgOh8MA7nDH8=,tag:nGevX8WMlmqvdhU4h4cL3w==,type:str]
    password: ENC[AES256_GCM,data:SRHpGNpo6HMdUmOiJA==,iv:dGxYRvZ+4if2uUwnF2tKj49ZSLUwhv82wfnH3GPuyyU=,tag:ok84nA/+Fzig552f9K5vmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFRxdHh4c0NwbU96WFE5
            Wjg3SkdnU1BqelR1MldhejJKeVJKYVEzalZnCkVQbzdQMkRGWFdwVHRxeTVoRWVG
            ek9EMDFhTVpTOHVlaVU4eXlLakRDUEkKLS0tIHY0elNaMWtvSUpuTUZTM1FMdFMz
            MWgyektQMDFkSWJkV2hXUWg1bmYvYWMK4MfVArOYaFFDp1weduKlK5GFFReDcaqz
            4XCWeVwTUcLgIQPGieQDnCDdHwjrDOAKQE/Mm6cxCeDWItFL1uR5mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:11:17Z"
    mac: ENC[AES256_GCM,data:oWZtmeUV46ZfNWKayXUNJW0bDmhAHERnPt2P9M7VB077jvDdQAvVEdY7oTbH1H3Spr1FVI7TNygzqprqqHSgl1tC2qrbKrINDE6vSs0XVoO5P0si/f+K0dRstmS2Ao4vLMtyTkjTgMRyOM0dwx8gKtSEP+cNRX9vZqITDi6JQBo=,iv:2JuLC0M4/RZTUTRu7su4Eh1uupDK9mUDLYTeOfduvAQ=,tag:QZW9LZESWDkjJxZuZGjaCQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: floppy-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:wng7kzps,iv:YEupBEU5DutD/AX9E17WQFOGKyT6UsvSDc9eIoJMgTw=,tag:TfqydgZKZAYmc1xY9G51ug==,type:str]
    password: ENC[AES256_GCM,data:90WS8D89Bl1tZ2+YKJ1gN0c0zNuEjxKCawCx0NzeN1FNuCcVL36Jv+N3OshN0g7a,iv:bYyXNokY+SD45th5FYYZmMpgFOeNMwlySaKdMfBnOII=,tag:n46Bla5ZhhMzOc08FkS7EQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFRxdHh4c0NwbU96WFE5
            Wjg3SkdnU1BqelR1MldhejJKeVJKYVEzalZnCkVQbzdQMkRGWFdwVHRxeTVoRWVG
            ek9EMDFhTVpTOHVlaVU4eXlLakRDUEkKLS0tIHY0elNaMWtvSUpuTUZTM1FMdFMz
            MWgyektQMDFkSWJkV2hXUWg1bmYvYWMK4MfVArOYaFFDp1weduKlK5GFFReDcaqz
            4XCWeVwTUcLgIQPGieQDnCDdHwjrDOAKQE/Mm6cxCeDWItFL1uR5mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:11:17Z"
    mac: ENC[AES256_GCM,data:oWZtmeUV46ZfNWKayXUNJW0bDmhAHERnPt2P9M7VB077jvDdQAvVEdY7oTbH1H3Spr1FVI7TNygzqprqqHSgl1tC2qrbKrINDE6vSs0XVoO5P0si/f+K0dRstmS2Ao4vLMtyTkjTgMRyOM0dwx8gKtSEP+cNRX9vZqITDi6JQBo=,iv:2JuLC0M4/RZTUTRu7su4Eh1uupDK9mUDLYTeOfduvAQ=,tag:QZW9LZESWDkjJxZuZGjaCQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: tranga-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dTGVSyzv,iv:wHFt/g76bXX0vpi9ONUTh+5EVJJgaBdyNoP1eUqnMsM=,tag:IkpT89aSphYB/vslGMYXlQ==,type:str]
    password: ENC[AES256_GCM,data:BfErWZpDBkSyV/365JxhqwmZOA==,iv:wR/nME/rY9lGVPFbRzIFNcBfaRKd6sIdwzAI+ofhTlo=,tag:sRHWwL0S1YKOp2P9eo9jFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFRxdHh4c0NwbU96WFE5
            Wjg3SkdnU1BqelR1MldhejJKeVJKYVEzalZnCkVQbzdQMkRGWFdwVHRxeTVoRWVG
            ek9EMDFhTVpTOHVlaVU4eXlLakRDUEkKLS0tIHY0elNaMWtvSUpuTUZTM1FMdFMz
            MWgyektQMDFkSWJkV2hXUWg1bmYvYWMK4MfVArOYaFFDp1weduKlK5GFFReDcaqz
            4XCWeVwTUcLgIQPGieQDnCDdHwjrDOAKQE/Mm6cxCeDWItFL1uR5mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:11:17Z"
    mac: ENC[AES256_GCM,data:oWZtmeUV46ZfNWKayXUNJW0bDmhAHERnPt2P9M7VB077jvDdQAvVEdY7oTbH1H3Spr1FVI7TNygzqprqqHSgl1tC2qrbKrINDE6vSs0XVoO5P0si/f+K0dRstmS2Ao4vLMtyTkjTgMRyOM0dwx8gKtSEP+cNRX9vZqITDi6JQBo=,iv:2JuLC0M4/RZTUTRu7su4Eh1uupDK9mUDLYTeOfduvAQ=,tag:QZW9LZESWDkjJxZuZGjaCQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-db-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:U3shqcMHxjQ=,iv:tzm6Ah4rzyQKdmUwzmMt7d94z/44dpN0U6GRnDC+x2s=,tag:WVOlq9YHAkbk4VjqhSxIKg==,type:str]
    password: ENC[AES256_GCM,data:CIocJUyB7I+2JDujZ9eCcW3aCoD4gjk=,iv:Y+ELcS5MPwMYdU0n5BA1qs73209TVJX+U0pC1uct2xg=,tag:3XvjuEykvaTsbgIdLrVgKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFRxdHh4c0NwbU96WFE5
            Wjg3SkdnU1BqelR1MldhejJKeVJKYVEzalZnCkVQbzdQMkRGWFdwVHRxeTVoRWVG
            ek9EMDFhTVpTOHVlaVU4eXlLakRDUEkKLS0tIHY0elNaMWtvSUpuTUZTM1FMdFMz
            MWgyektQMDFkSWJkV2hXUWg1bmYvYWMK4MfVArOYaFFDp1weduKlK5GFFReDcaqz
            4XCWeVwTUcLgIQPGieQDnCDdHwjrDOAKQE/Mm6cxCeDWItFL1uR5mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:11:17Z"
    mac: ENC[AES256_GCM,data:oWZtmeUV46ZfNWKayXUNJW0bDmhAHERnPt2P9M7VB077jvDdQAvVEdY7oTbH1H3Spr1FVI7TNygzqprqqHSgl1tC2qrbKrINDE6vSs0XVoO5P0si/f+K0dRstmS2Ao4vLMtyTkjTgMRyOM0dwx8gKtSEP+cNRX9vZqITDi6JQBo=,iv:2JuLC0M4/RZTUTRu7su4Eh1uupDK9mUDLYTeOfduvAQ=,tag:QZW9LZESWDkjJxZuZGjaCQ==,type:str]
    version: 3.13.3
