---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracearr-redis-config
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: tracearr-redis-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracearr-timescale-config
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: tracearr-timescale-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracearr-config
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: tracearr-config
