apiVersion: v1
kind: Secret
metadata:
    name: tracearr-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:UM/cUiMMn2M=,iv:FAtigowbwR80SN/z2AHP3Zys9iiox1WXov3pJcRXUas=,tag:ZY8gV9iAkuOoZBvrRbslrw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:CHnJDKJFLkBiMxWsciSqbNvHrHZBLuHIBL2yEMXYBYyB1/Ni7X2T6W8laonq1u67RmiT5FrryeB2RbpigCcmFg==,iv:ZQ5BX2sbiqq4Dem7I5jhpb2A9BV1+HulFDxQB9vJsCo=,tag:1AzmVOkq5F6DS9sCEOYFHw==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:UkIg2eGvFMrwj+6P/b+yq13mhzKemcNA16qAPzDRl1vtACc6lgNnPMvKaO/ThtmVyUMu84e8Dc/B3crswPe3/g==,iv:bXzwJ2+ay56ebq2zl99hyHhxadze/YCD7/tibP60f38=,tag:IUTSVTlFted03fhnk46rQw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:/FG/wJFDOmVVbS+pON990SJeeO5dpX7x1/us8YzMw3U+tV3h7IXDmgoLh0I62H5mg1CD2LQ5FGkq03Kna39bjKodDhkr9jjMZhiD8HOZbN3xdPmz+ONByWuEfkgg2p9uOHE=,iv:ZMMvUZGhtR4E9dcXqD2xc1sJtpOWu7x/7CNHKHl4XSI=,tag:YYVzq8KqSwHHj1Vhl/YjcQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:SUVVGe5naDmSecH+GJJjsNMS+sngS0UYx7qHxF7HiE8qdsP+x7k+jtOlseYuJe3At/kUOUNsaYj8zYm3QRn9ojJUaPwm/XxhZUOQccM=,iv:pdz6FnpjJr8UUNO4l/X3qL+YHiMsgqbifhgSYB8aQ4Y=,tag:iEH+v55ttomXxFSj3vsovA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T12:07:23Z"
    mac: ENC[AES256_GCM,data:ldRnKgkRi5uvfIL4hnfViHQ3heN54/oE2sutz1P2QchBOl58uAFoE9nRJdiv9zTDj+v8FmgmOG6m0W7IZ24M4nEK7mSk4ct7X1k8l+AecKhYLPdsxK7xijk1q7bq9xfX9BqNJwb3muEc2drdsgbRcVR6SkYt1Ek2s+kE50NnwiM=,iv:WavV3IfJCYHqh6TBfvk6VV2qnrNXuyHxf6lGW8261as=,tag:Tw1D7D4Rh+1Tg3qC3No/UA==,type:str]
    version: 3.13.3
