apiVersion: v1
kind: Secret
metadata:
    name: tracearr-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:4UWEw5y3sBQ=,iv:YPJkbZ3R8QOwDnfe9CLRhrUsEh+268zOk3RizYiR+Jg=,tag:dOdzmzBmVsoUE+onY5Izjw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:8IZZs2TlGyfS8Epf0XgjHezxSGgpQspamjzdkJsLfnjg+7/MMPkSlJSOkAjT+lsq8PH+TQMScG7wMEC+j3YZwg==,iv:qdJozC1/jDtGaVddCmmHB7VUqqnN7Xu67Csmz3DR9bw=,tag:DQVihiMypf4y9/9jzSENjg==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:HSIe//ODY9LTeWTGctR0ZqX/UNFT/LaQROe0/VG5/XMHA/Lp4yKy/ogoyKJBZ2rB/aQIEDbqwrigQvy8wQcsmw==,iv:eNxqK9sHabdNgkbRiP5EEDLyN3/4/4Tgfqd6tvwTLeY=,tag:cDpSdl1cq85x0bKMDc0/jQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:z+ZfCPXGo2F0ZwqJqv3n9akrwkHS0guExODA6Or3RiIuHnwDyhxbnTt8+lYnTkrsSsbfKJxNIZ0xDLegkQMGWjk4PhG04Ltebb49IpANMHJp/McBtR6wXGT9LKaTpooWtEk=,iv:Mw8kA6e0oWE5IIn29NxwgurjzcCqTePasHQZ0XEYObQ=,tag:bnVcLaFuwOsfhYHa8aPGbA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXQyZjhIdHBYdkZveENt
            Sm1DUWZROEdIZXloRkRQS2pFaVZaTU5uVW1vCkVRek11dThDeWUxd2RjYlRVcm5E
            TXErV2FiVnlKUXNlQ0NIUld4SDhSazgKLS0tIFBuZC9JR1JHZldmMjdPMEFDVFBn
            Mis0R2ZCamdFZzBsaXJpSkpLdEN4UDAKtW2VF4z2EuVVLDuXfxQmpv3wmyDk0CcU
            wVefXh2ohaXfaACMNWDpyTJ0B337XiKOoO7Udgwtj6EYUpDqgWknog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T09:42:52Z"
    mac: ENC[AES256_GCM,data:bpzgHKlIhMkQWWAiLY++iTAfFnNGkEJzguz+8O3G5Xl3G5hXuUHJHzr/XRt4dU132vn3zBxogeri9zsL/vz6Qg7NbdmN8tTGuafg8U2+GAGXrLWCQCLYtu/ZR9PdXBR+SzBqNBiigiaaES1PXpTbrI1Uk644zCjyulkV//Gg5hs=,iv:Vaz3f3l7wZPi6F80AdPnjAS4NP1GUZXKeJ731l7vD98=,tag:4sABLLgBGcRd40xiXpEtgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
