apiVersion: v1
kind: Secret
metadata:
    name: tracearr-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ankzdkTuvr9tXOJKf3I=,iv:1sth4NYnXNZdhq6fpKOnJ6Lh5uXYsGeRNdezyhKmMb0=,tag:HatogKLtE5v+0RWQH8kgrg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:8IZZs2TlGyfS8Epf0XgjHezxSGgpQspamjzdkJsLfnjg+7/MMPkSlJSOkAjT+lsq8PH+TQMScG7wMEC+j3YZwg==,iv:qdJozC1/jDtGaVddCmmHB7VUqqnN7Xu67Csmz3DR9bw=,tag:DQVihiMypf4y9/9jzSENjg==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:HSIe//ODY9LTeWTGctR0ZqX/UNFT/LaQROe0/VG5/XMHA/Lp4yKy/ogoyKJBZ2rB/aQIEDbqwrigQvy8wQcsmw==,iv:eNxqK9sHabdNgkbRiP5EEDLyN3/4/4Tgfqd6tvwTLeY=,tag:cDpSdl1cq85x0bKMDc0/jQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:8ZQWsOLDF5DEDdtdafrC5uJGhUYbOWWSZeO1vYb9kovS6VhP20x+3oD4HtwSeRz1t/ego5BCat79zi2oQdE9vNwvoKaMXij/ldB+J0SR+9fjK3TrqyjHTf7o4jkMcmFVdPd1bnthYcI=,iv:bPdNYZe8bWKfahbiBASlR0Q6q8uTkKEdakI/0ep8Yjs=,tag:glOScI+FGmYMFGlZiBbuJA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXQyZjhIdHBYdkZveENt
            Sm1DUWZROEdIZXloRkRQS2pFaVZaTU5uVW1vCkVRek11dThDeWUxd2RjYlRVcm5E
            TXErV2FiVnlKUXNlQ0NIUld4SDhSazgKLS0tIFBuZC9JR1JHZldmMjdPMEFDVFBn
            Mis0R2ZCamdFZzBsaXJpSkpLdEN4UDAKtW2VF4z2EuVVLDuXfxQmpv3wmyDk0CcU
            wVefXh2ohaXfaACMNWDpyTJ0B337XiKOoO7Udgwtj6EYUpDqgWknog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T09:10:11Z"
    mac: ENC[AES256_GCM,data:Hjuc7sfzctcPxxdBY4Gg4lyHf1295rmGqYtQ6TiwLi/nK99zh8yTqY14q2ddFn61+shXpj8ctdw+7Xu+wmxkjGIEDRomdXc1c8pqmqm/rwfPJp8Z1OycbFhu81A4OOP5f5JUJbZNzCfCCh7X1aWAyX11zNDw5BAieQMwFTiyVw0=,iv:zfiGihRfSUC2isd54o3ygDNDe7/vjqSCtefINWyEhS8=,tag:id1zqCN/l0r14d1M0EuLng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
