apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-postgres-secret
    namespace: system-addon
    labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: crowdsec-postgres
        app.kubernetes.io/component: database
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:zbqvuXTD9y4=,iv:E0trzhz6Yo7bUqcsDhINoNj0ep04PX0EtHQejDo043s=,tag:PMOFRpLKZFS9vvofEg658Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a4LTBm6YfnzkMmSzgELUZLx4ilY+f0w=,iv:ozKNZ0oDYl/tWGd9F3vyG5LAxG/ZznK+8kzeTtdMipU=,tag:0YB0PjXGXZUrlixO12h6Mg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:nawuUZcrSSg=,iv:PWyFp0MnXIoeQXQ4v4JqXz41FexArIglORsbEwV+YIc=,tag:pGo39MqmlNzbIXHE3DXnuQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:8UeiTugQQqg7l3ZZklT9KPN7NKGoznYdoA9LJoYylrXaaEB+fFwRGrEcj5HZHXcewGKrRc5xs43ufWdReh6qxm2VEo9I04PSh2y0AA5bmVqbEJTuIk01UTzlaVcu+A+sqQI=,iv:Qjooo+Rwxzsdh86SKqw802qkab2s8EjI2V2EDjLBbQY=,tag:4fj90FheBPEIm158G3EFPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T09:09:37Z"
    mac: ENC[AES256_GCM,data:vYl5dDDE1iMJgZJVr/uaNmkH9M3WBSI8gyDENhAcGa2OWlHduymF9wzFgCfV+MSQEmKYGvgWPdZZEZEuexYXlrbh4hfzbyFqZoG+7IVqskuFzUPT708BYCtQe/foJZDDWEIB2WKM3pXD2MbzaaXEDAPNlEi2LCbt/sE7Lh/356U=,iv:+C42/w9AB3nM299uAx5V5+grXkXplOEl6i3DMkX+YKg=,tag:fZv4CWvZj42pnBjNdOc+jQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-keys
    namespace: system-addon
    labels:
        app.kubernetes.io/name: crowdsec
        app.kubernetes.io/managed-by: flux
type: Opaque
stringData:
    ENROLL_KEY: ENC[AES256_GCM,data:Hwbds7LYjcVvnhfJO+LrjCVk+ZsNPkVApA==,iv:G7aQrG2BUD939GTbQUajlbpC9CvtyE7AJUITjutYltc=,tag:dKO6knLwOG5p4P29iDSKWg==,type:str]
    BOUNCER_KEY_traefik: ENC[AES256_GCM,data:JCL34a6zYqczgeeHRbyPdEqOePy8k5qijFyzhX4r856kFtH+ZfOHy/pGb2oiducfjDwqrUDi6oot3ueo6yOX7Q==,iv:nMRU1N/oMQ6JXjzZZ/65PAvBZJRnzl62eWicFWehuDE=,tag:9QhWQlHfRlVlHMe4agSHpw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:a/JbSZhJ/4U55a7klxz8fuwzG6e6zLk=,iv:DnEBGV566T67GrlUlNAr2laJ6Amev5EQ7x17ZL2xnDY=,tag:4EFL7zGNtEW4Rh120zI/IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RlhlcTYzMXJKUndNVmV2
            TWlmZGpmd1VMbklySWo2QjlPNnJIUzlLa1JVClBMb3ZaOTdrYnFvN2NLS1dTUFdX
            em56UkREMnYraEtmRHZIbjl2OXRwTVUKLS0tIFJMTDhTQm1UcTNhbjFvRnI2OWJF
            MWpkQnBRNjUxb0xNOE5yZnlMZkpxN00Kc8wKCu20SSxf4vy9gRV33LQQCGWndkXG
            MWBTQQiQySVsgpJeUnpS+DvwjUwqaT/ZXsV3LP612/3E02HBA6UORA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T09:09:37Z"
    mac: ENC[AES256_GCM,data:vYl5dDDE1iMJgZJVr/uaNmkH9M3WBSI8gyDENhAcGa2OWlHduymF9wzFgCfV+MSQEmKYGvgWPdZZEZEuexYXlrbh4hfzbyFqZoG+7IVqskuFzUPT708BYCtQe/foJZDDWEIB2WKM3pXD2MbzaaXEDAPNlEi2LCbt/sE7Lh/356U=,iv:+C42/w9AB3nM299uAx5V5+grXkXplOEl6i3DMkX+YKg=,tag:fZv4CWvZj42pnBjNdOc+jQ==,type:str]
    version: 3.13.3
