apiVersion: v1
kind: Secret
metadata:
    name: nutify-secret
    namespace: extra-tools
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:lvXiFTwHtrzznrqiFseR,iv:LWFyjUWzm1B4EqyT3yHFKGjvBTqDRiPBcVqWwnX5DaQ=,tag:X82Pr0if9ml/EwS1diK7hA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZkdnUnpPTXdyamZrYkFm
            NDhGOFFRVEtpdy94MkNuTHpWRGZDckhjUFVnClpITFI1ZGRBNkRQRjJ6eXVrQXUy
            U1RsZnFyYXk0KzFtcUJvTEhMNW1XZHMKLS0tIGRERkRQaVBlQkkxV3ZxeFNlR0hi
            NGN2Y0R0ZTJ5NjZVMmJkWmtyT1N4RWsK0LBx4QWxa/UxThI/3703Un6aYh8gRyk6
            +9OxbtOHPuYGAxxDgNwMTVmu81S0hB0lX8nMu2LR0srlzuDaOi5fcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T20:26:49Z"
    mac: ENC[AES256_GCM,data:xbaaQmxs5V4hi8z/2PwhrHzC6uBahJMG/s8FDZZ+NJRSbu3pd9d0XyKQVPGhL//gMHdj7Cq44Iq5m3UytH4WxDv7eWU+14e/Oa8Pk9mdqkb4+TfVv7eTwdJkNHts7ybEpmnmFr8ZOhXB89repiyC1MbPmz7oLfQ4v10eTgLiKU8=,iv:ckNDj5i/TxSzak+OZuJ/x1/CkmvLwIrAY3X7HcG472k=,tag:PpPOos6gXqHDVmJC9r4WNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
