apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-mariadb-config
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: booklore-mariadb-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-data
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: booklore-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-books
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: booklore-books

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-bookdrop
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: booklore-bookdrop

---
