apiVersion: v1
kind: Secret
metadata:
    name: booklore-db-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:aajFcBNFAuZ2Lo9DIsYJrW8=,iv:o3ZFD1Cyq0vZbPtSc9GXbXP0/ctGPIdFoOX5dR5iikc=,tag:J+ST6o0FgzRPFImC/NOpqw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:Ir7LsQarUOQ=,iv:JIhrJSrgPGDOobuB+elhRiD7jGbA18JW6Nbo+RMy0NI=,tag:RFhN77zBgMxZsXGWEN8PXw==,type:str]
    DB_USER: ENC[AES256_GCM,data:2ZCeBFJJvzw=,iv:mmo/DWndnfYhlYwnVVLIp9E4qZ9KmnfJz5hHC4qm8xI=,tag:S/PMWp+8qSUBRU2XA8cxsw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Xak8I3FwO3Qk1cxpfkIn64c=,iv:MV9X+/8EcddKd0vSQjhrf7BRZtYDNLFfuuGo40LQuvk=,tag:53cQoa/Z58ugQvoS8g81Qg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ZPDB925mXzWaxKTYc6kpjAFVjjcNHwKmZrzyn0Ruk55Q7/tsavuYyg==,iv:CCxkNvf3la2BR0oLqazWILZ+glPbPTsiccyqEjRlXPs=,tag:8YeQi85OQN99Ujji7TAymQ==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:fXDFW0Ts0FA=,iv:3YsRvk0p3kL2ZyIDqgguxmSxScq2rg+cIePOcgx3rOs=,tag:MGZpemsBHU4Q6MWIvpqEJw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:x7nw/kXWm+yJxZBFjOX6sko=,iv:90P3xeTA2k1L3Tzj4ecmkqlTzZXNADqJRTviNqh8fSI=,tag:HCHq8QAvWozK2FPUeblhXw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:vPN9f4dsliHK4k8=,iv:zny+6Yfnd6iwgtKLEUTHjYcpzDKb2ySUXctt3gflRRk=,tag:GtyO5Gc0CC6wOvfRPacIfg==,type:str]
    PUID: ENC[AES256_GCM,data:Y6rQkw==,iv:nDH9m2SK81daAnq3CVMgcSNyRct9iIbrL7FDpOoFv08=,tag:NZoNksj06gS3tQsuJ5FnKg==,type:str]
    PGID: ENC[AES256_GCM,data:+v8/NA==,iv:cXkUNZ/1/fFxtIDqiraJoo4y65qB5DSdreGocySOuyw=,tag:sNaYdXa8ru4hnsLPRXS7qw==,type:str]
    USER_ID: ENC[AES256_GCM,data:m/1IGg==,iv:stO0d5GzP1CmluWM1F/t2MboFMaqTw0jdu0kRlL/DhE=,tag:w2VfIF/QhTh5a0WwbEAUhA==,type:str]
    TZ: ENC[AES256_GCM,data:pyQXbiogsA==,iv:+j7FBw1QKoYrTvV4vQL96G1RdxcYl1fTNHc9xMh6HIo=,tag:ScZ0B/FkDpj7cyzAy5YLzg==,type:str]
    DISK_TYPE: ENC[AES256_GCM,data:tGcYFZk=,iv:BrGDbN6IW0fuiFxHddYdDrxTRzwNmlR2afw4MWVT+BE=,tag:58fl+AHa/t6285UQqC1TJA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eEplUlk0ci9vSGt1cXJS
            SUdHQURwdm83ZEtHQU5MS1JGUmI5NHVTc2dvCktPSkttMGhIamx4dzBwOUY4WUJl
            UGJ5UEEyc09WNm50elFqOUtsL1cwVmMKLS0tIGtLaUNkeFZYT2tJOTFxRzVDNlNp
            Z1QrbUJFVHR2aU5meWdOdnNjUkUrc2cKtTyNTmFnUPCr7TS2+BQ15oNa0PM/iisZ
            Fcwg4O5LcxZPEri6Tt1OdKwVP8e80d08cj7v5xnabuTcoGADtpGQ1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T16:08:05Z"
    mac: ENC[AES256_GCM,data:Z74tuTyEu4Z8E9da/oIxVQGCKszL8u9VQn4/E8hFOyRIVD2gMR/YhI9U4Dt6yTz2ti4pW1XL2fC7A2fZ5ZZr6wGI9pwbTp0zoy/vSqCtsGk87jX6M1nWkuvd3L5QDEhKebWtV9ll6BFjtFDiTJAxBaU1mKj/FtqjIoZU2dqfgS8=,iv:vX9gFBxX+yztTvPOXam9M5Rs00z8fDMO0sjAPbCwGIY=,tag:6fDUyWci5+V9R8WFtoyHdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
