apiVersion: v1
kind: Secret
metadata:
  name: booklore-db-secret
  namespace: multimedia-factory
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "ksucml23520kycmls"
  MYSQL_DATABASE: "booklore"
  DB_USER: "booklore"
  DB_PASSWORD: "ksucml23520kycmls"
  DATABASE_URL: "jdbc:mariadb://booklore-db:3306/booklore"
  DATABASE_USERNAME: "booklore"
  DATABASE_PASSWORD:  "ksucml23520kycmls"
  DB_HOST: "booklore-db"
  PUID: "1000"
  PGID: "1000"
  USER_ID: "1000"
  TZ: "Etc/UTC"
  DISK_TYPE: "LOCAL"