---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker
  namespace: extra-tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: speedtest-tracker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: extra-tools
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
