apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-db-data
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: youtarr-db-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-data
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: youtarr-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-images
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: youtarr-images

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-config
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: youtarr-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtarr-jobs
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: youtarr-jobs

---
