apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtarr-db-data
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/youtarr/db_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtarr-data
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /mnt/md0/MediaFactory/custom-downloader/youtarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtarr-images
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/youtarr/images
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtarr-config
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/youtarr/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtarr-jobs
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/youtarr/jobs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
