apiVersion: v1
kind: Secret
metadata:
    name: youtarr-db-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:za4lBN3Xikw17Tjf/sc=,iv:veBrT9Iq75rf51SM37Gg2e4E55NIpHz4qLEuV7E8eQU=,tag:xF9/e6tYXa9QkYf4nkWwFQ==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:pNh0g2T7Cg==,iv:J07mml10H4HH33q8lwYE+xHL4JGHOKwajkdqMo/r2mY=,tag:N3gCle9yxaQdU+kQGm2VmQ==,type:str]
    MYSQL_CHARSET: ENC[AES256_GCM,data:iSAYEASwPw==,iv:IHQNApSgbKCLuBsq/2ma/TNcuYvVB8UYpEoKq0i0lxs=,tag:49zAvCvbqziOU7xr4GXqVA==,type:str]
    MYSQL_COLLATION: ENC[AES256_GCM,data:ZSWuc6qLDieqD/x/uuHZu8bx,iv:tnmRXW2QHYUKseSiXBwlwjO4quJ/RuFwfR+qqQNevbM=,tag:Y5vFSRuEsPErbnQMXbq+Pg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:8SloidRQHi0M3w==,iv:7ubh2B5mAWUzElDb69LOjmva5FBKsfVr67evfBBXnnU=,tag:7O5isjBfhX9E/WEdYtyo5A==,type:str]
    DB_PORT: ENC[AES256_GCM,data:e7e/bQ==,iv:Ioh7268ltKXeRKfXbzdPe9HMAJI2IovWQYS+PTwdqck=,tag:jWVbTtGGyZzk5WWYYXfVpA==,type:str]
    DB_USER: ENC[AES256_GCM,data:YmBgEA==,iv:pfMaclMSk1rALjoN/lOaUNHl6SR/J61l7RmrzeLMAV4=,tag:U0Oro5FLyzM4cm1mtLK1mg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:8Wt6gVoiQDHLukCbeno=,iv:9p9MCEPI/AnnK8aNRDD/5S/0zB8T9JU8C8c2HaZaQOA=,tag:9pOBYzMGaPEWbWJoG5MeJg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:k0WuHRVk1A==,iv:HiwBAvVPyzBBzfeLbRU5u9lS23qDU2En3l0Qh/8wlkc=,tag:zCHgY5RVmCUtQSbLxmtLPQ==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdFYrNVk4NkJJdFg1MlJi
            Q05tZTVDNVNQU21CWXFOdklSd1cxU1JiUEVnCkR4N0tYeHFwdlNVVWZFWW9aK1ZR
            blZNRllQM1BUQ0JJdmFsVUpSRkd0NzgKLS0tICtvU3BXaGh3eUl1TGxLK21CbnRW
            Zm1RL2dXcVdZZ1gyUmhrWm1YaXVObkEKF9IXUIoExeSJhUzNu6A4ll2hAI1mNwY3
            ZwL7yGv7hgTCRRxEaH/sQOPz9v8tJv9vjdu7XMHsgEuhXkwLMRiP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T10:12:56Z"
    mac: ENC[AES256_GCM,data:9F+gBA3F9/G/xdX8rCgwhftIG0ZAduJNk+sebPOCn55ULS5EfKRmNaYimhPHESqyjV0dW1v5yd180IUCNqgYSgkB6FJsu2+rpGiJDstvtI7GXCCTDwFfcQjtFHl6Wv2K4l5oSly6IiL4zSEf5EjlUxYyY5vuPqlG5EKQKxnljqA=,iv:hGbs3UT3qKPkc44oaSNdxs1F79qt+A/lLLLSI5KXq/Y=,tag:54ez3yzW2Z8XSUxUkk/Ycw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
