apiVersion: v1
kind: Secret
metadata:
    name: youtarr-db-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:za4lBN3Xikw17Tjf/sc=,iv:veBrT9Iq75rf51SM37Gg2e4E55NIpHz4qLEuV7E8eQU=,tag:xF9/e6tYXa9QkYf4nkWwFQ==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:pNh0g2T7Cg==,iv:J07mml10H4HH33q8lwYE+xHL4JGHOKwajkdqMo/r2mY=,tag:N3gCle9yxaQdU+kQGm2VmQ==,type:str]
    MYSQL_CHARSET: ENC[AES256_GCM,data:iSAYEASwPw==,iv:IHQNApSgbKCLuBsq/2ma/TNcuYvVB8UYpEoKq0i0lxs=,tag:49zAvCvbqziOU7xr4GXqVA==,type:str]
    MYSQL_COLLATION: ENC[AES256_GCM,data:ZSWuc6qLDieqD/x/uuHZu8bx,iv:tnmRXW2QHYUKseSiXBwlwjO4quJ/RuFwfR+qqQNevbM=,tag:Y5vFSRuEsPErbnQMXbq+Pg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:siY790JDZJgpzFuw2Af8BxA3qC3GWqSH5a21C5723iiRJg==,iv:U1n0C45bmMlxmR/2hhJNGTmSVI2i31xLXS4/14O+s40=,tag:X7SS31ofz7dAGPij7NM3LQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:sCcd1g==,iv:0PcajULj47WU5ba7nRSYDqFzJbKpPVV/YEV8ndoEFok=,tag:ehlWO9zkmm/G2v/Dii8KlA==,type:str]
    DB_USER: ENC[AES256_GCM,data:8SF55ftLvA==,iv:JwgnpbWxOLrUHAEcEk6cKonE3QBKegzvJ+TVnUPSDX8=,tag:5/0EmqCxEYMsMxfg6sdxcw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:8Wt6gVoiQDHLukCbeno=,iv:9p9MCEPI/AnnK8aNRDD/5S/0zB8T9JU8C8c2HaZaQOA=,tag:9pOBYzMGaPEWbWJoG5MeJg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:k0WuHRVk1A==,iv:HiwBAvVPyzBBzfeLbRU5u9lS23qDU2En3l0Qh/8wlkc=,tag:zCHgY5RVmCUtQSbLxmtLPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdFYrNVk4NkJJdFg1MlJi
            Q05tZTVDNVNQU21CWXFOdklSd1cxU1JiUEVnCkR4N0tYeHFwdlNVVWZFWW9aK1ZR
            blZNRllQM1BUQ0JJdmFsVUpSRkd0NzgKLS0tICtvU3BXaGh3eUl1TGxLK21CbnRW
            Zm1RL2dXcVdZZ1gyUmhrWm1YaXVObkEKF9IXUIoExeSJhUzNu6A4ll2hAI1mNwY3
            ZwL7yGv7hgTCRRxEaH/sQOPz9v8tJv9vjdu7XMHsgEuhXkwLMRiP1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T14:20:49Z"
    mac: ENC[AES256_GCM,data:m/RzMNl34NwcGxZNsXnx/OfYzxH3wp0l+vOyaNnHxwe6wDHcMgI4kg3Biir1iVOsWr7NEzJDKi5KtkN5hUU/bDeDDR+TGdtzMwSMEGRBA1oKQppi/QttauImcNtZa9jfPeX2Wx6GKkVyvAqk5ECZ2Hd3aRgzNSCa6T3yebbk3Ww=,iv:QEEO+q27z6B7OE0Ybluce5GtdJ1NYgjOohdIpbK0cGc=,tag:V+GaDRp4etl9ubKQZpmnFQ==,type:str]
    version: 3.13.3
