apiVersion: v1
kind: PersistentVolume
metadata:
  name: yamtrack-db-data
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  local:
    path: /var/lib/rancher/k3s/storage/yamtrack/db_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yamtrack-redis-data
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  local:
    path: /var/lib/rancher/k3s/storage/yamtrack/redis_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
