apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-db-data
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: yamtrack-db-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-redis-data
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: yamtrack-redis-data
---
