apiVersion: v1
kind: Secret
metadata:
    name: yamtrack-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:nrvfAB6L4pX+9ko=,iv:5qa9IoquhDuhqXx+5dCIowdIaVBpcrpSLuLuN1fQB7c=,tag:HWAzZQq9CORcv4XjVVN8Hw==,type:str]
    SECRET: ENC[AES256_GCM,data:5E+TcBdNfXiA5HUlR/TaEA7xYCk=,iv:4UcnQDUW3+e9YSyDEJC89ks8hP7RqvmO36SUlenGZv4=,tag:w2g1MXt/FTLZLKAdnNhY8A==,type:str]
    DB_HOST: ENC[AES256_GCM,data:6rQ+9KgPrl5siBxHKF9alyxP4gMvrV+A46JjA6AvU3kZVcevCmI=,iv:CyhZjtozdGk8B904TUg3hLE4ggAoosRVq/Xl/q01k2M=,tag:svjAKLL5N9kY71r9hKcunw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:kn1QmLq2ey8=,iv:GVoZrgm+X7oOJvqijyLTAxJN0tpVn9SLfYcwutYg9Aw=,tag:eaJPWmz0d/MjSmGSzHQPiQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:FZVT9aEJUUE=,iv:KVR61NZ7GHzAoEU+wLkMsr9MQV5PUknPF4ayz9GD1q0=,tag:QQPGcWkOLZo+gtbvIHD1Bw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Ii17nuh5LGbHcvISlFYdCbapoiw=,iv:SJ4Koxvci/IH3mDnzi0vhS9TCslFFx76wAF3D2/u8u8=,tag:XkegJIGBG+TrRpH6Pt1NkQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:nh3GHA==,iv:4yXJ8ll9M+SRjCTZWz/XNnk6BIscLAMOR1xv6C9U8Yo=,tag:Kt5Li0S2B2IBY1F0lOoqog==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:ZTU8sTlQ3TOq7K2dFTDXaBDyc6sZCgGOoR23HjzVAs1OcQvqePEH,iv:CKzNyBCGNZmkfC4iOwpd2LCKerk8PT2+PvJEFMkrADM=,tag:bC+XG5RpB00VJE4VLX0RNw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:HTLDuQ==,iv:NksgOAhGiuL0dPgYy0ZwCHW4EFdWsbXzyrZc3wg+2k8=,tag:fsxn8KgC3UslGpNyjgGgyQ==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:GA==,iv:NTYH0keLJV+Hk/05Gbb1ukPRy+1dYMA0xDDQQcbuQ4E=,tag:OJvFHoRSMS8DZxecL8ZG+Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:yinv8NYApj9L9JumRqgsU1L8HYFS,iv:Pk4Rqgb3FyoBmaxMjGKqtEXYHnuM7DELVNNvo6ZUt10=,tag:krvD9Htnza3jDarZTDlcRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdFYrNVk4NkJJdFg1MlJi
            Q05tZTVDNVNQU21CWXFOdklSd1cxU1JiUEVnCkR4N0tYeHFwdlNVVWZFWW9aK1ZR
            blZNRllQM1BUQ0JJdmFsVUpSRkd0NzgKLS0tICtvU3BXaGh3eUl1TGxLK21CbnRW
            Zm1RL2dXcVdZZ1gyUmhrWm1YaXVObkEKF9IXUIoExeSJhUzNu6A4ll2hAI1mNwY3
            ZwL7yGv7hgTCRRxEaH/sQOPz9v8tJv9vjdu7XMHsgEuhXkwLMRiP1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T11:43:36Z"
    mac: ENC[AES256_GCM,data:PuMRTdD9ezen4fl7wHpvqmyN5tA98qa3Cjm0sEOYA0BAMnX3uSNcT0qhZuCIx1IqMFwqSNf/unB2LmGohgDL4zWxqwAC7kU+RddRUr3h+k3EHhVjvcSBkL32tAS1LQNiHAkqQFbBQu6aPo5LfO5TVOYjns4sAp2nmmYDamjb9Fc=,iv:fOFqDX3+Nfy72p9fn72LcQhiEi+CNfdW9O76AbSj6sE=,tag:tFwldsRx09AsD4VRXRQtgQ==,type:str]
    version: 3.13.3
