apiVersion: v1
kind: Secret
metadata:
    name: yamtrack-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:nrvfAB6L4pX+9ko=,iv:5qa9IoquhDuhqXx+5dCIowdIaVBpcrpSLuLuN1fQB7c=,tag:HWAzZQq9CORcv4XjVVN8Hw==,type:str]
    SECRET: ENC[AES256_GCM,data:5E+TcBdNfXiA5HUlR/TaEA7xYCk=,iv:4UcnQDUW3+e9YSyDEJC89ks8hP7RqvmO36SUlenGZv4=,tag:w2g1MXt/FTLZLKAdnNhY8A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:yXurA4tvc636d3Qi51zgiXwQu7fVjWnaoR+d,iv:YSNgKGcyRfMxUXp86Q5/i9iPKCf3rmtYuQqzbfT5PNE=,tag:6GfA83RhzU3WBRypVbzk5w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:CpSDN8b3dH1oSY4=,iv:axM1t/dJmV+xs5TFtWBivZGBUVswDC5bFZ8wx6yfM/E=,tag:uGc50geqi0q0/wAEjcbOyw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:kn1QmLq2ey8=,iv:GVoZrgm+X7oOJvqijyLTAxJN0tpVn9SLfYcwutYg9Aw=,tag:eaJPWmz0d/MjSmGSzHQPiQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:FZVT9aEJUUE=,iv:KVR61NZ7GHzAoEU+wLkMsr9MQV5PUknPF4ayz9GD1q0=,tag:QQPGcWkOLZo+gtbvIHD1Bw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Ii17nuh5LGbHcvISlFYdCbapoiw=,iv:SJ4Koxvci/IH3mDnzi0vhS9TCslFFx76wAF3D2/u8u8=,tag:XkegJIGBG+TrRpH6Pt1NkQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:nh3GHA==,iv:4yXJ8ll9M+SRjCTZWz/XNnk6BIscLAMOR1xv6C9U8Yo=,tag:Kt5Li0S2B2IBY1F0lOoqog==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:8kruZcg7vNc=,iv:QZjlVpBSIKIf25PXC/k7yaQ4tgpvxxxtGvseBv1kQyA=,tag:cTSTjlBnoz1nfDwZsbVfAQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:OEdND1ynSYQ=,iv:WRiM76e8nm+s3LtwPqye1XwQDePQICjiVWAzwIR8Fvk=,tag:wq9qJ2anGwJ6V9syzrYq0w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8Mc0PDP+FiXERwfIAgqBUrxCplo=,iv:G2w2O4Rd9p2EmtiPNNPGNw7TqhCMZgqAwAdPHUJ/brw=,tag:LCC7+KDEJhLbPh0VWKk7PQ==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdFYrNVk4NkJJdFg1MlJi
            Q05tZTVDNVNQU21CWXFOdklSd1cxU1JiUEVnCkR4N0tYeHFwdlNVVWZFWW9aK1ZR
            blZNRllQM1BUQ0JJdmFsVUpSRkd0NzgKLS0tICtvU3BXaGh3eUl1TGxLK21CbnRW
            Zm1RL2dXcVdZZ1gyUmhrWm1YaXVObkEKF9IXUIoExeSJhUzNu6A4ll2hAI1mNwY3
            ZwL7yGv7hgTCRRxEaH/sQOPz9v8tJv9vjdu7XMHsgEuhXkwLMRiP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T16:08:35Z"
    mac: ENC[AES256_GCM,data:mRKh9Wkr0N7HZsOd8wtj4PMgDskPZxyE8eOomVGvfr6DPm9J6MLH97o4jYTGhsbjmQvnqyDcE7MMQL/bWxG88wCspzcX4csAwbYC7uADpVqOicm+13R5lsj4VS+hJ6QGW18tFKOqfbXd/bOUDBGRc4CWkI0MdZnLlIzCWlpcLmk=,iv:sxiuf3QsWm+AdjeX3D39XYfB3sn5LMxyOhwSzOGjLQs=,tag:PhvDL3JkmOEdvCwr+Emf7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
