apiVersion: v1
kind: Secret
metadata:
    name: yamtrack-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:nrvfAB6L4pX+9ko=,iv:5qa9IoquhDuhqXx+5dCIowdIaVBpcrpSLuLuN1fQB7c=,tag:HWAzZQq9CORcv4XjVVN8Hw==,type:str]
    SECRET: ENC[AES256_GCM,data:5E+TcBdNfXiA5HUlR/TaEA7xYCk=,iv:4UcnQDUW3+e9YSyDEJC89ks8hP7RqvmO36SUlenGZv4=,tag:w2g1MXt/FTLZLKAdnNhY8A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:yXurA4tvc636d3Qi51zgiXwQu7fVjWnaoR+d,iv:YSNgKGcyRfMxUXp86Q5/i9iPKCf3rmtYuQqzbfT5PNE=,tag:6GfA83RhzU3WBRypVbzk5w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:6rQ+9KgPrl5siBxHKF9alyxP4gMvrV+A46JjA6AvU3kZVcevCmI=,iv:CyhZjtozdGk8B904TUg3hLE4ggAoosRVq/Xl/q01k2M=,tag:svjAKLL5N9kY71r9hKcunw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:kn1QmLq2ey8=,iv:GVoZrgm+X7oOJvqijyLTAxJN0tpVn9SLfYcwutYg9Aw=,tag:eaJPWmz0d/MjSmGSzHQPiQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:FZVT9aEJUUE=,iv:KVR61NZ7GHzAoEU+wLkMsr9MQV5PUknPF4ayz9GD1q0=,tag:QQPGcWkOLZo+gtbvIHD1Bw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Ii17nuh5LGbHcvISlFYdCbapoiw=,iv:SJ4Koxvci/IH3mDnzi0vhS9TCslFFx76wAF3D2/u8u8=,tag:XkegJIGBG+TrRpH6Pt1NkQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:nh3GHA==,iv:4yXJ8ll9M+SRjCTZWz/XNnk6BIscLAMOR1xv6C9U8Yo=,tag:Kt5Li0S2B2IBY1F0lOoqog==,type:str]
    #ENC[AES256_GCM,data:yCsId/rVSTw3XXhlrLQ2EhPUr9NSoA==,iv:KAroYBU44StRmOviat0R3blAnFxmo2UkHroWQ0ET9io=,tag:lnZiEwODDlNIYXYZQH6NCQ==,type:comment]
    #ENC[AES256_GCM,data:2MxXzN28OqUAIe/Ai5GfQsg5p8PUV11q,iv:vSZ09h4pmtwZB+af1MfAIf4o+yw3+udyPpWuZ/2Mqgg=,tag:U8g4Md9eFqXgsrKrXkGBLw==,type:comment]
    #ENC[AES256_GCM,data:LLW92uD64i3+Lb21TjIGMtF06Wkg2n8uSHdMAnPnhvbO1k2ne7E99A==,iv:GuZEgCybpGGNCM5uO8w8f1MTda1ZT0QxlIMZRa2/1+o=,tag:UGX1QPQsAzKjQvYTbhWn5Q==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdFYrNVk4NkJJdFg1MlJi
            Q05tZTVDNVNQU21CWXFOdklSd1cxU1JiUEVnCkR4N0tYeHFwdlNVVWZFWW9aK1ZR
            blZNRllQM1BUQ0JJdmFsVUpSRkd0NzgKLS0tICtvU3BXaGh3eUl1TGxLK21CbnRW
            Zm1RL2dXcVdZZ1gyUmhrWm1YaXVObkEKF9IXUIoExeSJhUzNu6A4ll2hAI1mNwY3
            ZwL7yGv7hgTCRRxEaH/sQOPz9v8tJv9vjdu7XMHsgEuhXkwLMRiP1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T10:27:05Z"
    mac: ENC[AES256_GCM,data:7RLgptIJj2lVorYqY5AElguLnUtc5EOtv2ws7L2TsCX2IgtEElVHkC58wlrY05WuE6aMJ+Stz2oURqV/ySQqoszNIAnAmawx2tcKP985HGTVuPeKNmV4Ay7ROmbvKn3RmDsbWPWeYX7oHo+sSFTORSz96l/Dc6rqefrlmfT8g2E=,iv:r1QxXVLuM8SuUuvdnVHdZBkSjzed8hALJYmJRXqn/K8=,tag:A9owM5uzu/pUUzzgebMOvw==,type:str]
    version: 3.13.3
