apiVersion: v1
kind: Secret
metadata:
    name: romm-db-secret
    namespace: gaming
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xfBCjmtLDV9I3Waolr3+2s7Vfxcuoo6Mrg3lfhDu/Jdt07HF1gpKC6Hguw==,iv:slmjwAJ9YTo60UZQPTlt/J7C+JxWmIFp05cUpbWzg18=,tag:yMTBkxWy/LOKBI2zkjiFMw==,type:comment]
    #ENC[AES256_GCM,data:ASH8pnn94iToz3JtZNEQxeZwS8fN263za1qO8EQEHRacMb8HbQ==,iv:q15sv/BzPBiRgTVn+nWBVOjdFBJguG6YmxNZc//5TAw=,tag:Su9iDs2bR76Z/vSaiD+JBg==,type:comment]
    #ENC[AES256_GCM,data:pmwTWOd4RGu4mqC5dkkYDMeeJg==,iv:D/1207xNsewtpDMZukz5iLN1SvhEP//yHxDW1ycszc4=,tag:1gWI4Ckaco7XbpFnPl6Y3w==,type:comment]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:eG8jwUpHEdnfni6s+YUCUrm0oHZXGhNTdtC6vZDZgHunRF2289TqzvGH40zyefeDQeIzUUTDr9uH5NitVF/uHw==,iv:m1cOu6O8flg5JeCT0+b7MwJIYuQAgvdg5BztaCA4XO8=,tag:v9MUMArgnZHxXYwEbovQtw==,type:str]
    DISABLE_USERPASS_LOGIN: ENC[AES256_GCM,data:Kt2+OA==,iv:5kyu2YcrwfSYfR5Nf9Q2z2war57GS80Puy/0PNB6wrs=,tag:L3Gqqu0pHHWYBJuMShpmBw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:eYiN8e5HaPjrcIXp7WX2waM4iTUdxUCsSDV2tkYQNvzCPQ==,iv:u2jt7SZ4ltTy0gwer+SpCIxkxDNd/CC7XIM3xN6G3+g=,tag:O4XZx5fOXKkwwFswyKOBCw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:bo5ihg==,iv:Jx5UouP6hJ38yankfEppeMiJxHqWhtc989W3sbORJ5w=,tag:Rwqrv+dawcFeAHXBqggMdQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:P4DVmQ==,iv:ZhS0HG5oX5VG+cwypKOb00n5fCCIIJwlbXGX9+pInSk=,tag:9L5nIko+SrlgLfOhYtVbeQ==,type:str]
    DB_PASSWD: ENC[AES256_GCM,data:C8CTDcYaBuPb1Mt4KwAyF+aK,iv:WICkBHteMM4vMHVo+5OilQ5AVfrzOPv8Xqhg1WLnBR8=,tag:+OyW9T1gZz3S1Jnv5oBtpA==,type:str]
    SCREENSCRAPER_USER: ENC[AES256_GCM,data:zHS89tYV/QYEDg==,iv:2HAMy19OnLO6+76Xmsu7P8cAzhy6G7UWLno8+r4Gv9Q=,tag:7BsX44wtUfaPJt0eR8ScTQ==,type:str]
    SCREENSCRAPER_PASSWORD: ENC[AES256_GCM,data:n4upngfL5v+uZ5UZu611/f3k,iv:++/3OJn4KMAgWve9F8Sc2zba46y5sD5T3omNVac+y/Q=,tag:YN2J3UfVyjg3TbBfj/9i6Q==,type:str]
    RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:y7ov+rJ/V6m4TafnNIyyvIqGmTwPepupEQbmxz7bggM=,iv:Nilfp2XKBr7tMng5gDzUpA3q1bNRFNnqLBmcJ5PfY2U=,tag:77OKfzh4EKbKO02KXb6rUA==,type:str]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:/Q/tHVBsPL9ZykuLbtSGgWXuSEF/qnd1qVYKEdWao/M=,iv:kggcmnb71lTaQ/M1RQ/w2WqIoVVLW1kmcNuBMt5nK2s=,tag:tZ3zvy9bebNk9YNgZ3Wgtg==,type:str]
    HASHEOUS_API_ENABLED: ENC[AES256_GCM,data:tS4bYw==,iv:kbmhWqI8OxT1WBvqntr+kSNoSErPynrvIr6E3npP0DE=,tag:LEpCvzgpukKcZprlNt0nqg==,type:str]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:qDfSZdp0ELP0YdCI4maC14x7ckz03l8MrVB3MSi6,iv:ze5Bk1H/IxVwGtI4AalWh38d3WgoFEABrezj0vpm2Pw=,tag:I/4U+QrdvxoNfKrogeXHrg==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:/WMBKzatu/lgxdoq19Xe7e5rk+LGMBwYlPhRO1T/,iv:04svY6tFyYgNzgdGatj8kfvCwP5GqbeGJwf+VqdyVkI=,tag:alptv8STpwTN1yIKSTEQEA==,type:str]
    DISABLE_DOWNLOAD_ENDPOINT_AUTH: ENC[AES256_GCM,data:m5Ca2w==,iv:c+FedJ/38CX2S90uR4xduO+cqPK+568jA4Q6H4dpACQ=,tag:Xbw3g5JSTr3QIMg+Vx/0NA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:h6Ep33A66QhDPGpikGPiS+t8NhRyC73UErLy5Y/VMQODXnmRcNUw,iv:2TMPY/0XgVpLGuwtyyBsj9S3hfjixCkB11FpC8LfJdk=,tag:QuRRN6T2KI04BxsH7moPvQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:zdIFeA==,iv:Ar7vIP2BMCKhGIHYZyblDxibxDDMd9CwBzTM3ZAP36U=,tag:22VEsiCrHaf+RAbIO+J3IA==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:Ow==,iv:KL7VXCZnhCXNnfnW6Goud3jZTFREp3qXb1NI3vc1hpc=,tag:qihiARHoukLRnrFKiEF/Ow==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:oPTw21yh6EASRmJ4adk6anDd5/dr,iv:RO7oqHOihnRdIe1zpnQOWqihFLP44pJtWtbInsAMKhg=,tag:hlIXCVmyzJe5gCWs1aKnzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSWlxMWE4UDFLL3IzRklx
            UnF2Ym5nTEhaZThOdnc1ZU9EbjFVQmhjWVNnCnJZQXdESUwyVGVGWnhLaE5WV2dL
            U2hxTzlvMXl5M3hJZmpsaW82VjNmTkkKLS0tIEhNaDI0QnNRcmVDZlFZL01Xa0Jw
            anpuUmNQVnFoQWliRVFUSERzVFRRUncKwWDS21qx2KGEM4NldtRghjOaQ8LhLMLu
            HWd0+haibTTloEvmVPUKqAuyddgQrlp7aeucsBCjCFMWwtPhf8qliw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T16:15:58Z"
    mac: ENC[AES256_GCM,data:I/DgMR1DVM5xURREc7R2VK3KTzReF7g+lnvOSUi1rfCJP8WPPRrxa6ay83pAFVTe7sVc6zcK8SWFLuRYabvmkMbIShrWJ+cOYHjCLzILuOoOYpbWTuYIfhGse0wvKAWMaj9T4n4AAEqpnUHFLk9tHdaj1WLobxTLqwYp75ptcSo=,iv:46i6JbiMb7KraPh6ue95YTqAKxSwtU15AT4tnM/KBDE=,tag:Q5fDHpgv2hwtKZcqnevZzQ==,type:str]
    version: 3.13.3
