apiVersion: v1
kind: Secret
metadata:
    name: romm-db-secret
    namespace: extra-tools
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:hjPgbg==,iv:vhl7SMCqVmRcGTndJdYis5cE6txXUsBbn4BOdjtkbY0=,tag:Fqj/89DizoCgww8Ao6ybyw==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:Z+wpqbkbFU12qi+rr4wamVFz,iv:Q3j/iDYtv0Avh3Lg5qeCE6yYmiSzvgJn8RI7//AwpyU=,tag:NP0TxZgLpg0HO4jU1/IC5Q==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:eG8jwUpHEdnfni6s+YUCUrm0oHZXGhNTdtC6vZDZgHunRF2289TqzvGH40zyefeDQeIzUUTDr9uH5NitVF/uHw==,iv:m1cOu6O8flg5JeCT0+b7MwJIYuQAgvdg5BztaCA4XO8=,tag:v9MUMArgnZHxXYwEbovQtw==,type:str]
    DISABLE_USERPASS_LOGIN: ENC[AES256_GCM,data:ZKNqXw==,iv:E8lrG/2c+GOiCprErdTSOSJGoqEqYrTLVKqnlDtkPcU=,tag:NJhZHc2L60eJxSs66s1Fmg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:3m8Dp8iW2A==,iv:nsjr6Us3SB4suzE21kSUzic+l2RBK85kOtn7Na3qNXw=,tag:svrsbq+qecR6vwYbVecisw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:bo5ihg==,iv:Jx5UouP6hJ38yankfEppeMiJxHqWhtc989W3sbORJ5w=,tag:Rwqrv+dawcFeAHXBqggMdQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:yWOd0SzxULfd,iv:UwzobUprwULB83cws4nFdK8rogoWnJYFiGSjOleMEGc=,tag:gjL6kmyWet9fI7avuhzXag==,type:str]
    SCREENSCRAPER_USER: ENC[AES256_GCM,data:zHS89tYV/QYEDg==,iv:2HAMy19OnLO6+76Xmsu7P8cAzhy6G7UWLno8+r4Gv9Q=,tag:7BsX44wtUfaPJt0eR8ScTQ==,type:str]
    SCREENSCRAPER_PASSWORD: ENC[AES256_GCM,data:n4upngfL5v+uZ5UZu611/f3k,iv:++/3OJn4KMAgWve9F8Sc2zba46y5sD5T3omNVac+y/Q=,tag:YN2J3UfVyjg3TbBfj/9i6Q==,type:str]
    RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:y7ov+rJ/V6m4TafnNIyyvIqGmTwPepupEQbmxz7bggM=,iv:Nilfp2XKBr7tMng5gDzUpA3q1bNRFNnqLBmcJ5PfY2U=,tag:77OKfzh4EKbKO02KXb6rUA==,type:str]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:/Q/tHVBsPL9ZykuLbtSGgWXuSEF/qnd1qVYKEdWao/M=,iv:kggcmnb71lTaQ/M1RQ/w2WqIoVVLW1kmcNuBMt5nK2s=,tag:tZ3zvy9bebNk9YNgZ3Wgtg==,type:str]
    HASHEOUS_API_ENABLED: ENC[AES256_GCM,data:tS4bYw==,iv:kbmhWqI8OxT1WBvqntr+kSNoSErPynrvIr6E3npP0DE=,tag:LEpCvzgpukKcZprlNt0nqg==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSWlxMWE4UDFLL3IzRklx
            UnF2Ym5nTEhaZThOdnc1ZU9EbjFVQmhjWVNnCnJZQXdESUwyVGVGWnhLaE5WV2dL
            U2hxTzlvMXl5M3hJZmpsaW82VjNmTkkKLS0tIEhNaDI0QnNRcmVDZlFZL01Xa0Jw
            anpuUmNQVnFoQWliRVFUSERzVFRRUncKwWDS21qx2KGEM4NldtRghjOaQ8LhLMLu
            HWd0+haibTTloEvmVPUKqAuyddgQrlp7aeucsBCjCFMWwtPhf8qliw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:21:10Z"
    mac: ENC[AES256_GCM,data:LyaPDgIKfKa8N1pI9KdI8hOzHnB3WmXg3qFguYEcIp3jMpYXG6vZy1s5xSdjbUxOOWnj4tRXEjOzqNFPhBNBVotMHnh0VcfY/g2QTe4ismNCctlwCuV/+DXKkwQJ1ZZ7u8YT/dP+eKq8oUNVsdqOcP3WKHYzXSWWK99+WM/x8Ts=,iv:GN4pk1Z8rt+1TVNXhGD7Y1EMKgObgurTWO5/yRpA+vQ=,tag:qlH2U5bRmloUmop9/GUz2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
