apiVersion: v1
kind: Namespace
metadata:
  name: system-addon
---
apiVersion: v1
kind: Namespace
metadata:
  name: multimedia-factory
---
apiVersion: v1
kind: Namespace
metadata:
  name: home-automation
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: gaming
---
apiVersion: v1
kind: Namespace
metadata:
  name: extra-tools
---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-operator