---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-media-server
  namespace: multimedia-factory
spec:
  releaseName: plex-media-server
  interval: 5m
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: plex-media-server
            patch: |-
              - op: add
                path: /spec/ports/0/appProtocol
                value: https
  chart:
    spec:
      chart: plex-media-server
      sourceRef:
        kind: HelmRepository
        name: plex-media-server
        namespace: flux-system
  values:
    statefulSet:
      podAnnotations:
        uptime-kuma.io/enabled: "true"
        uptime-kuma.io/type: "http"
        uptime-kuma.io/url: "http://plex-media-server.multimedia-factory.svc:32400"
        uptime-kuma.io/name: "plex"
        uptime-kuma.io/interval: "60"
        uptime-kuma.io/retries: "3"
        uptime-kuma.io/notifications: "Monitoring Bot"
        uptime-kuma.io/status-codes: "401"
        uptime-kuma.io/group: "Media & Streaming"
    image:
      registry: index.docker.io
      repository: plexinc/pms-docker
      tag: latest
      pullPolicy: Always
    ingress:
      enabled: false
    pms:
      configExistingClaim: plex-config
      gpu:
        nvidia:
          enabled: true
          devices: "all"         
          capabilities: "compute,video,utility"
    resources:
      limits:
        nvidia.com/gpu: "1"
    runtimeClassName: nvidia
    service:
      type: NodePort
      port: 32400
      nodePort: 32400
      externalTrafficPolicy: Local
    extraVolumeMounts:
    - name: plex-media
      mountPath: /mnt/md0/MediaFactory
    extraVolumes:
    - name: plex-media
      persistentVolumeClaim:
        claimName: plex-media
