---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex-media-server
  namespace: flux-system
spec:
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
