apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranga-manga
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: tranga-manga

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranga-settings
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: tranga-settings

---
