apiVersion: v1
kind: Secret
metadata:
    name: tranga-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:0TSAyHaqjQKE5ejos/n5OSOPq8webxNTmsQOdNaExxFmZ66nRXg=,iv:3b1M7Kt7ay4T7MQApXA9pOKvdrSwefq0tJt5lEwZipg=,tag:dVFGCQOLOcxw3Pi9j6QfaA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:XRwHK4rs,iv:riocLyGLVS6AaKfr9CmD5U+8faFkBtI7etHpXfxDsTY=,tag:IAtakQf3pbY/Yd+OFrpZ9w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WAsqizygv8Ik+/BahkvtJp5HQQ==,iv:YpNoU2HwWXoUzvZHC8Hyqk2rPcLrXZ8MI+X1wMMaBFY=,tag:rBXhF5k3ROiKlUo50POqDQ==,type:str]
    FLARESOLVERR_URL: ENC[AES256_GCM,data:Bfoy86REDqy1CXj0rRzcGa20SjCjDiKB,iv:mXqnz7ckeDfJ+q/wuUDO6ctig0TeQSpT0LMP7JUk5Fo=,tag:1kzE6LU6PS1JYtLMp/Pmhg==,type:str]
    #ENC[AES256_GCM,data:hDtUIdRvoxW0edfXN69D+F6wZZQT92HxZFgpQY7Nog==,iv:26IocSqEn9wczqVVCOiXvC1cFslY317OautQNFjUa88=,tag:tDTw/55EGzMQRKRYgwsR2g==,type:comment]
    #ENC[AES256_GCM,data:IDQ7iVDT8CjspVbJffTdSLB7v80t7QjqYLUM5URcdYM0pQ==,iv:21y1I5OR6qOiDDS3oia6kPyygvgNjYOAJplcBaXXBlM=,tag:aKSdYbvFdzXy4YCTJ3RKbg==,type:comment]
    #ENC[AES256_GCM,data:VYTb1wgJpairtIJg0tMmyEZW8OFTVKdoB82qRWSpQZ2xUOTJ,iv:7AGt8l3ca7FRdmF24xXuXJT5ZXuNi0Haa+0L3CAvesM=,tag:TvC8yfAMH65eyyrlbLp35Q==,type:comment]
    #ENC[AES256_GCM,data:44qcRmEmTG4vDpeIpg3urXy/yo3FWRkoa4AbFUo=,iv:dHZKIwVhdSUNF3LOYIBU7n0PmGxH2aCOr0Lbo/Frol4=,tag:a6U4OWswLMjobNszUogo7w==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVTVMd21pY1RSOWQySkwr
            Vkk5d21IYnVyVVRIWG03eW44OVhIZE1rb21nCldEbk80UEl4allNS0Ivc1pYRUhx
            d211WGM2YkVqTm5NUHJDRlVpa2R2UU0KLS0tIEhTRHBlT0doMUNsak5OQ2lxa2Va
            OWVCYmN1eG90QjE3RUQ2L2xyaFc4M1EKq8rOtTdIcrsJo5ucnDSHRoJgRuzm0S/W
            9kQdDxxVY6AQSTHUaxPA3Z9gq2xk32ASiYs48riOIZBvwZ1+/5Kcvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T10:04:13Z"
    mac: ENC[AES256_GCM,data:BbQbjIU9MMe771gyh6NZknGgGgzqy0r7cUM9PiNoIAkbG7KMyYTNM4dMPNLXiFMk3MdCSTqYytakZIrvbom1WdCndT5jd8hzJLb30zBlXc0/xrVCypKUBLvSMTm3y3O8tlTQTVL+438Hk/S8mzj7y5+kOMfR3zgdq++QDb7Dp08=,iv:IhzMc4/2X65nRuXgD9E8H0JVYdRgald/l6ia3mkk3ps=,tag:NNU2KosDjEhS52QYSE20kg==,type:str]
    version: 3.13.3
