apiVersion: v1
kind: Secret
metadata:
    name: tranga-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:FLSB65bYZRW4,iv:avSJ2TQYsxjnaedJg6BQ7/djzNchO1fFrDUsfDL1O2w=,tag:PCpzxblWIS1+pbZ+/MNfew==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:LDxsvTM1w8c=,iv:kvnQc2YA2ozwSUh4RJpkai/1ksCHaaHW/ZQKw7PWKec=,tag:9s7G/nZhJGS3jzVnMBYHjQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WAsqizygv8Ik+/BahkvtJp5HQQ==,iv:YpNoU2HwWXoUzvZHC8Hyqk2rPcLrXZ8MI+X1wMMaBFY=,tag:rBXhF5k3ROiKlUo50POqDQ==,type:str]
    FLARESOLVERR_URL: ENC[AES256_GCM,data:Bfoy86REDqy1CXj0rRzcGa20SjCjDiKB,iv:mXqnz7ckeDfJ+q/wuUDO6ctig0TeQSpT0LMP7JUk5Fo=,tag:1kzE6LU6PS1JYtLMp/Pmhg==,type:str]
    #ENC[AES256_GCM,data:hDtUIdRvoxW0edfXN69D+F6wZZQT92HxZFgpQY7Nog==,iv:26IocSqEn9wczqVVCOiXvC1cFslY317OautQNFjUa88=,tag:tDTw/55EGzMQRKRYgwsR2g==,type:comment]
    #ENC[AES256_GCM,data:IDQ7iVDT8CjspVbJffTdSLB7v80t7QjqYLUM5URcdYM0pQ==,iv:21y1I5OR6qOiDDS3oia6kPyygvgNjYOAJplcBaXXBlM=,tag:aKSdYbvFdzXy4YCTJ3RKbg==,type:comment]
    #ENC[AES256_GCM,data:VYTb1wgJpairtIJg0tMmyEZW8OFTVKdoB82qRWSpQZ2xUOTJ,iv:7AGt8l3ca7FRdmF24xXuXJT5ZXuNi0Haa+0L3CAvesM=,tag:TvC8yfAMH65eyyrlbLp35Q==,type:comment]
    #ENC[AES256_GCM,data:44qcRmEmTG4vDpeIpg3urXy/yo3FWRkoa4AbFUo=,iv:dHZKIwVhdSUNF3LOYIBU7n0PmGxH2aCOr0Lbo/Frol4=,tag:a6U4OWswLMjobNszUogo7w==,type:comment]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVTVMd21pY1RSOWQySkwr
            Vkk5d21IYnVyVVRIWG03eW44OVhIZE1rb21nCldEbk80UEl4allNS0Ivc1pYRUhx
            d211WGM2YkVqTm5NUHJDRlVpa2R2UU0KLS0tIEhTRHBlT0doMUNsak5OQ2lxa2Va
            OWVCYmN1eG90QjE3RUQ2L2xyaFc4M1EKq8rOtTdIcrsJo5ucnDSHRoJgRuzm0S/W
            9kQdDxxVY6AQSTHUaxPA3Z9gq2xk32ASiYs48riOIZBvwZ1+/5Kcvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T20:00:19Z"
    mac: ENC[AES256_GCM,data:u4eaE/UUDpaCFOwuS1vCy5o7hkpZ0qf2vKpirRZU4mrtKB3CPsOXqY9P3ciqXHnO7fyFsj6bH6aK3QNOmaCNL+f8XQHTWo7rdbRT4ggzIxl/QpStUKiVUlmvxSOPbhfrcZjbIjDkgs+na/niSxW46wxMrgafNAfatEMW3QsP698=,iv:oaGwd3VjACPEuWhim9PJeZ6AkqixGqZeKo9sWS1Y6OM=,tag:ifMovmfP2SJnqje/ayBdmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
