apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: qbittorrent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: qbittorrent-config
---
