apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco-operator
  namespace: system-addon
spec:
  releaseName: falco-operator
  interval: 1h
  chart:
    spec:
      chart: falco-operator
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    excludedLabels:
      - kustomize.toolkit.fluxcd.io/name
      - kustomize.toolkit.fluxcd.io/namespace
    image:
      pullPolicy: Always
