apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: system-addon
spec:
  interval: 15m
  timeout: 5m

  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m

  releaseName: metallb

  install:
    crds: Create

  values:
    controller:
      podAnnotations:
        uptime-kuma.io/enabled: "true"
        uptime-kuma.io/type: "tcp"
        uptime-kuma.io/url: "metallb-webhook-service.system-addon.svc"
        uptime-kuma.io/port: "443"
        uptime-kuma.io/name: "metallb-controller"
        uptime-kuma.io/interval: "60"
        uptime-kuma.io/retries: "3"
        uptime-kuma.io/notifications: "Monitoring Bot"
        uptime-kuma.io/group: "Network & Connectivity"

    speaker:
      podAnnotations:
        uptime-kuma.io/enabled: "true"
        uptime-kuma.io/type: "tcp"
        uptime-kuma.io/url: "metallb-webhook-service.system-addon.svc"
        uptime-kuma.io/port: "443"
        uptime-kuma.io/name: "metallb-frr"
        uptime-kuma.io/interval: "60"
        uptime-kuma.io/retries: "3"
        uptime-kuma.io/notifications: "Monitoring Bot"
        uptime-kuma.io/group: "Network & Connectivity"