apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: system-addon
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      version: "0.15.3"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m
  releaseName: metallb
  install:
    crds: Create
