---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
  namespace: home-automation
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: homebridge-pv
