apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-mariadb-config
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: grimmory-mariadb-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-data
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: grimmory-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-books
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: grimmory-books

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-bookdrop
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: grimmory-bookdrop

---
