apiVersion: v1
kind: Secret
metadata:
    name: grimmory-db-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:aajFcBNFAuZ2Lo9DIsYJrW8=,iv:o3ZFD1Cyq0vZbPtSc9GXbXP0/ctGPIdFoOX5dR5iikc=,tag:J+ST6o0FgzRPFImC/NOpqw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:Lphf2sPT9uE=,iv:U3G0VwCHZ3LPZ5UXWPpzGcTPyslGvMzL6I88fpBPGPg=,tag:gg0oTBO/DgH1v+PEp+j2EA==,type:str]
    DB_USER: ENC[AES256_GCM,data:ilgah8mG0Kw=,iv:DeLjHssxXAgBZHFe4MUJrKJ95G7n/9tDgPQ4Teivd/4=,tag:0jESla551bHq1LnudT2D2g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Xak8I3FwO3Qk1cxpfkIn64c=,iv:MV9X+/8EcddKd0vSQjhrf7BRZtYDNLFfuuGo40LQuvk=,tag:53cQoa/Z58ugQvoS8g81Qg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oh42bgzcFW8IjwC9QOACVszkAqBBWsf5CPQ6co0fqqJa3oijAq/5dFH8yjMg6uD8ta3az71kM8ATJGgpmp4B,iv:XUKdCu4EzlH1wmBT/P9ONMwps842P55qxyXNXHrvLYM=,tag:gOg8VReQJN6eI7zLT0b5Tg==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:ux2PHstXick=,iv:LXcc8SCUSmhupZzK6tGyf9nJvfcTB7P7ozmrEhBtNAU=,tag:YP66a2Jxnc+NUgW5W2pukw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:x7nw/kXWm+yJxZBFjOX6sko=,iv:90P3xeTA2k1L3Tzj4ecmkqlTzZXNADqJRTviNqh8fSI=,tag:HCHq8QAvWozK2FPUeblhXw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:VEVeg6MufnmTS8gBM5KTPDz/fyzn14HiqXHiw+AbRSFp/w==,iv:1vl3B8jLSmiJDlXhgKZjSS9gng3dZwUOQkYvIhPK6XA=,tag:0DB7o0mcnXpixtuYJgHJeA==,type:str]
    PUID: ENC[AES256_GCM,data:Y6rQkw==,iv:nDH9m2SK81daAnq3CVMgcSNyRct9iIbrL7FDpOoFv08=,tag:NZoNksj06gS3tQsuJ5FnKg==,type:str]
    PGID: ENC[AES256_GCM,data:+v8/NA==,iv:cXkUNZ/1/fFxtIDqiraJoo4y65qB5DSdreGocySOuyw=,tag:sNaYdXa8ru4hnsLPRXS7qw==,type:str]
    USER_ID: ENC[AES256_GCM,data:m/1IGg==,iv:stO0d5GzP1CmluWM1F/t2MboFMaqTw0jdu0kRlL/DhE=,tag:w2VfIF/QhTh5a0WwbEAUhA==,type:str]
    TZ: ENC[AES256_GCM,data:pyQXbiogsA==,iv:+j7FBw1QKoYrTvV4vQL96G1RdxcYl1fTNHc9xMh6HIo=,tag:ScZ0B/FkDpj7cyzAy5YLzg==,type:str]
    DISK_TYPE: ENC[AES256_GCM,data:tGcYFZk=,iv:BrGDbN6IW0fuiFxHddYdDrxTRzwNmlR2afw4MWVT+BE=,tag:58fl+AHa/t6285UQqC1TJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eEplUlk0ci9vSGt1cXJS
            SUdHQURwdm83ZEtHQU5MS1JGUmI5NHVTc2dvCktPSkttMGhIamx4dzBwOUY4WUJl
            UGJ5UEEyc09WNm50elFqOUtsL1cwVmMKLS0tIGtLaUNkeFZYT2tJOTFxRzVDNlNp
            Z1QrbUJFVHR2aU5meWdOdnNjUkUrc2cKtTyNTmFnUPCr7TS2+BQ15oNa0PM/iisZ
            Fcwg4O5LcxZPEri6Tt1OdKwVP8e80d08cj7v5xnabuTcoGADtpGQ1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T14:53:09Z"
    mac: ENC[AES256_GCM,data:6/G/Y9d/xR8DPDd8QpRVRscpC45hXXPXsc7lHt1Vi+5VflxlxSA3j/jpufJgSj9qeFrvreMs0J5dzb7JyKBXelrZP+fwiilMHhKBLmPPo3BsfFNFn3jD/XRZfipyC3ZJoUZtmmNJIk82hy+xMeP5c8rnOXDKumh98Ib5/FFSvmM=,iv:NFibD7p5Dhxfp8lYc/xDU3Ryuvy+oAA2eFrk1xdDPGo=,tag:5Q8NCEe7bfuZKb8a0nVkAA==,type:str]
    version: 3.13.3
