apiVersion: v1
kind: Secret
metadata:
    name: grimmory-db-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:aajFcBNFAuZ2Lo9DIsYJrW8=,iv:o3ZFD1Cyq0vZbPtSc9GXbXP0/ctGPIdFoOX5dR5iikc=,tag:J+ST6o0FgzRPFImC/NOpqw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:Lphf2sPT9uE=,iv:U3G0VwCHZ3LPZ5UXWPpzGcTPyslGvMzL6I88fpBPGPg=,tag:gg0oTBO/DgH1v+PEp+j2EA==,type:str]
    DB_USER: ENC[AES256_GCM,data:ilgah8mG0Kw=,iv:DeLjHssxXAgBZHFe4MUJrKJ95G7n/9tDgPQ4Teivd/4=,tag:0jESla551bHq1LnudT2D2g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Xak8I3FwO3Qk1cxpfkIn64c=,iv:MV9X+/8EcddKd0vSQjhrf7BRZtYDNLFfuuGo40LQuvk=,tag:53cQoa/Z58ugQvoS8g81Qg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VnIijsr2kJYCiBpOgb4i2l4zmu5BpFRCqmPpI4QgNxR09WrvNIo6pg==,iv:AP3NRM/r8fkGAhjoEO14mjbtigzE+Wyy4nwxvktiULE=,tag:rj390/MTvQIcTZs5Fkk0zw==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:ux2PHstXick=,iv:LXcc8SCUSmhupZzK6tGyf9nJvfcTB7P7ozmrEhBtNAU=,tag:YP66a2Jxnc+NUgW5W2pukw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:x7nw/kXWm+yJxZBFjOX6sko=,iv:90P3xeTA2k1L3Tzj4ecmkqlTzZXNADqJRTviNqh8fSI=,tag:HCHq8QAvWozK2FPUeblhXw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:m3D3UIcgsIol/Qg=,iv:iE7Di6fkL98NqUrzAHgQq27YyColF8K0p2Rqn6YiEEk=,tag:w65aSe1xKDy40Y0GVnOcvQ==,type:str]
    PUID: ENC[AES256_GCM,data:Y6rQkw==,iv:nDH9m2SK81daAnq3CVMgcSNyRct9iIbrL7FDpOoFv08=,tag:NZoNksj06gS3tQsuJ5FnKg==,type:str]
    PGID: ENC[AES256_GCM,data:+v8/NA==,iv:cXkUNZ/1/fFxtIDqiraJoo4y65qB5DSdreGocySOuyw=,tag:sNaYdXa8ru4hnsLPRXS7qw==,type:str]
    USER_ID: ENC[AES256_GCM,data:m/1IGg==,iv:stO0d5GzP1CmluWM1F/t2MboFMaqTw0jdu0kRlL/DhE=,tag:w2VfIF/QhTh5a0WwbEAUhA==,type:str]
    TZ: ENC[AES256_GCM,data:pyQXbiogsA==,iv:+j7FBw1QKoYrTvV4vQL96G1RdxcYl1fTNHc9xMh6HIo=,tag:ScZ0B/FkDpj7cyzAy5YLzg==,type:str]
    DISK_TYPE: ENC[AES256_GCM,data:tGcYFZk=,iv:BrGDbN6IW0fuiFxHddYdDrxTRzwNmlR2afw4MWVT+BE=,tag:58fl+AHa/t6285UQqC1TJA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eEplUlk0ci9vSGt1cXJS
            SUdHQURwdm83ZEtHQU5MS1JGUmI5NHVTc2dvCktPSkttMGhIamx4dzBwOUY4WUJl
            UGJ5UEEyc09WNm50elFqOUtsL1cwVmMKLS0tIGtLaUNkeFZYT2tJOTFxRzVDNlNp
            Z1QrbUJFVHR2aU5meWdOdnNjUkUrc2cKtTyNTmFnUPCr7TS2+BQ15oNa0PM/iisZ
            Fcwg4O5LcxZPEri6Tt1OdKwVP8e80d08cj7v5xnabuTcoGADtpGQ1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T19:22:05Z"
    mac: ENC[AES256_GCM,data:/IhkZjKLdldLPfPNtGTYNzYWzEn9B61OfdslyrxH90htBXa/TGO5ZkdcalODaaiHmxKauauuZUHPwjfg/9Zh0o2qZh5wh3lrTBWmhKHra7rg2Ta4a3hP96PtVr96jYmMuOzIqA3IiwuppDCjm5E7s5xrlaZqcN/0jYOvb2dELWg=,iv:RrF4enr7P4nSkOUsNrF+5hzgxGYZ15hUHg5zJ+JKCxI=,tag:wN4TxVXhp/dj0ZVL1mWGkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
