apiVersion: v1
kind: Secret
metadata:
    name: ollama-secrets
    namespace: extra-tools
type: Opaque
stringData:
    OLLAMA_BASE_URLS: ENC[AES256_GCM,data:MdOX0kj2eWW50MXjQ2g85l/zfTZ2fEqaswPm8d/jo1XXzLH6CwEZ,iv:E0JHeBeMIa8qWhYNMNXVrESJbnHxZCQ2rgQpmCtO5lA=,tag:RggDRwZlC4d0pggDz9LVbA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WXVNUVR3cEd4UjZ6Mlcv
            N24vdFJyakpPTC9xMU1RTHhDdTltUm55WkI4CndFSWFteFFKOVBRY3g5LzYwcE9q
            MVVmMTlldkg5QWE3NEI3cW41WDJvWGsKLS0tIExhRlZQSnQvV0lpdU9FT2hPY3dj
            c0UvcW1QdVcrR25xUGdja1VFblB6eDQKI3IHnVVnrnlfHcYjt1Nvt+pCuojUVDsu
            AcYt+xfm1id1G3v439eFyqmhMOpYBeJQcWyrxIllfSy9dZ2W5/kYEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T07:19:18Z"
    mac: ENC[AES256_GCM,data:h99YPvY7d0AcsnKagryf2H1/xOjnHsGWl+nxRFSuwmz48an20dAs1W3pr3xTpqnpbAZ7cRjd/nHgq9+vHKUkpliCRGXufWHSsIem2GjqjjeTajoJv0zB3BYbyko0wWw3vbb0XnX0Hetnq/4wJCLwIQFw/6chs+vdX+gQ7RdVdj8=,iv:Ze20vE+ocjseACx4UzOkDD5rUF+X560z3Le0Tnr5fvo=,tag:2RKIFYJMurEoygm0lE1EHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
