apiVersion: v1
kind: Secret
metadata:
    name: metoro-exporter-secret
    namespace: system-addon
type: Opaque
stringData:
    AUTH_TOKEN: ENC[AES256_GCM,data:QNda9MeHlOkE9Xb636QDwxGSibsgnZlHzDFisOYu2fdaKcFJMMTkEFwVrR0Dtd2dZlTEP+f7BXwTochSbuBSeDpGhYS1Z/THhSjSItiHozJpJXuyfYbey4WU8YF9BGpR3B+tP7SiIe0prKyFSiDm2z0DuCDU2r/kz0gKF3c4lCKRT7RK/ZmvKVWuziYK1S3tsKITlPJaSHNMGocp11o7fBzbZa4nyM5o3nEylMk/3JSLJRk/lYp0m+fbfp7h6H4d8Hpi,iv:3I0Fr94IJd0h3GMRCIKr45Y3EG6gY815tsu2IB7nCZA=,tag:HnLx6CsHevxDh06Jbu/Gqg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:5bdvOFkPFqboxfNyhLHVr4PERYnH,iv:MW3LQVbKuY06dF+ad1oiV1L4trPVGfw1ie6WRRL5+5g=,tag:Fre1RsSwsQhntxGEzAkmUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNTZwR2dQdlV1ZWluY0NP
            c0lKa05DNjBnMHhHQm5PV3hZMFo1dEF5c0JRCjJ2YWxSVkN4NVBZYnFCa2diTTRO
            NFloeHIwNFYybUlFVzZvdlBnSktNMG8KLS0tIFRtODJCS2M5RjRpenRkbzRmU3BE
            b0RuZzU3VzNRWjg1YUxyQzBGTWhHN3cKmwNmBNQkPzd7o1HZu1UEGlJG/HEiNQmG
            /J0q7zNJ9o38wmUzC9Kl/CR+l3mgsQ+1QqxHQsaSntSMeVdPJN4cYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T13:02:32Z"
    mac: ENC[AES256_GCM,data:k/dRlgHFDa5OSzxLIRPlXO1g9geAogCeW9DjVXsDmJH3oScMgWgsSh9GIQd8jatPmgaXqz/x4aLgjBw61WS2nlGrx5afx9SyxIs9ZutVqwtrqyJU0qKV22hYYHLfvtipwJEampwhEUZO/CSpB6RJmXeWSHNd33B2QqeBAaDLKl4=,iv:d5jKhgJoX8vr5jc9qxzfpsjpjPgFos0M9wo8zRMMdfY=,tag:M8kNaDmTqouL1YG+FkMRJA==,type:str]
    version: 3.13.3
