apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-config
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/kavita/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-data
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/kavita/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
