apiVersion: v1
kind: Secret
metadata:
    name: keel-secret
    namespace: system-addon
type: Opaque
stringData:
    BASIC_AUTH_USER: ENC[AES256_GCM,data:HJI2T7fA5v67AQ==,iv:wcayb5g/NMhuoPmPg0wwsw1FGIz72H1riiSU5RkwpIQ=,tag:MwdjjQPR7pX6Lzows5ptFQ==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:OE7QVpNHUdlSmAFAMumFQF+uBI8=,iv:IzZVqStKm4CF4Vkurj6lqsHpfyEXXqzvq/rAyQfPSBs=,tag:NbgQCGjd/Vlev7vlGRZgCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNTZwR2dQdlV1ZWluY0NP
            c0lKa05DNjBnMHhHQm5PV3hZMFo1dEF5c0JRCjJ2YWxSVkN4NVBZYnFCa2diTTRO
            NFloeHIwNFYybUlFVzZvdlBnSktNMG8KLS0tIFRtODJCS2M5RjRpenRkbzRmU3BE
            b0RuZzU3VzNRWjg1YUxyQzBGTWhHN3cKmwNmBNQkPzd7o1HZu1UEGlJG/HEiNQmG
            /J0q7zNJ9o38wmUzC9Kl/CR+l3mgsQ+1QqxHQsaSntSMeVdPJN4cYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T16:53:04Z"
    mac: ENC[AES256_GCM,data:TmBku9dlJexY87NH8/IxWcEB8Pblg7VknFFviS4KRIPT9NYI35bdbav7H3wTbohBSMmmNd0GSmR8IWJ+Tfw5Cd1WNkRnLwwstbSJap+oG2G2crX5prMOFOq6eBtywRJI+6yN4oBAnz20Eh/4qGVRW0HfhrRBDJjR3rFIikM9nso=,iv:FSCA0JqinjRCLJaGwXhC/a/3iWGw1b6zESo16xEDcYw=,tag:3MEoecFAF3jgsGMO5+gmeg==,type:str]
    version: 3.13.2
