apiVersion: v1
kind: Secret
metadata:
    name: keel-secret
    namespace: system-addon
type: Opaque
stringData:
    BASIC_AUTH_USER: ENC[AES256_GCM,data:HJI2T7fA5v67AQ==,iv:wcayb5g/NMhuoPmPg0wwsw1FGIz72H1riiSU5RkwpIQ=,tag:MwdjjQPR7pX6Lzows5ptFQ==,type:str]
    BASIC_AUTH_PASS: ENC[AES256_GCM,data:i7C1L5S4r7ZpoQuj/TnspySDACQ=,iv:pDUODM7MNHu2WtFetOBbXmR6+uFJmY7cbOERw0F1ric=,tag:EXckFen4l97PCwbdaHV7eQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNTZwR2dQdlV1ZWluY0NP
            c0lKa05DNjBnMHhHQm5PV3hZMFo1dEF5c0JRCjJ2YWxSVkN4NVBZYnFCa2diTTRO
            NFloeHIwNFYybUlFVzZvdlBnSktNMG8KLS0tIFRtODJCS2M5RjRpenRkbzRmU3BE
            b0RuZzU3VzNRWjg1YUxyQzBGTWhHN3cKmwNmBNQkPzd7o1HZu1UEGlJG/HEiNQmG
            /J0q7zNJ9o38wmUzC9Kl/CR+l3mgsQ+1QqxHQsaSntSMeVdPJN4cYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T16:46:24Z"
    mac: ENC[AES256_GCM,data:qIIHrPzf2l5nbfvvH2CQDK3dhNJQjYzHcnfnklVzQKMevrT+jInx1trByWk8lM00M9Q2BxIFXvBN6sOmtitGII+nUIymh9C8iqY3W7VRyZTa6eC370fn7YXrlnMHKTMOTX6PN77dzw5DvDHZvIamauuiK2HgU9ObdDz+mriRZeQ=,iv:kauCHNJBKBClyEYsKPQnIlAbsEp7rC3k2rajKqeuQx8=,tag:iBM+TO8fLSVQG+bpgmbiLQ==,type:str]
    version: 3.13.2
