apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: multimedia-factory
  labels:
    app: prowlarr
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/matchTag: "true"
    uptime-kuma.io/enabled: "true"
    uptime-kuma.io/type: "http"
    uptime-kuma.io/url: "http://prowlarr.multimedia-factory.svc:9696"
    uptime-kuma.io/name: "prowlarr"
    uptime-kuma.io/interval: "60"
    uptime-kuma.io/retries: "3"
    uptime-kuma.io/notifications: "Monitoring Bot"
    uptime-kuma.io/group: "Media Acquisition"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9696
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: UMASK
          value: '002'
        - name: TZ
          value: Etc/UTC
        volumeMounts:
        - mountPath: /config
          name: prowlarr-config
      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName: prowlarr-config
