apiVersion: v1
kind: Secret
metadata:
    name: wireguard-proxy-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:tFB7EsD8PWOdp4zXlEPrqLkUXyGAq8DNsxlUukXz5uYsXozy2sOWquH5vRw6d0dGt3AYbdv0dsUyXGY7xY+22FuwavwJFtHm7614iM0IY+sKXhC3EELVMjg1LN/4R9ctra4VDreHP17tdH/EIlEjzmEIQSLMvjmGIw8PhikI2sifueKHI716AeLfMVMeQRwRb6VrDpU0cnUz6SV4V5aSRxzAYp6qdPEs1KDqgxVUeVgNjWFiys/3wXy8zeDe841vKlVF4ZsJNFzGg0BETGANL6Dtq1LSEN2Z45HwqmJxYg3j367CEnhiO4JDXciWELOv0vw9n+qia2PaJo6b5iRwY7CcY2YukpQxK0k8fiIlUE5cnN0NKcgaFaEozF97+lzTqtA5iA3+ZUJpnBqIiIeU7jzeYOP0AfXid7ozv8w=,iv:RUA41+/1SXQ0eJCU4Hn06y2OSMQTLhptg6fPP3v+BEg=,tag:vtNX5hX+ECETyzwqST1UJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2c2eHliTDN0UUxENGt3
            NjE1dzNaRVo5ZHZqNkszYXBXWHJ0eTBjWjJBCjFUNXNmTktGeW5qM01SNSt1cS9M
            eUtmUVZwWWN4OVFIRjNzbVhNcTV5V1EKLS0tIDZraUZhZUJoQ2lWY3F0RVN5eWxP
            Mi8yUjZpZnFRUUdYSTcxRWVhNGx4cUkKPoe2vqH9PcSl8i7NsomlUA/ktA7ZLtQn
            XNaUvZn5n0cboU+LYeJA+yDFyuQfzerzFweGbrC5ZgyRDPB0XA4eow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T07:43:59Z"
    mac: ENC[AES256_GCM,data:qtzAKU3OOORFYiYkJ/iSBQmZhGAoGGxWPbvQ26bi3jkolcZr2KBbuWwR67JgGS1y15BEQS1hzP3F1ZlYbH7ZeWoepn/fWdjEr185EvLGBNQu15HKmMKKWz9BAsF1EbxE8ili3vaPeHSo90I09h+Sfm1pa/ptm1UUkDw0C8a9VaY=,iv:xMezC/ORG4/uB+3bWDofmlHVi/ddy71Fvk04r/i+EsU=,tag:V3A8Mm7z/iqCkGC7WnmA2w==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-options
    namespace: multimedia-factory
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:AQxMTdZWhZ8I,iv:BHzlLGbgIeP6UDPmVXr+MOLUoc+tBurm1q7E7ZiSCTA=,tag:xLYpFbnZ7VMMtH4ByZtCPg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:WwsSs+mjJxgBru9KZA==,iv:nYFH6OaPBbx8ZuKH5PcqnFkDh/n+z8jkbDDMdK1yK+E=,tag:8xj1/SgF0FN9qqoLSoDbiQ==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:KeMOIpoO,iv:BNvRqrr0Psn860LfMFSUabfhaf5EYf8/hYm8d84Dlxs=,tag:ijw6C+ZDC9Pe1Qr0YlLkaQ==,type:str]
    SHADOWSOCKS: ENC[AES256_GCM,data:xCku,iv:X8FW+1iNBZYnTQya8PyZzslP/gRBzOX+hZ1hVHtGphw=,tag:AcCdLKUlwCN300hg50IAeg==,type:str]
    HTTPPROXY: ENC[AES256_GCM,data:jvVx,iv:L/+yrlNcF9p6oNFgmn9+skqzj9BV5WlYdjyUxGUxHgA=,tag:9Lki2VvFrLr/6jgz9Hm6Gg==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:lKvnzcUnTF9B2JIh6/9IWHPFlx6XVDFxPA==,iv:1rHYqZNCHdgaCI04lbDw9ANAxi/rSf43FgGWvkXqXDg=,tag:fdHdmDmpu3yURtYvHzRkaQ==,type:str]
    DNS_KEEP_NAMESERVERS: ENC[AES256_GCM,data:kOI=,iv:hl4mJqW9nos+Y8mYF+/2Zg7VdMahOC4RdLlrC+wZmBw=,tag:ZRIeqOqFiOvVi5n6AFx0vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2c2eHliTDN0UUxENGt3
            NjE1dzNaRVo5ZHZqNkszYXBXWHJ0eTBjWjJBCjFUNXNmTktGeW5qM01SNSt1cS9M
            eUtmUVZwWWN4OVFIRjNzbVhNcTV5V1EKLS0tIDZraUZhZUJoQ2lWY3F0RVN5eWxP
            Mi8yUjZpZnFRUUdYSTcxRWVhNGx4cUkKPoe2vqH9PcSl8i7NsomlUA/ktA7ZLtQn
            XNaUvZn5n0cboU+LYeJA+yDFyuQfzerzFweGbrC5ZgyRDPB0XA4eow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T07:43:59Z"
    mac: ENC[AES256_GCM,data:qtzAKU3OOORFYiYkJ/iSBQmZhGAoGGxWPbvQ26bi3jkolcZr2KBbuWwR67JgGS1y15BEQS1hzP3F1ZlYbH7ZeWoepn/fWdjEr185EvLGBNQu15HKmMKKWz9BAsF1EbxE8ili3vaPeHSo90I09h+Sfm1pa/ptm1UUkDw0C8a9VaY=,iv:xMezC/ORG4/uB+3bWDofmlHVi/ddy71Fvk04r/i+EsU=,tag:V3A8Mm7z/iqCkGC7WnmA2w==,type:str]
    version: 3.13.2
