apiVersion: v1
kind: Secret
metadata:
    name: wireguard-proxy-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:VVDAUXV8+XNjknR+0upnjJ/kisanq5vFPTTYqQ2OGhk7e77cWN5a4J3ekHayt0rxoeVXlQgPhxjFxGV3eDuKxAKhD3IsPYcacmtoDBpBY6XmuWhvORUVEJXmn6u6CjRsvkN5iDTsBvm64rk0XqpT2uBwrsA6fBfYACaxbs/WdIeNe1xHW78978bk7zNC2VhLjLBGLROCu5zhTRq9VDSMPnYtWszS0vVruejRwPky2Sbf1TfdW7yZgh3w7MAVIZCPPFXB04vE0peBmZrYCD0NSlG+hdZFAweuVOsx6hNylyiuek1yYUkzbkOGc1/jrN8bgElMPEeVbBVGMSTDeBBoM1csm0es+xFeEL1qT07t1osxIpBXsdp0cVkIBoEQOxZRh9JnAdNI3X/twUcHYKIn85HL3D9k5Drk8JrjYce5WQ==,iv:kZnrIkq9x4+sw7ZAUSl9JSdiKe8RycxeI1mwV5WSoz8=,tag:P2dcJGck2fSRzfcx0tfJxQ==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2c2eHliTDN0UUxENGt3
            NjE1dzNaRVo5ZHZqNkszYXBXWHJ0eTBjWjJBCjFUNXNmTktGeW5qM01SNSt1cS9M
            eUtmUVZwWWN4OVFIRjNzbVhNcTV5V1EKLS0tIDZraUZhZUJoQ2lWY3F0RVN5eWxP
            Mi8yUjZpZnFRUUdYSTcxRWVhNGx4cUkKPoe2vqH9PcSl8i7NsomlUA/ktA7ZLtQn
            XNaUvZn5n0cboU+LYeJA+yDFyuQfzerzFweGbrC5ZgyRDPB0XA4eow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T12:22:53Z"
    mac: ENC[AES256_GCM,data:P76+NruquUf6X1mZdV10lY8RJET2G5bp9+NgHn8ZREU8nvJJxOcgG2ptxoylJk6iwZVkboeFE24Paelz/a0XKbnN7tJrG9kxjnJvdiS7vl8iawNGchGhNWHQ72Cf5aqWBQkX70UN7d0hw7SgCnd9fYMK75qYTjQIAUkbVELXAAQ=,iv:5BRoCUTPghud6a/K7jfOj+IoAJboDZ8M7VuwT68Z878=,tag:Shqulok7R+f6+GOaTWqkVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-options
    namespace: multimedia-factory
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:AQxMTdZWhZ8I,iv:BHzlLGbgIeP6UDPmVXr+MOLUoc+tBurm1q7E7ZiSCTA=,tag:xLYpFbnZ7VMMtH4ByZtCPg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:4H0g1W3/fUQNjNtsrvQ=,iv:ORnDQb9AF9vG2Cdrom432y+uD5b0F3NzxII3WGzTsaY=,tag:hdUkj4k9Z2JqEkneRHWObA==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:KeMOIpoO,iv:BNvRqrr0Psn860LfMFSUabfhaf5EYf8/hYm8d84Dlxs=,tag:ijw6C+ZDC9Pe1Qr0YlLkaQ==,type:str]
    SHADOWSOCKS: ENC[AES256_GCM,data:xCku,iv:X8FW+1iNBZYnTQya8PyZzslP/gRBzOX+hZ1hVHtGphw=,tag:AcCdLKUlwCN300hg50IAeg==,type:str]
    HTTPPROXY: ENC[AES256_GCM,data:fL0=,iv:SCVTM5qX0IsoFF109gOFCb2Xez0+LqtO1EQQDy62Tx8=,tag:pEhqMIVUNeb+xnSawXSFsA==,type:str]
    HTTPPROXY_USER: ENC[AES256_GCM,data:q9pp4qU=,iv:dsC+z9T35xG5ABIY2xrH6skJc0BpSAjaHMzFhI9Jctw=,tag:OKLGzlo47K/Sv8S6mKsT3Q==,type:str]
    HTTPPROXY_PASSWORD: ENC[AES256_GCM,data:BHNmA3c=,iv:gfAsqRwdgI9TQoXe2GjTz9FmOrl+ykXWGJWHTRSoApE=,tag:HxA1kIjg7WwIZwqIgn1Neg==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:lKvnzcUnTF9B2JIh6/9IWHPFlx6XVDFxPA==,iv:1rHYqZNCHdgaCI04lbDw9ANAxi/rSf43FgGWvkXqXDg=,tag:fdHdmDmpu3yURtYvHzRkaQ==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:tiZMGUw=,iv:BJ7NFVl27OrHbTAFw62HSG/HyhOi3uQgpjiyaYrg7TE=,tag:KAhNAA54hH5jc2z+DBP7YQ==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2c2eHliTDN0UUxENGt3
            NjE1dzNaRVo5ZHZqNkszYXBXWHJ0eTBjWjJBCjFUNXNmTktGeW5qM01SNSt1cS9M
            eUtmUVZwWWN4OVFIRjNzbVhNcTV5V1EKLS0tIDZraUZhZUJoQ2lWY3F0RVN5eWxP
            Mi8yUjZpZnFRUUdYSTcxRWVhNGx4cUkKPoe2vqH9PcSl8i7NsomlUA/ktA7ZLtQn
            XNaUvZn5n0cboU+LYeJA+yDFyuQfzerzFweGbrC5ZgyRDPB0XA4eow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T12:22:53Z"
    mac: ENC[AES256_GCM,data:P76+NruquUf6X1mZdV10lY8RJET2G5bp9+NgHn8ZREU8nvJJxOcgG2ptxoylJk6iwZVkboeFE24Paelz/a0XKbnN7tJrG9kxjnJvdiS7vl8iawNGchGhNWHQ72Cf5aqWBQkX70UN7d0hw7SgCnd9fYMK75qYTjQIAUkbVELXAAQ=,iv:5BRoCUTPghud6a/K7jfOj+IoAJboDZ8M7VuwT68Z878=,tag:Shqulok7R+f6+GOaTWqkVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
