apiVersion: v1
kind: Secret
metadata:
    name: wireguard-proxy-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:qBYwIcMZzAfrDJ6fcV9WVnUgLwHe8JUsmjHv90Y9bjuivY4y4aBhnhZjoFlH8VNj+/9nDZ6sWVGj8vyvqta9qWC61vBOWO/OOY17uMCrpRs9b/YzeHugScU1aq1vEQi8kioisFn615g3FPnzm6u8GRsAchpTNrO/YFaUnUeBCo1MUtwhlXlr0abcLBX1+TewoEB5AhpthD3SxfOjleVrG0gD7PI1XYnZnDBfBxeS8ROqcoDV8gCjM6WHC6hx0ehwvy2EA9URImcAwWjLc4j3X6nNrfS5295RCpxDt00wSRP0DAka20Esaz4C7Qia0DriCOrPrBrIV1mq60epi2qrUH/XyAbWC6hANd5Nn1pNFEQyxKWBFyGLtr0FaZDKeZDa58LEAqRhYjqG0+dXzubD3JoLZz8SVfWluE6AzGA=,iv:9Vstiy/+PxBmwfdj7Pf6k/gKU/QiNb0KXK4UbqG5KX4=,tag:ZzNqxwLtyVIcBjoVNYWu+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2c2eHliTDN0UUxENGt3
            NjE1dzNaRVo5ZHZqNkszYXBXWHJ0eTBjWjJBCjFUNXNmTktGeW5qM01SNSt1cS9M
            eUtmUVZwWWN4OVFIRjNzbVhNcTV5V1EKLS0tIDZraUZhZUJoQ2lWY3F0RVN5eWxP
            Mi8yUjZpZnFRUUdYSTcxRWVhNGx4cUkKPoe2vqH9PcSl8i7NsomlUA/ktA7ZLtQn
            XNaUvZn5n0cboU+LYeJA+yDFyuQfzerzFweGbrC5ZgyRDPB0XA4eow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T08:03:34Z"
    mac: ENC[AES256_GCM,data:1QmVfEls3PxSg0Mn9ArSKXHihFp71BSebbVw5dMpKkVYuNE62oUiVbCPu4o1kZG6b50SANHd2fRLYABP/zpZ2PigdyfzNNKS7SVj2dZpDuupByq4vuT5XX0Eq/GUA9NBMa95SdORrQK9wGL1eVYYrw67h41motqvHBQ3/3B1FLo=,iv:GA1uT6jSdjY+xQpMI2c+AxvVsNzBrKCk2u9SInyBf2k=,tag:pkwZr/VM1gnPDcG+f9KiiQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-options
    namespace: multimedia-factory
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:AQxMTdZWhZ8I,iv:BHzlLGbgIeP6UDPmVXr+MOLUoc+tBurm1q7E7ZiSCTA=,tag:xLYpFbnZ7VMMtH4ByZtCPg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:rnfn31vTp2K3KkHp2w==,iv:yZ70MCnFyVSsL/R5imxmV4+Ehj9IEBAE1345tMcug1o=,tag:yVn+EFHsBMTYu9cmb+Z6pA==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:KeMOIpoO,iv:BNvRqrr0Psn860LfMFSUabfhaf5EYf8/hYm8d84Dlxs=,tag:ijw6C+ZDC9Pe1Qr0YlLkaQ==,type:str]
    SHADOWSOCKS: ENC[AES256_GCM,data:xCku,iv:X8FW+1iNBZYnTQya8PyZzslP/gRBzOX+hZ1hVHtGphw=,tag:AcCdLKUlwCN300hg50IAeg==,type:str]
    HTTPPROXY: ENC[AES256_GCM,data:jvVx,iv:L/+yrlNcF9p6oNFgmn9+skqzj9BV5WlYdjyUxGUxHgA=,tag:9Lki2VvFrLr/6jgz9Hm6Gg==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:lKvnzcUnTF9B2JIh6/9IWHPFlx6XVDFxPA==,iv:1rHYqZNCHdgaCI04lbDw9ANAxi/rSf43FgGWvkXqXDg=,tag:fdHdmDmpu3yURtYvHzRkaQ==,type:str]
    DNS_KEEP_NAMESERVERS: ENC[AES256_GCM,data:kOI=,iv:hl4mJqW9nos+Y8mYF+/2Zg7VdMahOC4RdLlrC+wZmBw=,tag:ZRIeqOqFiOvVi5n6AFx0vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2c2eHliTDN0UUxENGt3
            NjE1dzNaRVo5ZHZqNkszYXBXWHJ0eTBjWjJBCjFUNXNmTktGeW5qM01SNSt1cS9M
            eUtmUVZwWWN4OVFIRjNzbVhNcTV5V1EKLS0tIDZraUZhZUJoQ2lWY3F0RVN5eWxP
            Mi8yUjZpZnFRUUdYSTcxRWVhNGx4cUkKPoe2vqH9PcSl8i7NsomlUA/ktA7ZLtQn
            XNaUvZn5n0cboU+LYeJA+yDFyuQfzerzFweGbrC5ZgyRDPB0XA4eow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T08:03:34Z"
    mac: ENC[AES256_GCM,data:1QmVfEls3PxSg0Mn9ArSKXHihFp71BSebbVw5dMpKkVYuNE62oUiVbCPu4o1kZG6b50SANHd2fRLYABP/zpZ2PigdyfzNNKS7SVj2dZpDuupByq4vuT5XX0Eq/GUA9NBMa95SdORrQK9wGL1eVYYrw67h41motqvHBQ3/3B1FLo=,iv:GA1uT6jSdjY+xQpMI2c+AxvVsNzBrKCk2u9SInyBf2k=,tag:pkwZr/VM1gnPDcG+f9KiiQ==,type:str]
    version: 3.13.2
