apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  name: falco-rules
  namespace: system-addon
  labels:
    app.kubernetes.io/managed-by: falco-operator
spec:
  ociArtifact:
    image:
      repository: falcosecurity/rules/falco-rules
      tag: latest
    registry:
      name: ghcr.io
  priority: 50
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  name: falco-local-rules
  namespace: system-addon
  labels:
    app.kubernetes.io/managed-by: falco-operator
spec:
  inlineRules:
    - macro: known_drop_and_execute_activities
      condition: >
        or (
          container.image.repository = "docker.io/dartsteven/nutify"
          and container.image.tag = "latest-amd64"
          and container.name = "nutify"
          and k8s.ns.name = "extra-tools"
          and user.uid = 0
          and proc.name = "upsc"
          and proc.exepath = "/usr/bin/upsc"
          and proc.pname = "python3"
          and proc.cwd = "/app/nutify/"
          and proc.cmdline in (
            "upsc ups@127.0.0.1",
            "upsc ups@localhost ups.status"
          )
        )
        or (
          container.image.repository = "docker.io/pihole/pihole"
          and container.image.tag = "latest"
          and container.name = "pihole"
          and k8s.ns.name = "extra-tools"
          and user.uid = 0
          and proc.name = "pihole-FTL"
          and proc.exepath = "/usr/bin/pihole-FTL"
          and proc.pname = "bash"
          and proc.sname = "start.sh"
          and proc.cwd = "/root/"
          and proc.cmdline startswith "pihole-FTL "
          and proc.tty = 0
        )
        or (
          container.image.repository = "ghcr.io/flaresolverr/flaresolverr"
          and container.image.tag = "latest"
          and container.name = "flaresolverr"
          and k8s.ns.name = "multimedia-factory"
          and user.uid = 1000
          and proc.name = "chromedriver"
          and proc.exepath = "/app/chromedriver"
          and proc.pname = "python"
          and proc.sname = "python"
          and proc.cwd = "/app/"
          and proc.cmdline startswith "chromedriver --port="
          and proc.tty = 0
        )
      override:
        condition: append
    - macro: user_known_stand_streams_redirect_activities
      condition: >
        or (
          container.image.repository = "ghcr.io/qdm12/gluetun"
          and container.image.tag = "latest"
          and container.name = "gluetun"
          and k8s.ns.name = "multimedia-factory"
          and user.uid = 0
          and proc.name = "ping"
          and proc.exepath = "/bin/busybox"
          and proc.cmdline startswith "ping -c 1 "
          and proc.tty = 0
        )
      override:
        condition: append
    - macro: user_known_contact_k8s_api_server_activities
      condition: >
        or (
          (
            container.image.repository = "ghcr.io/gethomepage/homepage"
            and container.image.tag = "latest"
            and container.name = "homepage"
            and k8s.ns.name = "multimedia-factory"
            and user.uid = 0
            and proc.exepath = "/usr/local/bin/node"
          )
          or (
            container.image.repository = "ghcr.io/mariadb-operator/mariadb-operator"
            and container.name in ("controller", "cert-controller")
            and k8s.ns.name = "database"
            and user.uid = 65532
            and proc.exepath = "/usr/bin/mariadb-operator"
          )
          or (
            container.image.repository = "ghcr.io/alexxanddr/update-unifi-pbr"
            and container.image.tag = "latest"
            and container.name = "sync"
            and k8s.ns.name = "system-addon"
            and user.uid = 65532
            and proc.exepath startswith "/usr/bin/python3"
            and proc.cmdline = "python3 -m app.main"
          )
          or (
            container.image.repository = "ghcr.io/alexxanddr/uptime-kuma-operator"
            and container.image.tag = "latest"
            and container.name = "operator"
            and k8s.ns.name = "extra-tools"
            and user.uid = 0
            and proc.name = "kopf"
            and proc.exepath startswith "/usr/local/bin/python3"
            and proc.cmdline = "kopf /usr/local/bin/kopf run --all-namespaces --standalone operator.py"
          )
        )
      override:
        condition: append
    - macro: postgres_running_cnpg
      condition: >
        or (
          container.image.repository = "ghcr.io/cloudnative-pg/postgresql"
          and container.name = "postgres"
          and k8s.ns.name = "database"
          and user.uid = 26
          and proc.name = "sh"
          and proc.exepath = "/usr/bin/dash"
          and proc.pname = "postgres"
          and proc.cmdline startswith
          "sh -c -- /controller/manager wal-archive --log-destination /controller/log/postgres.json pg_wal/"
        )
      override:
        condition: append
  priority: 60
