apiVersion: v1
kind: Secret
metadata:
    name: falcosidekick-ui
    namespace: system-addon
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:5oq6mjx72kN97YKnboa/hnXrdGFq,iv:HbU3DkPSM/qVufSJp2DJRqON8kDk5hJWI9Byh310818=,tag:BajLCuYZlu/dC1f+UaPqmQ==,type:str]
    ui-user: ENC[AES256_GCM,data:FA+N/MlBP/6UvmmmtVmOGRldvqrOJSCEBBQvPmcQp/3STZvi/Jk=,iv:/5LJl4oLdwpoSCP/D4Dv8qK2yF13E1/i0zsBXbkNqPI=,tag:b7w+kyL1idv2DWxCq/ICkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aEY0T1plMEt4ekhBK25o
            Z2FVQmJSa25kYXRaOUFLbm82dnVuKzk0ZW13Ck5aZ3ZuRW1uMm5sdmZOeE9ySHZR
            a2hIb1QrQzZ2Rm0yTFprRWpac3FYRG8KLS0tIERrWWxXUGZvSUJ4akh4RXhsdG1P
            M081cnk0aUpMUHN1Yml4WjBhaDhGaW8KxkSbDvCwkfbs6/pv8x0SO4vSy0TRA82m
            GDH+iTcW5KI5SZYosIGY/z/K5j+7jQQX1ttJS+YAfop0lQFTGwNCsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T18:03:00Z"
    mac: ENC[AES256_GCM,data:3tCe9db3fy1pS8PfQuL1yoRn2TB/0BZYwLKS2WewvTrROzjJZn9/WHmUDKH7U2RLuBQ/Y+oevC4wVkGV8L+OC8t4WxytCBusG9ZGOfg5hxyP1KGAhLlQpMxlW0Gk9SpT0SbmmJpSpDDyA0n+pH2MghnO7zukFouwJKu57QlNz5k=,iv:Jwiu2a2GSxWPMvlrjWSpeKTw4wpBHowuxgmTz1t5NDQ=,tag:B5ao0IrpyRgBe/wBA4QoHA==,type:str]
    version: 3.13.3
