apiVersion: v1
kind: Secret
metadata:
    name: falcosidekick-ui
    namespace: system-addon
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:5oq6mjx72kN97YKnboa/hnXrdGFq,iv:HbU3DkPSM/qVufSJp2DJRqON8kDk5hJWI9Byh310818=,tag:BajLCuYZlu/dC1f+UaPqmQ==,type:str]
    ui-user: ENC[AES256_GCM,data:FA+N/MlBP/6UvmmmtVmOGRldvqrOJSCEBBQvPmcQp/3STZvi/Jk=,iv:/5LJl4oLdwpoSCP/D4Dv8qK2yF13E1/i0zsBXbkNqPI=,tag:b7w+kyL1idv2DWxCq/ICkQ==,type:str]
    telegram-chat-id: ENC[AES256_GCM,data:mjNAUbOrhU0o,iv:wah/MIq6BnyIvgfMS6rvDMIUyEsRlKAjS8LU9bajMFQ=,tag:fPg/EpTqZL+Vuw7MMh4rFg==,type:str]
    telegram-token: ENC[AES256_GCM,data:iPTSauAk9IsYafcZZFJY7qirT8nJ2qecdMHVNj+py5o+KL71oGpD5Bp4B2kcig==,iv:2t3uZ17oKNhW6s7jXz4AsWyJM5pMN9n60otDDqjXuic=,tag:SeA3edRSCmEFFAPei+dOYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aEY0T1plMEt4ekhBK25o
            Z2FVQmJSa25kYXRaOUFLbm82dnVuKzk0ZW13Ck5aZ3ZuRW1uMm5sdmZOeE9ySHZR
            a2hIb1QrQzZ2Rm0yTFprRWpac3FYRG8KLS0tIERrWWxXUGZvSUJ4akh4RXhsdG1P
            M081cnk0aUpMUHN1Yml4WjBhaDhGaW8KxkSbDvCwkfbs6/pv8x0SO4vSy0TRA82m
            GDH+iTcW5KI5SZYosIGY/z/K5j+7jQQX1ttJS+YAfop0lQFTGwNCsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T09:44:51Z"
    mac: ENC[AES256_GCM,data:uHLkpmSn84+mL8Tns4zpgDg//NMjeEXoyOA4MmE908GNYRe2E2tKpUK2eGZ2L9iwyhcWaj75AsxvDXc4PENvN50QERZY6XgaWzdy2vBjiPo8QNXiZr9Mmj0fggROGgRtZBlHS4NyFuoHc1g1xcmn7yt2Zx5isjMVIolSalYz5/c=,iv:rD60R1cXXnXl+cC3Wkciyz67pzBNJCmgGHPCrRHvWDk=,tag:+yqlxWRinMrwPY3V1XP2lQ==,type:str]
    version: 3.13.3
