apiVersion: v1
kind: Secret
metadata:
    name: lingarr-secrets
    namespace: multimedia-factory
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:vwTuOqaWkmvhD3Ub+PkA,iv:Zu2gMVNOkY4+FdNUU4qwQG8C1G8DpK9VL0ltLrgGoYY=,tag:omlJSQiFnfXGU6W4vTnWAA==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:6/zmd4rzvdixE3bXuLMw,iv:AFO99yxT8GUpwoufSw+P1PyMG2WjE3kzAcdD1Cw9tPg=,tag:ZxfFVgFICTfD6m7X1V6iXA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNTZwR2dQdlV1ZWluY0NP
            c0lKa05DNjBnMHhHQm5PV3hZMFo1dEF5c0JRCjJ2YWxSVkN4NVBZYnFCa2diTTRO
            NFloeHIwNFYybUlFVzZvdlBnSktNMG8KLS0tIFRtODJCS2M5RjRpenRkbzRmU3BE
            b0RuZzU3VzNRWjg1YUxyQzBGTWhHN3cKmwNmBNQkPzd7o1HZu1UEGlJG/HEiNQmG
            /J0q7zNJ9o38wmUzC9Kl/CR+l3mgsQ+1QqxHQsaSntSMeVdPJN4cYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T22:32:41Z"
    mac: ENC[AES256_GCM,data:cRdaqAHrbyUFyP/yAB7nz7zkrRen1X1v2JunLUnAH+kRRRjg7RUFGb8CvhL2FK7t9iQaQm88C/B3QmBTqG/zYLwAL9KElYjjSrUXv6DqY4uexGBfebaabS6v/DlD3Js6zFHVvqEba+I2+Uaq8nnBVWM2RYDqhYSCyhoXCf5KM74=,iv:lg168QcQUGfyeeghh/chEFT+zzykWiqZKOvvDgSje0M=,tag:3AfAsDg10FofL0wq6B96fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
