apiVersion: v1
kind: Secret
metadata:
    name: lingarr-secrets
    namespace: multimedia-factory
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:DWu/6KQMdadsfeMOOW3y,iv:52khtuHE0a3CTu1L0bUeFwLp7UJ1c2aLSokIpCa0PEs=,tag:Gt5qMCPzZwFflfB+kSdkjQ==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:wDNrAi80nsnlT070t5vs,iv:7TlDC4oz7zA569D0umTYUHRFl93F2JXnMgoTEF+JPdQ=,tag:ly8Gtk/Xc6qOeLcSy6kaWw==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:2Udbyro=,iv:axoHsn8JrY9cVoT+OsAbaJeBT6A19hrens44Dkum6uI=,tag:3cbBAJxmCbzCqfuxdkzAjg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:WXDGhSYrvOAc01NC8rto0iQga3Ssa1VAL/Q3VGIPYDskpA==,iv:9Bvc6b5NaZ2EAxEkgCtJZphpogv0LsJW7b3rFbiDnRQ=,tag:ev/tPEjL5WLzB8uhkG9OdQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:L5m+uQ==,iv:xxbbzuDeD3rZTqdlBu13axUS4PBaSiXXv5sNZ7kY0Ec=,tag:zHErAxXRvtqf4sj8vQUYTA==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:J0fbzKEJ6Q==,iv:QZuHxxFa97qvXbq5I+YQJusK2702QMJZHJiA3zuIcDw=,tag:uASRzTMo7IxbYAfts1dqLA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:QnBKJ2NZ4A==,iv:vtrhBfR/iYW966XyuemThbGpmt0gPF+F8PaVJZGv6GA=,tag:7qcLn3LIFT/iy71RB1ykqw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:1X/WkrSdrW4pVRDUVnxj,iv:JughT2EIUD9lpTNnL8RuTABxmErbJOEjmZxacSiXJ1w=,tag:w85LhO/cJUWDt+r/TLUQwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNTZwR2dQdlV1ZWluY0NP
            c0lKa05DNjBnMHhHQm5PV3hZMFo1dEF5c0JRCjJ2YWxSVkN4NVBZYnFCa2diTTRO
            NFloeHIwNFYybUlFVzZvdlBnSktNMG8KLS0tIFRtODJCS2M5RjRpenRkbzRmU3BE
            b0RuZzU3VzNRWjg1YUxyQzBGTWhHN3cKmwNmBNQkPzd7o1HZu1UEGlJG/HEiNQmG
            /J0q7zNJ9o38wmUzC9Kl/CR+l3mgsQ+1QqxHQsaSntSMeVdPJN4cYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T14:40:42Z"
    mac: ENC[AES256_GCM,data:bqR5ABLBO9Ss9KcaUsco6Uwid6cLA/FDNfbdzCsbZVsKsyDZGn6rRk16olzJXKEn612YiR8e/v/FRw/RnAUTMcahQvL9AN3Wr0SFFDM8mZmQZ7sGGaVcNnDRXalGZ6ot1GiAPGydOkz20mx1zAsK7qo15Rqu4ukC+hqPxzMR2hY=,iv:l08eNQzTzXToS09Gugn5A+YoP9OVfiWQtn0k5Ykm/eI=,tag:KIy5CC9c7UZVSOf3qP5JPA==,type:str]
    version: 3.13.3
