---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-to-trakt-pvc
  namespace: multimedia-factory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: plex-to-trakt-pv
