---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-to-trakt-pv
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  local:
    path: /var/lib/rancher/k3s/storage/plex-to-trakt-pv/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-server
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
