apiVersion: apps/v1
kind: Deployment
metadata:
  name: floppy
  namespace: multimedia-factory
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/matchTag: "true"
    uptime-kuma.io/enabled: "true"
    uptime-kuma.io/type: "http"
    uptime-kuma.io/url: "http://floppy.multimedia-factory.svc:8000"
    uptime-kuma.io/name: "floppy"
    uptime-kuma.io/interval: "60"
    uptime-kuma.io/retries: "3"
    uptime-kuma.io/notifications: "Monitoring Bot"
    uptime-kuma.io/group: "Media & Streaming"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floppy
  template:
    metadata:
      labels:
        app: floppy
    spec:
      enableServiceLinks: false
      containers:
        - name: floppy
          image: ghcr.io/dannyvfilms/floppy:latest
          imagePullPolicy: Always
          env:
            - name: DEMO_ACCOUNT_ENABLED
              value: "False"
            - name: FLOPPY_REDIS_MAXMEMORY
              value: "0"
          envFrom:
            - secretRef:
                name: floppy-secret
          ports:
            - containerPort: 8000
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-rw.database.svc.cluster.local 5432; do echo waiting for db; sleep 2; done;']
        - name: wait-for-redis
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z redis-master.database.svc.cluster.local 6379; do echo waiting for redis; sleep 2; done;']
