apiVersion: v1
kind: Secret
metadata:
    name: floppy-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:/FTP6uls61miQkY=,iv:j3MWI2ntOrd1pntnVhEtRdATIZSoAPVgSsMCZ+77FnU=,tag:EHyiKFeDRVpFsgRfKX5w8w==,type:str]
    SECRET: ENC[AES256_GCM,data:d8/a81NZmtCM/g0vt9whctJ/oY73UOKCfWzcWhIwu48VcuTUpGaDY3DEBGMpdqXNaptdlxBlMx2XUfaGmU5tiQ==,iv:RF0cCiBUokX+wWrOVg3GyYiukpICfc4D5j0pnsdkj7M=,tag:p350+DCZpFCTJtLif4sqkQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:wFTkoe/ZSLz6iqxsgwmxW2Zrky/zHA0DZ+Hf1ZWGK3MqPjVHSwo=,iv:ku6YJo54r1ivZVVv+R2EQOdU2wqG4d/dn2CWfD2bLJ0=,tag:atKo1SMwP5fQ8PN1dh0NPA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:ING0I2Uh,iv:KJzTp7Q5ObnsYTmEzkmXX1zyy/Uh2hfT2fuG2BYmeyQ=,tag:J+wtu6CGEPUYQOcgTHsADA==,type:str]
    DB_USER: ENC[AES256_GCM,data:qO00Dd0+,iv:2DjsAIkDkevI8CZ4TViS5nnsa1GGM0dtPDo26K0z9U0=,tag:OW/UDnvoYMSmBW1fdLkWzA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:4Jhckccna3WFkPSdb77PxJXnm0G4H+TwSbL92yuqsznAdMeY4zRDnY++t7njAocb,iv:YwZ0ku3RrafUQc2aE57liFEbXU5eB1qV9RAme9k+uyU=,tag:BVJp1Sd4/07JZY1p7SOkrA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:W8c8aA==,iv:2Jp3LWvvgTTHPYAyUXKwOgpkaLRcm6sWvaEHCwwhKg0=,tag:f0R7DUicYB7YVQ5NIrxb2g==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:t/5xsKW/xuMcRqL6cEHVmi7r3hI3CMqEZVarjxSHjm4KKB1C57mVKFm8i9ECroN1NKKEAESAUtd20Hq4cd4Uj0ggd6EP2vZb/EtsXRM=,iv:0P9WPXNE0LTI0WTZkPbwdO9kXtrBZk9zt+8gf426TNo=,tag:X0wAwqJtZIBQGM+Jn6s3nw==,type:str]
    REDIS_CACHE_URL: ENC[AES256_GCM,data:1H7boWrlzUJTKtDloERB2eqVSq/nEkO76cfCJiyh/wDqr+zVka93iE8Fto9LP/cKFGlqrTc7kPwBXZ3FAO+sTEm4Je6X95yQ8bEbYUY=,iv:c+/pDo7XFqbQp3JdytXZT7JRoLtv5Rk8rqvR4axKlmo=,tag:XhRMuYEeJituOUNrj+rmFg==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:slAXHVBeW7j4c6Kqfqo7p4GeIk2hprLErsof13p0bL5hdHL283eh+t5PWZhQL364HZLDyD0EKp6MdhFpmLT1p38JY4ReNmwNN+zIlm8=,iv:KvoJ2/XhNLLdqTvC+4u99q5r5vnENoI1KqHu+88/tJU=,tag:Q/rUp7bYpLiYMnQvZz9Caw==,type:str]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:Qm4LEdK4my/Bxma1PAvScqqYjtHmbb7kQhxy0hwGdkEqVkk75btcuoO7XOQgQLcbH85z1IrEjBKOH5Qsv1VYfGOmsQNLu3EPCyKkO2o=,iv:O+coZjVnjAelQVptKERMAqQ0RaZEA4sWOxfCHO+UV/s=,tag:XqFAb/yLWjvnW2Z1myygeQ==,type:str]
    URLS: ENC[AES256_GCM,data:64BYQy5Yu8ylJKRfy4cM9gjheCazbMpD/wUduxidSjmp8DYI,iv:EKya+88oW80VLqpppCB8UNPHIwTriwOP6VJRE16rDSQ=,tag:rpAE1L2DvwMLUtlr9LEezA==,type:str]
    USE_X_FORWARDED: ENC[AES256_GCM,data:xgpeVw==,iv:fuGrTvHdpymWOmW6EytkGZJV/1XWh2Wfkge77bL2R08=,tag:v2xTxtBUWgY7Ch6KR1nLAA==,type:str]
    USE_X_FORWARDED_PROTO: ENC[AES256_GCM,data:fPfSmA==,iv:cJLu1rSifC5Y1fQzJ1NHwnU9nMc4OpD5Mdo0l2qbd/s=,tag:1a2u6ad6InmjQ6eg7xJceQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWTdHQzlES05OR21Kdy9W
            elh1TElJdDYyZnBERHhST3IxNlNxSHRnVzFnClhFMGJmTlh1THFvQ21zRzYvcG5R
            aFRxYmRWdXRJWDFqWTBSR1p2MXRNeVkKLS0tIDJMWFRSSWpXN1FZQytMVTZyRXBi
            dDFuNXcrbVBHUkhXeEFMVEJFek9GdVEK6BrLY86CnyFRgnKXsNhhxehPArpUL4hT
            L+0leF5CLCfgwToOsXCoYOAJ983P6hpAesDgR0SH0gDVlqa/kkeftA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:17:49Z"
    mac: ENC[AES256_GCM,data:bB8TkzuLj2Vzl/703V0jcKuoD6QG6DYqpy20mUDE5Wssvu+tZaE5vMaTRDV6vC386Ltwc/KHpEz6TyQWUnuhBypgUTUltq9WDVEWIKlJOtAYW7N8brCY1vlmHIWXEMmUx4wBOxPcMkmpxxvV5nm+/+NdRHBVxHvvG8B7OrGbxCU=,iv:138aHpaqXSJTFPC+2cNq1/hsG//lakRIm4rtRc2OnNs=,tag:M6OJyn8QVEV8TLvm5+3v1g==,type:str]
    version: 3.13.3
