apiVersion: v1
kind: Secret
metadata:
    name: floppy-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:H6i/hc3k7WfkxnM=,iv:VypgTHnJUThjShWLyVSOuq+VsuYw4BvBtTZliXDmHMg=,tag:wEydORsGE6i0kdQS+icxEw==,type:str]
    SECRET: ENC[AES256_GCM,data:e9FPue1H1UeYT+AQ5S2NY9pnIz+xGhvD9WnwLYadgKJCzCTpisvhUnKdvHCysmhUi10JPgvO1QRaOrmusQ0WfA==,iv:74AUkKlkfmvME6xBVffi0V9hUjFg1w3lMVSwzExT6VE=,tag:AVb5DEJHfgicglofeuY3hA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:m7KDdpXTY6lsrBgyyW1qm9Eiilj1y9F/IcSQtnJva92CyPIQ22A=,iv:Na77r9EqJzomNPy838inZpk+c50c3/Sxy6IwQPSATts=,tag:FeVA9/nnPXuEVhq/gmIOqg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Ey1Tolk3,iv:E+PzA2skW0vjqznf2b8SWZRbpPctt2NYBOIkIGb4jjs=,tag:3B2GEZhWc1PjPpLTDngQ4w==,type:str]
    DB_USER: ENC[AES256_GCM,data:px7S8QXR,iv:IzQWSg2YnlE/wULmvxXX7Kl4I5voR2K6phRH8baQBqs=,tag:HpQMgrEUNvMTDu/qRaMMnA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:m5jwuCCPHHluomSu5+W5IQ6l//2kAqzY6FjhrdQuDJJaUSDgcR2mDUHXkSgVxGGv,iv:9DsgAfX4YeRUsxgwqq3iyp6Qe3H885Hiu8aqYsrQIcQ=,tag:BYgBA8xM0TpALeJlV3Dtcg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:grukZg==,iv:bFBTH4bp4Ed7MRepNrG+IKisGIqPVN56krqjunjniLk=,tag:qW6Gt3SKecrhKhmuwX2Ouw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:m0EBkUQCT+pMO09jYPWGdTRICqv5R9rGP87ZGCgdi0OChA+eLg9qtJkm+7tGYbsW+/R5yjPkdTkp4ke1cZrvq5ebnEJGEFc6djmS9PE=,iv:4B6mRq+/TaNnTSYlc9VWQ9wT4CJcjCwSLZoIWVlvSug=,tag:Q6R1bNNaFPkYbTmxzFCW9A==,type:str]
    REDIS_CACHE_URL: ENC[AES256_GCM,data:G3D3lJu5LPhDKS0OHirGPahKeFgfcrr9g4qg88g13kFit1dQNvOSzFq6y+ZaBW14JXd24jwXpQYF5XUWwR7OfiXlyn9561vzaY+r1aA=,iv:68Zwx37a/74y6XR6ucS7A5z46epytWSqnl5mm3iP7Yw=,tag:gktNicI2dFAqLUFBt/NPcA==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:5W0EB/tvW3bofxzJwtiMaYLuKSrVP0olWFkweOn4znoXQhRcbc7KvZ1IkwROHKJkKR1Z9kOIT5fHrKHRKJLZKrdyMnOjWdStkxAERnw=,iv:z8Zb0WY75BR+Qa5548uY1waHnMZLA43JnzN6LiPuSNs=,tag:yBd8/0cJeVCxz7najgDd/Q==,type:str]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:jQKlC55QOvYpj8jheaNMkNI/NI+PX0ulpces5EJaKStm9FuDTNKroQ/l/yA2yqOVKA+oPdk06n+FMIflPaP6KYuTyInGfQntU9J/QU0=,iv:a7sqk/Vd6r8BqLvmeHntduTU4z995V+wtCpSJu7uPnI=,tag:FfO5DAjhrUVzGHCvL1dC3w==,type:str]
    URLS: ENC[AES256_GCM,data:Fxqlw4mEKi+E4igosPTWy3nedbsygwjlm0/hKt+xO/IPD3iWGzKV1DGzpWQXSnXao73TRHj9CL+NNGATlAa4vdz3NrojOJhphlA8kgDB,iv:Zr6z6OzaUeXEPWWJPlYVERBv3Zwwmq+UXNriDqELtzM=,tag:JYdOPZ7sOIgkppBdZOYy8g==,type:str]
    USE_X_FORWARDED: ENC[AES256_GCM,data:xnPbFw==,iv:YjEZZXXG3ystft01iCHhgrka82VvVpqgiIutusc3JUM=,tag:qFJ9ZgAZjIoZBFUDpaRabw==,type:str]
    USE_X_FORWARDED_PROTO: ENC[AES256_GCM,data:uYJG2w==,iv:EPGmw+4ZaW7IShemADzx/QI7AKVVcdqkr+qCrSHWJaw=,tag:z74K+BBlxYY3Ghse8/zLng==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:BPrUTNsLS8T7kEQ7RkOFf79Cf+0K+fqz54ZDI6ULHAw=,iv:K7hSMXlQpzxG0xqKUH5ZRrMcw9hqUpXcAnG9ZHxf5Dw=,tag:+7TO5R96KRQW+dPe0/Nfwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjczTTdHM1cvWFVtbjFC
            NGZpRVNadi9xN21xS0ZpbHc0YTl1ZkNxT1VRCjdMN2hRazNPemhnSVMvcTdFUS9v
            U0E3Z2RuZ2FuUHFZTnhWM2lBYnFqZlkKLS0tIDlaWjVHc0FWcU8wMlJBZlh3UWN3
            U3BrMWwwY25aaFNSNDhieTVMMzdWajQKq1gTAiVQ15rV/SFqN8fcbFqO0qdk8/gj
            lbSdvx0wlaiwIDFy735HaGs1hrjDDujB5/InDEpWiTWUr4kuixwtSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T10:10:26Z"
    mac: ENC[AES256_GCM,data:aLr643Ya9tsJS+zuROj6coXGnTYxpjlzLUdInnWmpWngrhznfWX7F7nOQAUdRAaPUU+Fneuz3BhHlqgmvtfuP5tVsSslduOYEiPBf6edSjDdEB9DLkGyC1LfZPkBED2N5jLGknqT5Wwg+5sua8VtA5f9N3e1aIxv0zHKaHR0TwE=,iv:inzBHaZv8VeuaJdGCcwkoFfow0WJSz5v0zZW4YNTlh8=,tag:fyAKukCdOdK4E0gSFcnwjQ==,type:str]
    version: 3.13.3
