apiVersion: v1
kind: Secret
metadata:
    name: floppy-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:2GuU7umU3DBaWDg=,iv:qSIwpLpPDHfkEFvRu0aQAuERWMqcxz2TgpHsnIiEMps=,tag:EWaGszBRWIMRqSP2HLO1Hw==,type:str]
    SECRET: ENC[AES256_GCM,data:2tF/3MN5DLVwuzJUOAGYS05n5IzokOZYiTs2TcOPVjxqk4rkyX78pIx5fvAPSGlDc7XPH0kjaLftrjsWREeZVA==,iv:vIu5FO7vHXK7zo6wSOtCDSe7YNXNtLdG375GMY/zOB8=,tag:0d4wTRdnFk/aGipj/EyXxw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:15FE2CVOUDrSebJdQNKTYGJr39D0Kd3QslzHJm8vq3YEEoS7Qmg=,iv:bUIEXO6NeAOXqETelUMsctNATlruKHYVMptne5wuv1k=,tag:qBTwRsu7rx7ned66aUY+kw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:wzYCxXGc,iv:o3QbqyxFRhLZfMnwT98ACeXW9jV+cnt9pm+xtzWqx6Q=,tag:U3x/Ic1i/7u6XFVe2WAP0A==,type:str]
    DB_USER: ENC[AES256_GCM,data:B6/ywgSj,iv:G4X0jCekV1nRHYnj0AItil5L1Roa6OBtJt/5rcaKcM8=,tag:spg3CZtOzFozeSk+rKNjfA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:zu4mJwYeB7tNLbLN9mUAPc8SUhizoS1HalLCifWYBRa/QNWU/RZlE6AALRiKvT4b,iv:zml/ERK3v/C4yoMDwE8vfgxqG6UknuEND+OVp7uI3qE=,tag:eF4x6i6Aof4C1qp4GziQ7g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:BwKyPg==,iv:MxVGs67imr7bmmafBZ8oPSA1szPUbxEiOpK+v2TLNA4=,tag:MAxRHIfEO2IG85Nqz8zVVA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Y/4EXjgYRzFzWRSb1A8nAF9ZwDj/W3bJNL9gkS19ZWUeqbJQJq/s/PWlKux/ImUUuJnXhps4fwekGetPv4BczCw7z7ynL9wg+UlR0sc=,iv:uia7lRKTg0b3StBgxgaRo9GYe/MXZxvb1HRUIGxGZts=,tag:abBOVGctVcdApLttlAprVA==,type:str]
    REDIS_CACHE_URL: ENC[AES256_GCM,data:4+RlySZePhdCmt/mb/y6ocH3ajwUdbW+kMW3vpWApSC9IGgGvViWa1jS8xyB24o5L6DsBrVvVc+NTNCNIsdIY7dBXGkxXtvBU6zWNHs=,iv:FfZSUQK9r0RZkXM/WiwzYtBneIJ6KDKBU7lNLom/hbQ=,tag:360e0dt62trNOBdvelUMUw==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:qFfEN9/7yBRopC6gJyRNrSGlfXvzUT/tpwW5oupMcneH/SzsIY9LHNAgWZYyVV2AsfouYCPq/HbaXGnPEGhFZ8qluHH18cDmYqYsP4I=,iv:zx8U5iPTl+5oEdh8SWSyH8GmB63X7pg6lqBp2qagdSc=,tag:HaNxOqgkeI05xwPZ5fFMyA==,type:str]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:mH7/HpHRJakAKIXBSmjpKxr3bAlTFS2uaFigE4VpGjucdpS8f3rI8hsy6nS0ZCLQD70M+E9yWFjUoNiv7gk2nZOo7hX6PAn5nwrwOSY=,iv:x0DVnbazTrHrqW3IDStsRF7Q5beRqIbCwIW+zIVGRCw=,tag:rIBei5UO3ODr8GvZs4AtUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSjRmMXkzdS8rTGJxeE95
            bnJGQUdYd0M5TEtMWmdvRWlvR0w1WWFVWndvCjBzUjNYbGp4MXhOdk1wUHBSWmhz
            UjArWnZDSHl0VnNwT0Z1bFRjdVNxK1EKLS0tIHduVDdOT0tQSllwR2hRRTdTczlj
            c3BJZTd6NjFsM0sxZWF2U0ZmODMzbVEKqA/LmONsOApNGxfMgqcPCxTd90c+WJ1X
            M8C9rD9jizpgfVlkSKeUTnOp49EwM23/39lCWLs7HvpCajAT3r6G3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T19:11:17Z"
    mac: ENC[AES256_GCM,data:ptIiuvVK8eEM5Qr53o7uknhJfT2mI0UjduXNEAL+q8FWSaQ9+IFthbSrW9mKUyFdjkhZ9eSoARvFsjBRcEvr7Z8KU8gG0DPCydVa4bJWZzvdumE79W134uqJuH2cYHdlr76crAMWiIV7wJseh46fd1CCY749B4SuOj38SdqczCs=,iv:gwCvSpWKjKO2g2daqNdDCEKAMMmOXZ1Z2fAcQfgvHZU=,tag:3rjIPDmp6C/BrVzreX8lsw==,type:str]
    version: 3.13.3
