apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: flux-system
  releaseName: cert-manager
  values:
    podAnnotations:
          uptime-kuma.io/enabled: "true"
          uptime-kuma.io/type: "port"
          uptime-kuma.io/url: "cert-manager.cert-manager.svc:9402"
          uptime-kuma.io/name: "cert-manager"
          uptime-kuma.io/interval: "60"
          uptime-kuma.io/retries: "3"
          uptime-kuma.io/notifications: "Monitoring Bot"
          uptime-kuma.io/group: "Network & Connectivity"
    controller:
      podAnnotations:
        uptime-kuma.io/enabled: "true"
        uptime-kuma.io/type: "port"
        uptime-kuma.io/url: "cert-manager.cert-manager.svc:9402"
        uptime-kuma.io/name: "cert-manager"
        uptime-kuma.io/interval: "60"
        uptime-kuma.io/retries: "3"
        uptime-kuma.io/notifications: "Monitoring Bot"
        uptime-kuma.io/group: "Network & Connectivity"
    webhook:
      podAnnotations:
        uptime-kuma.io/enabled: "true"
        uptime-kuma.io/type: "port"
        uptime-kuma.io/url: "cert-manager-webhook.cert-manager.svc:9402"
        uptime-kuma.io/name: "cert-manager"
        uptime-kuma.io/interval: "60"
        uptime-kuma.io/retries: "3"
        uptime-kuma.io/notifications: "Monitoring Bot"
        uptime-kuma.io/group: "Network & Connectivity"
    cainjector:
      podAnnotations:
        uptime-kuma.io/enabled: "true"
        uptime-kuma.io/type: "port"
        uptime-kuma.io/url: "cert-manager-cainjector.cert-manager.svc:9402"
        uptime-kuma.io/name: "cert-manager"
        uptime-kuma.io/interval: "60"
        uptime-kuma.io/retries: "3"
        uptime-kuma.io/notifications: "Monitoring Bot"
        uptime-kuma.io/group: "Network & Connectivity"
    crds:
      enabled: true
      keep: false
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
