apiVersion: v1
kind: Secret
metadata:
    name: cert-manager
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:l7v6Yl8hyVENAKcQoPmeF/72HpeeKtJJr+npRs70pcULD8gZ0gVSTBvDqTWIT1GP/+ILuAI=,iv:J1LWBzhjOlg1268oCXtZ1il1QmimtytSGJQwblrw+zw=,tag:ssq12V4XdAHTu3Hcu/NfCw==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbUdTeFBXRURzOFF1N0ZL
            Q1Rud3V3THFJUTY4OTdqUEJucU10dmxPcVFrCkZyRjB5L2pEc3VXMFgxR3ZuWnlE
            czBndHFWdTZ0enhmaDYrVG9ZUWYxdVEKLS0tIDdJOE1KSWVSNk9ueVlsRlZKNTY2
            V21UV1VLKzlBWTdmc3g1aU5LbGo3RmcKsMaTqYi5LSDOSeQef4ZdnHhNiw80yxrV
            S2Qnav0kjsz3GDuhFD6EoRKBiJUx1Ke1APe409u6iIRsdQNvpfQl3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T09:09:57Z"
    mac: ENC[AES256_GCM,data:TdYuUduOgo2b5vMZpIyYVd+cSa+OxYLCXUh8Z2drDaS9m4tS+mFwbK9ZRRD06pvm96vHxaqBi2rDX2k9MZSIvwG+DdiYMVmBwXCVRhROXBRUbn0vHHoFO4bjsq8Lup9thjNQlco8aI79lNHXyZ9fwbp3mvmO6/nMHBEaVfEPJ2M=,iv:62RdsTnJFBdn6hug+8lLBsng9Ho1wma71FyjJh6vd2s=,tag:Wo6+PpSK12FQI4JHoOxu7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
