apiVersion: v1
kind: Secret
metadata:
    name: cert-manager
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:PYwDgHiwHlHJZFWVjC1rMXHtC1MFBdAauRbr9HbTa85qfR/Mnz2JAw==,iv:+174wHiV2VWEpGb4w77OBv/qt6nb1wosJurYTVcGU/A=,tag:7dnnlmiJcZBzGv+jc9H8wA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbUdTeFBXRURzOFF1N0ZL
            Q1Rud3V3THFJUTY4OTdqUEJucU10dmxPcVFrCkZyRjB5L2pEc3VXMFgxR3ZuWnlE
            czBndHFWdTZ0enhmaDYrVG9ZUWYxdVEKLS0tIDdJOE1KSWVSNk9ueVlsRlZKNTY2
            V21UV1VLKzlBWTdmc3g1aU5LbGo3RmcKsMaTqYi5LSDOSeQef4ZdnHhNiw80yxrV
            S2Qnav0kjsz3GDuhFD6EoRKBiJUx1Ke1APe409u6iIRsdQNvpfQl3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T02:32:22Z"
    mac: ENC[AES256_GCM,data:nWlLnzINHvIiFq7fYU+33SXsnPgikY72oVbxJdl497iBUjQbCsB6UTFcfOsS6rzV2r3Mj7KoueaGuoK6HFTIM3eVmTV4oXy/UW0ZwR+R6ug00aAfxXx9DVT0pmBzZWweJaX5LAi4KtLOA0NtvtekgF2o/x/vFLcfvYC7TMEQxNw=,iv:vHn+XF9ELDtVKlLklyZbaLH87ic7PdgYZqJhKz7urbE=,tag:9MRd5nQo6XyjvTw1wfIEAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
