apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: database
spec:
  interval: 15m

  dependsOn:
    - name: mariadb-operator-crds

  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 1h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    currentNamespaceOnly: false

    metrics:
      enabled: true