apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: violarr-data
  namespace: multimedia-factory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: violarr-data
