apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-wg
  namespace: multimedia-factory
  labels:
    app: qbittorrent-wg
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent-wg
  template:
    metadata:
      labels:
        app: qbittorrent-wg
    spec:
      containers:

        # =========================
        # GLUETUN (VPN gateway)
        # =========================
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.41.1
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - name: http-proxy
              containerPort: 8888
          envFrom:
            - secretRef:
                name: qbittorrent-wg-opts
          volumeMounts:
            - name: qbittorrent-wg-wireguard-conf
              mountPath: /gluetun/wireguard/
              readOnly: true
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "ping -c 1 $(echo $WIREGUARD_ADDRESSES | cut -d'/' -f1)"
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ping -c 1 $(echo $WIREGUARD_ADDRESSES | cut -d'/' -f1)"
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

        # =========================
        # qbittorrent-wg
        # =========================
        - name: qbittorrent-wg
          image: linuxserver/qbittorrent:latest
          ports:
            - containerPort: 9696
          envFrom:
            - secretRef:
                name: qbittorrent-wg-opts-secret
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-wg-config
            - mountPath: /data
              name: qbittorrent-wg-data
      volumes:
        - name: wireguard-config
          secret:
            secretName: qbittorrent-wg-wireguard-conf
        - name: qbittorrent-wg-opts
          secret:
            secretName: qbittorrent-wg-opts-secret
        - name: qbittorrent-wg-data
          persistentVolumeClaim:
            claimName: qbittorrent-wg-data
        - name: qbittorrent-wg-config
          persistentVolumeClaim:
            claimName: qbittorrent-wg-config

      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1
      hostAliases:
        - ip: "10.43.98.59"
          hostnames:
            - "qbittorrent-wg.multimedia-factory.svc"
        - ip: "10.43.67.209"
          hostnames:
            - "sonarr.multimedia-factory.svc"
        - ip: "10.43.26.74"
          hostnames:
            - "radarr.multimedia-factory.svc"
            