apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wg-wireguard-conf
    namespace: multimedia-factory
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:EN+qmpYCMSK+Rm5960ppaZjadO/WyzF+UkpZJXrDHa51jDbrQysx9vFjuS9jU9ul2ELHARP/wg62VH1K7UwJzjwOOC4e7Gm763ER5uetE0VBbuAwOF9W0onebjaqVnGrLJgg6lElkylOJglWnhekn9PPI4WUCAfF3E3YijCdAuef1mcHJkX1V3ibOgADjOt712zy9TX1xQuaH2PSmD7LldVGjy3JV8251OJM749kgXUCGa9rXv1Qbgelccg4kfdtCksjejYzjBsKn5OBB838qZ2vNnf3Dyy7Rln480lvYnKK16JjA0aBVdUZbmQgMN4DvQjI9tPxoi+m2Hw35vUYokTp+JoZK703ezvxQlsGqDgVGupmQXiMcD7UUTGu5lqQPg1i4PBEU6kwIqLrfQCUtFuaG733AIpIdOzw,iv:HEuHKRa97EdJab35U/3ZN8ki/YFCyZ+I0c6eVRfjMoQ=,tag:ECDfKJ0/rvbkRm1h7PKCkQ==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczYyRXRoelV6bDFOVEFO
            ODFxN21KOGZLdlg1M09Pd0ZFM1hnbHJiNnc0CkVPVUNjbTZDRkkxa1NzSllHSmdF
            S0FJUmVVYTZDWmxmanhNaXMzdHR4NUkKLS0tIG04NGVyN0dVVmtSMXFOS28zLzMw
            RGV3cVZiT2k2cXN2Q212OU5MTklMQ2cK5OacGsku0QXqHHk4CSoo+pYdxn751zeL
            AtP+tNKt2AhhzbFdQ1lclBPnK/pgglvXM30XtSOtN6AhoU1MiQ4RJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T14:53:53Z"
    mac: ENC[AES256_GCM,data:jXQ9fRTiHpaalaN1TRU9HVTXCmT5EWFu0RM8SlLAP6jF/8vnKPpO9PWQ+M2+A1A5DhOywr62z97KEQ4jtfyBuw+/EXBmTJHnQv4nhDm++ZnPIkJ7e/77r5miUtkZ6hm8esqXt+xpfKaPySsvbj+vDhvmoG3pv1H8UBzWhU5upsQ=,iv:ZH4qdDK2XFtnBnrqsb8faPrLo+y/lCVCeMYbpmEUdeo=,tag:Y4eKtkgNRiPoL7R7r+m6Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wg-secret
type: Opaque
stringData:
    WEBUI_PASSWORD: ENC[AES256_GCM,data:mFT58J+BnK/wIkO9IjoNHZON1Ws=,iv:UlOY1ULCeFxg7kRkp31/UHAMupKtab0Q3TaPNkSkhOU=,tag:2EZVMaRSaeBaXTFMGWMk6A==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczYyRXRoelV6bDFOVEFO
            ODFxN21KOGZLdlg1M09Pd0ZFM1hnbHJiNnc0CkVPVUNjbTZDRkkxa1NzSllHSmdF
            S0FJUmVVYTZDWmxmanhNaXMzdHR4NUkKLS0tIG04NGVyN0dVVmtSMXFOS28zLzMw
            RGV3cVZiT2k2cXN2Q212OU5MTklMQ2cK5OacGsku0QXqHHk4CSoo+pYdxn751zeL
            AtP+tNKt2AhhzbFdQ1lclBPnK/pgglvXM30XtSOtN6AhoU1MiQ4RJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T14:53:53Z"
    mac: ENC[AES256_GCM,data:jXQ9fRTiHpaalaN1TRU9HVTXCmT5EWFu0RM8SlLAP6jF/8vnKPpO9PWQ+M2+A1A5DhOywr62z97KEQ4jtfyBuw+/EXBmTJHnQv4nhDm++ZnPIkJ7e/77r5miUtkZ6hm8esqXt+xpfKaPySsvbj+vDhvmoG3pv1H8UBzWhU5upsQ=,iv:ZH4qdDK2XFtnBnrqsb8faPrLo+y/lCVCeMYbpmEUdeo=,tag:Y4eKtkgNRiPoL7R7r+m6Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
