apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wg-wireguard-conf
    namespace: multimedia-factory
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:wis0VpiDWR3LsjKkTDRUEFZVw+lm9SFbpkTXDPKnBYL9GpYjrHPnPwUrY4Qs9OjjgURfOTI1AFUxBq0Qv8jVpBCIqIS1FxTLAgPChiKyV4zU0DjE0xP4qXgsV3yu1hyfxqlUHNJybOO8fMLYteQJWx/23MCxvKjJxCxfUgf3d+hAvlNe4Pxwt91DX38Dd+xwSGNr1NHQIxNVdt8EKgGwCd2KBoge0mKBjVowaqpkDfeW9l1uU7csKML1KztEDQVRa8W5yNVuDaX3VSF8pcV6RRxF19IFZAXWmo5dib2BGCHL4zHy0V8jWbhPqVryofKNc2T2uelHL839UrzoFnTi7kzPqOD2ecr0rP/ur+R20ALZNCiyqravlpNO+Md6+lVgCPCGMeV2uDJZUAhL4MMwwOTanKWIDduK6fuRRA==,iv:etlJQ94kQziisUlg03d8VsrNheFPEVRhtiqDZ0VSUFw=,tag:GACrQA7MjxvyNgM53Sw7nA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczYyRXRoelV6bDFOVEFO
            ODFxN21KOGZLdlg1M09Pd0ZFM1hnbHJiNnc0CkVPVUNjbTZDRkkxa1NzSllHSmdF
            S0FJUmVVYTZDWmxmanhNaXMzdHR4NUkKLS0tIG04NGVyN0dVVmtSMXFOS28zLzMw
            RGV3cVZiT2k2cXN2Q212OU5MTklMQ2cK5OacGsku0QXqHHk4CSoo+pYdxn751zeL
            AtP+tNKt2AhhzbFdQ1lclBPnK/pgglvXM30XtSOtN6AhoU1MiQ4RJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:44:34Z"
    mac: ENC[AES256_GCM,data:roXo0n2+pTMQa3BBfAU5d96iNafdaKp9q8HjlkbSWtTp+6HwPlAVquBu4ReTHqEU1daVbC/59FqWVfjsR+OPwdiO1UyHHb6w0dLVzzFMbSndSPDsFbd4Xo56dQQ5MRWgdTfdKlbfqDjPZaTAJjJmBJqDOrsVR706sTWfLxqf+2w=,iv:m487fmHc8lVJS00DkeS7wsmPOOuvrrfCZEm7gz/1NKg=,tag:/CedBUFv2mumGXyjTJ1zNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wg-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    WEBUI_PASSWORD: ENC[AES256_GCM,data:mFT58J+BnK/wIkO9IjoNHZON1Ws=,iv:UlOY1ULCeFxg7kRkp31/UHAMupKtab0Q3TaPNkSkhOU=,tag:2EZVMaRSaeBaXTFMGWMk6A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:uJM7+gWePEUKQZaT39c=,iv:0XdLB4jKBXE5WOBae9ARscO/NKfjRlRCTFWJ+EaUkQ4=,tag:GWwRWgQQ+s3o2R6sUIqj9A==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczYyRXRoelV6bDFOVEFO
            ODFxN21KOGZLdlg1M09Pd0ZFM1hnbHJiNnc0CkVPVUNjbTZDRkkxa1NzSllHSmdF
            S0FJUmVVYTZDWmxmanhNaXMzdHR4NUkKLS0tIG04NGVyN0dVVmtSMXFOS28zLzMw
            RGV3cVZiT2k2cXN2Q212OU5MTklMQ2cK5OacGsku0QXqHHk4CSoo+pYdxn751zeL
            AtP+tNKt2AhhzbFdQ1lclBPnK/pgglvXM30XtSOtN6AhoU1MiQ4RJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:44:34Z"
    mac: ENC[AES256_GCM,data:roXo0n2+pTMQa3BBfAU5d96iNafdaKp9q8HjlkbSWtTp+6HwPlAVquBu4ReTHqEU1daVbC/59FqWVfjsR+OPwdiO1UyHHb6w0dLVzzFMbSndSPDsFbd4Xo56dQQ5MRWgdTfdKlbfqDjPZaTAJjJmBJqDOrsVR706sTWfLxqf+2w=,iv:m487fmHc8lVJS00DkeS7wsmPOOuvrrfCZEm7gz/1NKg=,tag:/CedBUFv2mumGXyjTJ1zNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
