apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wg-wireguard-conf
    namespace: multimedia-factory
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:wis0VpiDWR3LsjKkTDRUEFZVw+lm9SFbpkTXDPKnBYL9GpYjrHPnPwUrY4Qs9OjjgURfOTI1AFUxBq0Qv8jVpBCIqIS1FxTLAgPChiKyV4zU0DjE0xP4qXgsV3yu1hyfxqlUHNJybOO8fMLYteQJWx/23MCxvKjJxCxfUgf3d+hAvlNe4Pxwt91DX38Dd+xwSGNr1NHQIxNVdt8EKgGwCd2KBoge0mKBjVowaqpkDfeW9l1uU7csKML1KztEDQVRa8W5yNVuDaX3VSF8pcV6RRxF19IFZAXWmo5dib2BGCHL4zHy0V8jWbhPqVryofKNc2T2uelHL839UrzoFnTi7kzPqOD2ecr0rP/ur+R20ALZNCiyqravlpNO+Md6+lVgCPCGMeV2uDJZUAhL4MMwwOTanKWIDduK6fuRRA==,iv:etlJQ94kQziisUlg03d8VsrNheFPEVRhtiqDZ0VSUFw=,tag:GACrQA7MjxvyNgM53Sw7nA==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczYyRXRoelV6bDFOVEFO
            ODFxN21KOGZLdlg1M09Pd0ZFM1hnbHJiNnc0CkVPVUNjbTZDRkkxa1NzSllHSmdF
            S0FJUmVVYTZDWmxmanhNaXMzdHR4NUkKLS0tIG04NGVyN0dVVmtSMXFOS28zLzMw
            RGV3cVZiT2k2cXN2Q212OU5MTklMQ2cK5OacGsku0QXqHHk4CSoo+pYdxn751zeL
            AtP+tNKt2AhhzbFdQ1lclBPnK/pgglvXM30XtSOtN6AhoU1MiQ4RJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T17:43:20Z"
    mac: ENC[AES256_GCM,data:vkQ73HRHe8KGa8oA8kc+em9409La5AsgUlvrBQsRJqVIJMVSFNm4o/Lju6sPyQFRNh/Z3mPbfLwrETwyY34M8daOLude+M+EADPSXkg8TYo+Ze5V59KsUoirVLx0oYZfc3OIoQ/ctasP/1UWudO6zF7QQVsKy7jgMG/+QQlrEfI=,iv:eETdf8un9lTgaE8VcuC583Www0gCZ4tdN8FKYWHfY6s=,tag:kKoRlRwWipIpdhVYPPXYwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wg-opts-secret
    namespace: multimedia-factory
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:wqLPa6pFMOZd,iv:7XsjEzK+Qo5Ebczysaryy5K0MYVlPyd9HX/0dGTP8lo=,tag:nXgQnXUOxTqD3Bmgtljz+A==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:SFDcThNa,iv:OWg6oJT3qftsRE5gGqBZR8qGZprMqHrVuz+iSHbP+A0=,tag:eda/UcQTZzUEeWaKb3MF2w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:uJM7+gWePEUKQZaT39c=,iv:0XdLB4jKBXE5WOBae9ARscO/NKfjRlRCTFWJ+EaUkQ4=,tag:GWwRWgQQ+s3o2R6sUIqj9A==,type:str]
    WEBUI_PASSWORD: ENC[AES256_GCM,data:mFT58J+BnK/wIkO9IjoNHZON1Ws=,iv:UlOY1ULCeFxg7kRkp31/UHAMupKtab0Q3TaPNkSkhOU=,tag:2EZVMaRSaeBaXTFMGWMk6A==,type:str]
    WEBUI_ALLOWED_NETWORKS: ENC[AES256_GCM,data:IiZOru+RKw1MoP5sMucfE6HKdlQJwL19VkpO2XlVpVp3RDikEjNBRB0gJ+bWRPYhhKpx,iv:g4UNc7nCFlAoiGMEeBA2jFdJOHVyNEBmNjiIWLE7z+o=,tag:MBz1WFp6Nt7Kbv9CURieng==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczYyRXRoelV6bDFOVEFO
            ODFxN21KOGZLdlg1M09Pd0ZFM1hnbHJiNnc0CkVPVUNjbTZDRkkxa1NzSllHSmdF
            S0FJUmVVYTZDWmxmanhNaXMzdHR4NUkKLS0tIG04NGVyN0dVVmtSMXFOS28zLzMw
            RGV3cVZiT2k2cXN2Q212OU5MTklMQ2cK5OacGsku0QXqHHk4CSoo+pYdxn751zeL
            AtP+tNKt2AhhzbFdQ1lclBPnK/pgglvXM30XtSOtN6AhoU1MiQ4RJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T17:43:20Z"
    mac: ENC[AES256_GCM,data:vkQ73HRHe8KGa8oA8kc+em9409La5AsgUlvrBQsRJqVIJMVSFNm4o/Lju6sPyQFRNh/Z3mPbfLwrETwyY34M8daOLude+M+EADPSXkg8TYo+Ze5V59KsUoirVLx0oYZfc3OIoQ/ctasP/1UWudO6zF7QQVsKy7jgMG/+QQlrEfI=,iv:eETdf8un9lTgaE8VcuC583Www0gCZ4tdN8FKYWHfY6s=,tag:kKoRlRwWipIpdhVYPPXYwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
