apiVersion: v1
kind: PersistentVolume
metadata:
  name: steam-headless-home
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/rancher/k3s/storage/steam-headless/home
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: steam-headless-games
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Gi
  local:
    path: /var/lib/rancher/k3s/storage/steam-headless/games
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
