apiVersion: v1
kind: Secret
metadata:
    name: steam-headless-secret
    namespace: gaming
type: Opaque
stringData:
    #ENC[AES256_GCM,data:kl53UReKlN8+bMGwe1s6,iv:dFUe/EvcNZKpd3syMcrOgnygL8KPg/VP9rtJeRQdZzQ=,tag:ITqr6HZYsj3QZP2mrgWUIg==,type:comment]
    USER_PASSWORD: ENC[AES256_GCM,data:5d4Jf+ndZvs=,iv:UGuFboL4r0uEYwbck/7aO+oDiv8hg/Yv/ogCVzdPqIQ=,tag:tk28beYIme1nd0g3plWaog==,type:str]
    #ENC[AES256_GCM,data:LRXxe/5ub81AgsKofosQ,iv:xs6Dt9V0ijrbbUU2Fr7/AQmEYLqJAC5j+CDV/0L2kGI=,tag:l+psXHgmXnCn0twqVP/KBw==,type:comment]
    SUNSHINE_USER: ENC[AES256_GCM,data:GhvxXnE01/8=,iv:/51DnDM4F70iVbHD/YCAgvIDSKQPCnxt2DexHnQd0Is=,tag:lg5TEX5h0u7z4N8w4nHNoQ==,type:str]
    #ENC[AES256_GCM,data:PYOrmToJ8ldJgPHCd8X9,iv:LuXfDL16Sq4cbTgQ7/EeNVat7WibeTrJ9GNsPEvJnvI=,tag:gXEbFzgHB/zWuM0sUh3reA==,type:comment]
    SUNSHINE_PASS: ENC[AES256_GCM,data:JgYcX06AQdA=,iv:S3/JJJkcO1e+XJ4hZtBPuX3L0nzfRPfOgdog1fnqcTU=,tag:DdvTvSVDs8MuodaJ9QZNrQ==,type:str]
sops:
    age:
        - recipient: age15kgnnd0nlu5vxerhfcrzh5y77x7efudnk74sk4d6z3zn29yltc5q25r54a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSWlxMWE4UDFLL3IzRklx
            UnF2Ym5nTEhaZThOdnc1ZU9EbjFVQmhjWVNnCnJZQXdESUwyVGVGWnhLaE5WV2dL
            U2hxTzlvMXl5M3hJZmpsaW82VjNmTkkKLS0tIEhNaDI0QnNRcmVDZlFZL01Xa0Jw
            anpuUmNQVnFoQWliRVFUSERzVFRRUncKwWDS21qx2KGEM4NldtRghjOaQ8LhLMLu
            HWd0+haibTTloEvmVPUKqAuyddgQrlp7aeucsBCjCFMWwtPhf8qliw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T13:03:51Z"
    mac: ENC[AES256_GCM,data:tycaSSmaXMdWCNKasP4dHRezeSMxOTrVPGXHtH9DT2NAYPQwHOYkf8JcV4tw8ezvrZeEjydEbB3FCumXVDQ02jarfDOlAwZ0J3GfOfKf3RF1NJx2vrk4usBX7/jU5bK/tZN0X5U8/pg+uJ2ZibpFye83WwFAVAeF06/CrR6/GY8=,iv:Md7KtFv7klveDzM3zBJo8+QtGR75utxJq272bHguv5U=,tag:cYbOWiSxtISbjGAN26kMkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
