apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: uptime-kuma-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /mnt/md0/k3s-storage/uptime-kuma/data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
